kiagnose, checkup: Use k8s client-go `Until` tool for watching the job
kiagnose/kiagnose pull request #100
Opened 2022-05-30 18:40 UTC by EdDev

Kiagnose creates a checkup job and waits for it to finish.
The current implementation uses a watcher with a self curated logic to
process the events received from it.

The client-go tooling module has a `watch` package [1] that exposes the
function `Until`, implementing all needed mechanics that are required to
process watchers events.

By using this tool, it is now possible to drop our own limited
implementation.
It is worth noting that `Until` also handles possible connectivity
issues between the client and the server, increasing stability in case
of connectivity flakiness.

The change is following the work done for the namespace deletion [2] but
includes an improvements for early termination:
- In case a DELETED event type is detected, fail the waiting earlier.

[1] https://pkg.go.dev/k8s.io/client-go/tools/watch
[2] https://github.com/kiagnose/kiagnose/pull/84

Note: The early exit from the waiting does not include the ADDED event, as I am unsure if it will not be received as well (given we provide the resource version for the initial creation).

2022-05-31 07:10 UTC, RamLavi commented
@EdDev I can't fully understand the commit message. can you rephrase? Notice:
- typo: "It it".
- You are talking about the go-tooling but not linking it.
- You are referencing to another case "It it similar to the one..." - it is not understood unless one reviewed it that case, you need to either link to that "similar case" or make the commit justification understood standalone.

2022-05-31 08:12 UTC, RamLavi requested changes
nit

2022-05-31 12:11 UTC, ormergi commented on kiagnose/internal/checkup/job/job.go
> +		case k8swatch.Deleted:
I think its odd that on Deleted event it will exit with `unexpected error` but for other types of event it return silently,
other events are not expected as well isnt it?
Also I think `ctx.Done` should be taken in account.

How about changing this switch to include:
case for `Added` & `Modified` events, case for `ctx.Done` and  return `unexpected event` error at `default`?

2022-05-31 12:25 UTC, qinqon submitted a review, later dismissed

2022-06-01 07:08 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +			}
Although it is not a must, I find this safer for potential future changes.
it is true that the `Until` function is not passing in any LabelSelector, but this is an implementation detail you rely on based on reading its code. It does pass in other options.

I think we should not rely on these implementation details and assume nothing about if the label selectors are already there or not.

2022-06-01 07:12 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +		case k8swatch.Deleted:
I only optimized for the parts I am sure about, I am not 100% sure about `ADDED`, because the RV we watch from is the one received from the creation operation. Does in include this initial `ADDED` event? I do not know.
I guess a following PR can try to add it, explaining why it is correct.

Regarding the `ctx.Done`, that is not required as the tooling is taking care of it. The whole point of using the `watch` tooling is to offload these mechanics to it.

2022-06-01 08:11 UTC, qinqon requested changes
a proposal, is not a must

2022-06-01 08:26 UTC, EdDev commented
change: Passed to `Until` a function instead of defining an anonymous one inline (per review request).

2022-06-01 10:59 UTC, RamLavi requested changes
I like this new tool! Added some comments.

2022-06-01 10:59 UTC, RamLavi commented on kiagnose/internal/checkup/checkup_test.go
> +		assert.ErrorContains(t, testCheckup.Run(), "initial RV \"\" is not supported")
is there no type of error like this? if possible it is better to use their errors, because it is not guaranteed that the wording will stay the same in future bumps, thus braking this test.

2022-06-01 15:36 UTC, EdDev commented
@RamLavi , I interpreted silence as ok to take it as is. If you think that point about the test merits a helper, please suggest it in a PR and I will take it.

2022-06-01 15:36 UTC, merged

2022-06-02 06:28 UTC, RamLavi commented on kiagnose/internal/checkup/checkup_test.go
> +			actualJob.ResourceVersion = ""
I will insist! but I'll put it i another PR :)

2022-06-02 06:29 UTC, RamLavi commented on kiagnose/internal/checkup/checkup_test.go
> +		assert.ErrorContains(t, testCheckup.Run(), "initial RV \"\" is not supported")
if you don't have  a predefined error, then I would let it go. odds are slim they they will change it...