vm-latency, e2e: Add bridge NetworkAttachmentDefinition
kiagnose/kiagnose pull request #103
Opened 2022-05-31 12:41 UTC by orelmisan

Currently, the NetworkAttachmentDefinition for a bridge network is created on-the-fly in the e2e.sh script.

Add bridge NetworkAttachmentDefinition manifest as a file, so users could also consume it as an example.

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-05-31 13:24 UTC, EdDev requested changes
The NetworkAttachmentDefinition is not part of the project, it is not even an example.
It is categorized as part of the tests.

I think this will make more sense to have this when we will create a test folder with the e2e in it.

2022-05-31 14:45 UTC, orelmisan commented
@EdDev we have an example for SR-IOV NetworkAttachmentDefinition at `checkups/kubevirt-vm-latency/manifests/sriov-network-attachment-definition.yaml`

2022-05-31 17:54 UTC, EdDev commented
> @EdDev we have an example for SR-IOV NetworkAttachmentDefinition at `checkups/kubevirt-vm-latency/manifests/sriov-network-attachment-definition.yaml`

It needs to be dropped.

2022-06-01 07:02 UTC, orelmisan commented
@EdDev, I've opened PR #106 to delete the SR-IOV NetworkAttachmentDefinition manifest.

2022-06-01 07:02 UTC, closed without merging