Kubevirt VM latency checkup: Use alpine image for VMs
kiagnose/kiagnose pull request #108
Opened 2022-06-06 08:55 UTC by ormergi

Initially `quay.io/kubevirt/alpine-with-test-tooling-container-disk` was used as the VMs image.
Alpine image is much lighter image then fedora, boot faster and require less resources.

Due to issues with QEMU guest-agent that caused the checkup to fail (due to VMs wont report readiness)
similar fedora image is used, which was addressed at .

Note about the tag: Since [[1]](https://github.com/kubevirt/kubevirtci/releases/tag/2205231118-f12b50e) changes did not landed at kubevirt/kubevirt yet (https://github.com/kubevirt/kubevirt/pull/7783 not merged yet), the `quay.io/kubevirt/alpine-with-test-tooling-container-disk` tag is being used.

Signed-off-by: Or Mergi <ormergi@redhat.com>

2022-06-06 08:56 UTC, ormergi commented
/cc @qinqon @EdDev

2022-06-06 10:09 UTC, ormergi commented
CI failed due to timeout when waiting for CNAO to become ready https://github.com/kiagnose/kiagnose/runs/6752723583?check_suite_focus=true

2022-06-06 13:20 UTC, qinqon approved these changes
I am happy the alpine container disk is helping people around.

2022-06-06 13:39 UTC, orelmisan reviewed
Thank you for the PR @ormergi!
Please see the inline comments.

2022-06-06 13:39 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +		fedoraContainerDiskImage                   = "quay.io/kubevirtci/alpine-with-test-tooling-container-disk:2205231118-f12b50e"
This function is called `NewFedora()`, please consider changing its name to something more agnostic.

2022-06-06 13:39 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +		fedoraContainerDiskImage                   = "quay.io/kubevirtci/alpine-with-test-tooling-container-disk:2205231118-f12b50e"
`fedoraContainerDiskImage`, and other "Fedora" (if exists) references should also change.

2022-06-08 08:15 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +		fedoraContainerDiskImage                   = "quay.io/kubevirtci/alpine-with-test-tooling-container-disk:2205231118-f12b50e"
Done.

2022-06-08 08:16 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +		fedoraContainerDiskImage                   = "quay.io/kubevirtci/alpine-with-test-tooling-container-disk:2205231118-f12b50e"
Thanks for the heads up, I renamed this variable name to be more generic.

2022-06-08 08:17 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/f0623b1f512328d46cb342fa624e7e39863ce7c3..1bbfe9d1edd250322538e00497e3dd6abcff9dfc): Remove fedora naming, also pin alpine image by using digest instead of tag.

2022-06-08 08:33 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/1bbfe9d1edd250322538e00497e3dd6abcff9dfc..30d71a5ecc8c3d9338936af28a38ad87ed571664): Update login to VMs logic to fit alpine image, also updated the commit message.

2022-06-19 14:23 UTC, ormergi commented
> @ormergi this reduce the startup time a little [kubevirt/kubevirtci#810](https://github.com/kubevirt/kubevirtci/pull/810)

@qinqon Do we need to wait for this PR to merge in order to use it?

2022-06-19 14:44 UTC, qinqon commented
> > @ormergi this reduce the startup time a little [kubevirt/kubevirtci#810](https://github.com/kubevirt/kubevirtci/pull/810)
> 
> 
> 
> @qinqon Do we need to wait for this PR to merge in order to use it?

nope, it activates ssh and increase size.

2022-06-19 15:32 UTC, ormergi commented
> nope, it activates ssh and increase size.

I meant for the image that should be created and pushed to `quay.io/kubevirtci`.

2022-06-19 15:57 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/pull/108/commits/0771379a19d82f533b93b656b6379bd473009b5a): Change ping-parser to support BusyBox `ping`.

2022-06-19 15:59 UTC, ormergi commented
Looks like using alpine image cut down 2 minutes from kubevirt-vm-latency checkup E2E check https://github.com/kiagnose/kiagnose/runs/6956053211?check_suite_focus=true

2022-06-19 16:54 UTC, ormergi commented
/cc @EdDev

2022-06-20 05:30 UTC, qinqon commented
> > nope, it activates ssh and increase size.
> 
> 
> 
> I meant for the image that should be created and pushed to `quay.io/kubevirtci`.

Its not merged yet, you can always do a follow up, updating the image.

2022-06-20 11:01 UTC, RamLavi requested changes
added some comments

2022-06-21 07:22 UTC, ormergi commented
> Its not merged yet, you can always do a follow up, updating the image.

I will :slightly_smiling_face:

2022-06-21 11:33 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +		// image digest tag 2205231118-f12b50e
Thanks for explaining, I will remove this comment.

2022-06-21 11:37 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/0771379a19d82f533b93b656b6379bd473009b5a..60e60dc17ffdad97b5deebb49502473abc68f32f): Remove alpine image tag name comment.

2022-06-21 12:45 UTC, RamLavi submitted a review, later dismissed
/lgtm

2022-06-21 12:46 UTC, orelmisan commented
@ormergi In the PRs description its not clear that the current image you want to replace is Fedora.

2022-06-21 13:07 UTC, ormergi commented
@orelmisan I updated the PR description.

2022-06-22 08:20 UTC, orelmisan reviewed
WDYT about this suggestion for the First commit message?
```suggestion
vmlatency: Use Alpine image

Use Alpine image for source and target VMs.
Update the login to VM console logic to fit the Alpine image.

The 'quay.io/kubevirtci/alpine-with-test-tooling-container-disk' image
is lighter, faster and require less resources in comparison to Fedora.
```

2022-06-22 08:28 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +		pingOutput = `
nit:
```suggestion
const pingOutput = `
```

2022-06-22 08:50 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/console/console.go
> +// LoginToAlpine performs a console login to an Alpine base VM
Done

2022-06-22 09:32 UTC, orelmisan approved these changes
Thank you!

2022-06-22 10:28 UTC, EdDev reviewed
> vmlatency, ping praser: Support BusyBox 'ping' 

Why do we need this if https://github.com/kubevirt/kubevirtci/pull/815 was merged?

2022-06-22 10:28 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +	const pingOutput = `
nit: Unrelated change in the 1st commit.

2022-06-22 10:28 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +func New(name string, opts ...Option) *kvcorev1.VirtualMachineInstance {
This reasoning does not fit with the existence of `LoginToAlpine`.

2022-06-22 10:34 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +	const pingOutput = `
I changed it here on porpuse for consistency after adding a similar test (on the second commit).

2022-06-22 10:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +	const pingOutput = `
You added it in the first commit instead of the second commit.

2022-06-22 10:46 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/d590f7433ced7f9e52b4e2281de14ba9146adfbd..071c59e0ed2a9216b429023268fa090e40006f85): address https://github.com/kiagnose/kiagnose/pull/108#pullrequestreview-1014920200

2022-06-22 10:46 UTC, EdDev approved these changes
Thank you!

2022-06-22 10:49 UTC, ormergi commented
> Why do we need this if [kubevirt/kubevirtci#815](https://github.com/kubevirt/kubevirtci/pull/815) was merged?

@EdDev there is a problem with the released image with those changes, it won't boot w/o user interaction.
It should be fixed by https://github.com/kubevirt/kubevirtci/pull/819 though.
Due to CI issues, things are slower than usual, I can do a follow PR to use the image with `iputils` and revert the parser changes, WDYT?

2022-06-22 10:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +func TestParseBusyBoxPingResults(t *testing.T) {
You added this test but left the other one still here. This is strange...

2022-06-22 11:00 UTC, merged