echo, README: Add usage instructions
kiagnose/kiagnose pull request #109
Opened 2022-06-06 10:57 UTC by orelmisan

Adds usage instructions:
Installation
Configuration
Execution
Results Retrieval
Removal

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-06-06 11:00 UTC, orelmisan commented
A follow-up PR is required in order to remove `checkups/echo/manifests/echo-checkup.yaml`, because it is used in the main e2e tests.

2022-06-06 11:08 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/bd15073835b36501a00f58b147709ae30f6232db..eb8aba030781292469c3e9baaa367c6313407360): Added results example.

2022-06-07 08:10 UTC, ormergi reviewed
The new structure looks good, please see my inline comments:

2022-06-07 08:10 UTC, ormergi commented on checkups/echo/README.md
> +
I think its better to guide the readers to wait for the `competionTimestamp` field at the checkup `ConfigMap` instead, we have an API for it lets use it :slightly_smiling_face:

2022-06-07 08:10 UTC, ormergi commented on checkups/echo/README.md
> +2. `status.failureReason: "MESSAGE environment variable is missing"`.
nit: Replacing the numbering with ` ```yaml``` ` block will make it look nicer.

2022-06-07 08:10 UTC, ormergi commented on checkups/echo/README.md
> +If a third party image registry was used - remove the checkup's image from the local registry.
Same, when working with k8s ecosystem these kind of things are pretty obvious, 
I think there is no need to mention it.

2022-06-07 08:10 UTC, ormergi commented on checkups/echo/README.md
> +The checkup does not require additional permissions.
I think there is no need to mention permissions for the echo checkup.

2022-06-07 08:10 UTC, ormergi commented on checkups/echo/README.md
> +## API
I think that with the new changes we can remove lines 112-132.

2022-06-07 08:16 UTC, orelmisan commented on checkups/echo/README.md
> +Kiagnose is [installed](../../README.install.md).
https://github.com/kiagnose/kiagnose#kiagnose-installation refers the reader to README.install.md.
I find it annoying to be redirected twice.

2022-06-07 08:21 UTC, orelmisan commented on checkups/echo/README.md
> +The checkup does not require additional permissions.
In the main README [installation steps](https://github.com/kiagnose/kiagnose#installation-steps), it says that you need to deploy the vendor-supplied permissions.
IMO it helps to explicitly say that this checkup does not require additional permissions.

2022-06-07 08:28 UTC, orelmisan commented on checkups/echo/README.md
> +2. `status.failureReason: "MESSAGE environment variable is missing"`.
It does look better.
Thanks.

2022-06-07 08:29 UTC, orelmisan commented on checkups/echo/README.md
> +
IMO this explanation should also be useful for beginner K8s users.

2022-06-07 08:29 UTC, orelmisan commented on checkups/echo/README.md
> +If a third party image registry was used - remove the checkup's image from the local registry.
As said in a previous comment, IMO this explanation should also be useful for beginner K8s users.

2022-06-07 08:31 UTC, orelmisan commented on checkups/echo/README.md
> +## API
This PR is about adding usage instructions to the echo checkup README.
I want to do one or more follow-up PRs to move / change other content in this file.

2022-06-07 08:32 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/054981fcc04283cfb8251da81fc25c7fa2c0f0c9..df919559c81a7cc174fbb93e7a773c830aaba28b): Answered review comments.

2022-06-07 08:34 UTC, orelmisan commented on checkups/echo/README.md
> +
BTW, I find this kind of explanation, very helpful when debugging with a tunnel vision - when you fail to see the obvious.

2022-06-07 08:41 UTC, ormergi commented on checkups/echo/README.md
> +Kiagnose is [installed](../../README.install.md).
Note that currently it directs to local file `Kiagnose is [installed](../../README.install.md)`, anything is better than that.

2022-06-07 08:43 UTC, ormergi commented on checkups/echo/README.md
> +
There is **a lot** to cover in this doc if you targets it to beginners.

2022-06-07 08:45 UTC, orelmisan commented on checkups/echo/README.md
> +Kiagnose is [installed](../../README.install.md).
Can you please elaborate why do you think a link to another file in the repo is a bad thing?

2022-06-08 10:56 UTC, ormergi commented on checkups/echo/README.md
> +Kiagnose is [installed](../../README.install.md).
> Can you please elaborate why do you think a link to another file in the repo is a bad thing?

What I had in mind is that the link wont work if it points to local file, would it?

> If a user has a copy of an older version, IMO it is expected to get the data for that version, and not the data regarding the latest version.

I agree, since we dont have tagged version yet I think we cannot do something like that at the moment.

2022-06-08 11:09 UTC, orelmisan commented on checkups/echo/README.md
> +Kiagnose is [installed](../../README.install.md).
> What I had in mind is that the link wont work if it points to local file, would it?

It works.
But on the PRs "Files changed" tab, it doesn't.

2022-06-09 11:42 UTC, RamLavi requested changes

2022-06-09 11:42 UTC, RamLavi commented on checkups/echo/README.md
> +Make sure your cluster can access `quay.io/kiagnose/echo-checkup` registry.
Please move this to pre-requisit

2022-06-09 11:42 UTC, RamLavi commented on checkups/echo/README.md
> +The checkup expects a `message` parameter, that could be configured to an arbitrary value.
please specify that you are now configuring the user-supplied cm

2022-06-09 11:42 UTC, RamLavi commented on checkups/echo/README.md
> +1. In order to execute the checkup:
```suggestion
In order to execute the checkup:
1. Apply the kiagnose job
```

2022-06-09 11:42 UTC, RamLavi commented on checkups/echo/README.md
> +After the Kiagnose Job had completed, retrieve the checkup results:
```suggestion
After the Kiagnose Job completed, retrieve the checkup results configmap :
```

2022-06-09 11:42 UTC, RamLavi commented on checkups/echo/README.md
>  1. "RESULT_CONFIGMAP_NAMESPACE" - namespace of the results ConfigMap object.
1,2 aren't these pre-set? this isn't something that the user needs to set, right? 
if so, then please mention this

2022-06-09 11:42 UTC, RamLavi commented on checkups/echo/README.md
> +In case the `message` parameter is not supplied, the following results are expected:
This is already mentioned [here](https://github.com/kiagnose/kiagnose/pull/109/files#diff-9305aeb8db4a4be1bc3007da984b54a311e569835322d0e3b09cf1bc5878a722R128)
I think your position to put it is better, but please delete if from the other.

2022-06-09 12:10 UTC, orelmisan commented on checkups/echo/README.md
> +In case the `message` parameter is not supplied, the following results are expected:
I intend to make a follow-up PR to touch all the content bellow the `API` heading.
This PR's goal is to add the usage instructions.

2022-06-09 12:10 UTC, orelmisan commented on checkups/echo/README.md
>  1. "RESULT_CONFIGMAP_NAMESPACE" - namespace of the results ConfigMap object.
I intend to make a follow-up PR to touch all the content bellow the `API` heading.
This PR's goal is to add the usage instructions.

2022-06-09 12:11 UTC, orelmisan commented on checkups/echo/README.md
> +After the Kiagnose Job had completed, retrieve the checkup results:
Changed to something similar.

2022-06-09 12:11 UTC, orelmisan commented on checkups/echo/README.md
> +1. In order to execute the checkup:
Done.

2022-06-09 12:11 UTC, orelmisan commented on checkups/echo/README.md
> +The checkup expects a `message` parameter, that could be configured to an arbitrary value.
Done.

2022-06-09 12:11 UTC, orelmisan commented on checkups/echo/README.md
> +Make sure your cluster can access `quay.io/kiagnose/echo-checkup` registry.
Done.

2022-06-09 12:56 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/df919559c81a7cc174fbb93e7a773c830aaba28b..74812f73bb619e7a6afdd8e6939f7109d8106382): Answered review comments.

2022-06-09 13:22 UTC, RamLavi commented on checkups/echo/README.md
> +In case the `message` parameter is not supplied, the following results are expected:
I see no reason why not do it now, but won't insist

2022-06-09 13:23 UTC, RamLavi submitted a review, later dismissed
/lgtm

2022-06-13 09:27 UTC, EdDev requested changes

2022-06-13 09:27 UTC, EdDev commented on checkups/echo/README.md
> +```
Missing `EOF` at the end.

2022-06-13 09:27 UTC, EdDev commented on checkups/echo/README.md
> +2. Wait for the Kiagnose Job to finish.
How?

2022-06-13 09:27 UTC, EdDev commented on checkups/echo/README.md
> +```
Isn't this suppose to appear in the `Removal` section below?

2022-06-13 09:27 UTC, EdDev commented on checkups/echo/README.md
> +If a third party image registry was used - remove the checkup's image from the local registry.
A beginner k8s user does not know how to do this at all.
If you want to explain how to do it, or ref how to do it here (i.e. support it explicitly), you need to give all the info.

I do not think we care about this part at all. If someone uses some other registry, he is expected to know what to do.

2022-06-13 09:43 UTC, orelmisan commented on checkups/echo/README.md
> +```
Here a user removes the results of the last run.
The checkup's configuration and resutls are stored in the ConfigMap deleted on line 110 (show in this snippet).
Kiagnose logs are removed when deleting the Job objects.

I'll remove the `Removal` heading.

2022-06-13 09:55 UTC, orelmisan commented on checkups/echo/README.md
> +```
Done. Thanks for catching that!

2022-06-13 09:55 UTC, orelmisan commented on checkups/echo/README.md
> +2. Wait for the Kiagnose Job to finish.
Added a command to catch a successful run with timeout.

2022-06-13 09:59 UTC, orelmisan commented on checkups/echo/README.md
> +
Re-added this command.

2022-06-13 10:01 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/74812f73bb619e7a6afdd8e6939f7109d8106382..a3511c505f9ed71b6f477cc7ba2068e03cce35b9): Rebase
Answered review comments.

2022-06-13 11:02 UTC, merged