vmlatency, parser, test: Apply test-case pattern
kiagnose/kiagnose pull request #114
Opened 2022-06-08 07:55 UTC by ormergi

Follow "test-case" pattern similar to other test suites in the code base in order to make it easier to add new tests.

Signed-off-by: Or Mergi <ormergi@redhat.com>

2022-06-08 07:55 UTC, ormergi commented
/cc @RamLavi @orelmisan

2022-06-08 14:53 UTC, orelmisan reviewed
Thank you for the PR @ormergi!
Please see the inline comments.

2022-06-08 14:53 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +type pingParserTestCase struct {
`pingParserTestCase` could be moved into `TestParsePingResults()` in order to decrease its scope.

2022-06-08 14:53 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +		})
If there is only one test-case, IMO we can drop the table (pingParserTestCase + for loop).

2022-06-08 14:53 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +const pingOutput = `
`pingOutput` could be moved to `TestParsePingResults()` in order to decrease its scope.

2022-06-08 14:53 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +var pingResults = latency.Results{
`pingResults` could be moved to `TestParsePingResults()` in order to decrease its scope.

2022-06-08 14:55 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +const pingOutput = `
`pingOutput` could be moved to `TestParsePingResults()` in order to decrease its scope.

2022-06-08 14:55 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +var pingResults = latency.Results{
`pingResults` could be moved to `TestParsePingResults()` in order to decrease its scope.

2022-06-19 13:48 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +		})
I added the table as preparation step for follow up PR that adds more tests to it.

2022-06-19 13:49 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +const pingOutput = `
It left out of the function to not bloat it when other cases are added.

2022-06-19 13:49 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +var pingResults = latency.Results{
Same here, I left it out of the function to not bloat it when other cases are added.

2022-06-19 13:54 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/7343f30952dce79dc454115077fa5903f4b5870b..ca845f28cfd8fa99ae83baf49f1a7c1e16f79864): Add more tests.

2022-06-19 16:35 UTC, ormergi commented
/cc @EdDev

2022-06-20 11:28 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
> +rtt min/avg/max/mdev = 1.732/2.074/2.382/0.214 ms
is this a thing?

2022-06-20 11:31 UTC, RamLavi approved these changes
L2xndG0=

2022-06-21 09:35 UTC, EdDev requested changes
> vmlatency, ping-parser: Improve test coverage 

Please add more information about what scenarios you tests and what these represent.
I for example am not clear why you check duplication or why partial info is ok.

2022-10-30 13:01 UTC, EdDev commented
@ormergi , is this change relevant?

2022-10-30 13:58 UTC, ormergi commented
> @ormergi , is this change relevant?

Nope, I am closing it.

2022-10-30 13:59 UTC, closed without merging