dpdk, Introduce design doc, Summary and Motivation
kiagnose/kiagnose pull request #125
Opened 2022-07-04 12:10 UTC by RamLavi

This PR introduces a skeleton design doc of the dpdk checkup.
Also, it adds the Summary and Motivation sections.

2022-07-04 14:06 UTC, ormergi approved these changes
I commented about the small nit, other than that looks good to me.

2022-07-10 12:47 UTC, orelmisan reviewed
Thank you for the PR @RamLavi!
Please see the inline comments.

2022-07-10 12:47 UTC, orelmisan commented on docs/dpdk_checkup_design.md
> +Provide a functionality to validate DPDK communication going through a virtual machine that runs on a [Kubernetes](https://kubernetes.io/) cluster with [KubeVirt](https://kubevirt.io/).
```suggestion
Provide a functionality to validate [DPDK](https://www.dpdk.org/) communication going through a virtual machine that runs on a [Kubernetes](https://kubernetes.io/) cluster with [KubeVirt](https://kubevirt.io/).
```

2022-07-10 12:47 UTC, orelmisan commented on docs/dpdk_checkup_design.md
> +Configuring DPDK inside a cluster is a multi-step configuration task. A cluster administrator can benefit from a check that can help verify that the overall configuration is optimized for DPDK applic
```suggestion
Configuring DPDK inside a cluster is a multi-step configuration task. A cluster administrator can benefit from a checkup that can help verify that the overall configuration supports execution of a DPDK application.
```

2022-07-10 12:47 UTC, orelmisan commented on docs/dpdk_checkup_design.md
> +Provide a functionality to validate dpdk communication going through a virtual machine that runs on a [Kubernetes](https://kubernetes.io/) cluster with [KubeVirt](https://kubevirt.io/)
There is one more instance of "dpdk" in the PR description:
```
This PR introduces a skeleton design doc of the dpdk checkup.
```

2022-07-11 06:07 UTC, RamLavi commented on docs/dpdk_checkup_design.md
> +Provide a functionality to validate DPDK communication going through a virtual machine that runs on a [Kubernetes](https://kubernetes.io/) cluster with [KubeVirt](https://kubevirt.io/).
Done

2022-07-11 06:09 UTC, RamLavi commented on docs/dpdk_checkup_design.md
> +Configuring DPDK inside a cluster is a multi-step configuration task. A cluster administrator can benefit from a check that can help verify that the overall configuration is optimized for DPDK applic
Like! Done

2022-07-11 06:11 UTC, RamLavi commented
@orelmisan fixes [here](https://github.com/kiagnose/kiagnose/compare/5c557a7f19f4b0b67e362c293d87cfcb59c6e8e3..988910d06c3e0f6ad94b9a2fef69297dee0e3b1b)

2022-07-11 06:24 UTC, orelmisan approved these changes
Thank you!

2022-07-12 12:05 UTC, EdDev requested changes

2022-07-12 12:17 UTC, EdDev commented on docs/dpdk_checkup_design.md
> +* Report results (and logs) with the cluster administrator.
I am not sure this can be classified as a goal.
We need result reports because we want to _help detect and troubleshoot cluster issues related to high performance VM/s_.

2022-07-12 12:28 UTC, EdDev commented on docs/dpdk_checkup_design.md
> +* Kubernetes Cluster Administrators
What about K8s namespace administrators?

2022-07-12 12:39 UTC, EdDev commented on docs/dpdk_checkup_design.md
> +2. Optionally provide the maximum accepted latency, such that beyond this value, the check will fail.
- Validate that given a namespace in a cluster, with secondary high throughput network, the high performance VM/s can run successfully.
- Validate that there is connectivity between two high performance VM/s on the secondary network.
- Measure the communication latency between the two VM/s, 
- Report the success or failure of the validations, including measured latencies and reasons of failure.

2022-07-19 12:14 UTC, orelmisan commented
@RamLavi Can you please move the file under `docs/design-proposals`?

2022-09-19 08:07 UTC, RamLavi commented
closing this PR for now. it has lost priority

2022-09-19 08:07 UTC, closed without merging