docs: Add design proposal to exec checkups in existing ns
kiagnose/kiagnose pull request #126
Opened 2022-07-19 11:56 UTC by orelmisan

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-07-20 09:52 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/fc3d127b10091004635750cad10b8247cb7d88be..d2bb236c4db31c2879c872f5c9d2af3aa3925e5b): Added implementation step.

2022-07-27 10:06 UTC, RamLavi requested changes

2022-07-27 10:06 UTC, RamLavi commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +The suggested solution is to create user-supplied [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) objects in the namespace in which the checkup shall be executed.
I think we should break it to 2 sentences, to make it clearer.
Suggestion:
```suggestion
The suggested solution is for the user to create user-supplied [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) objects in a pre-existing namespace. The checkup will then be executed on that namespace.
```

2022-07-27 10:06 UTC, RamLavi commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +A checkup shall be required to mark all objects created by it, in order to help users recognize leftover objects.
can we force this in any way?

2022-07-27 10:22 UTC, orelmisan commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +The suggested solution is to create user-supplied [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) objects in the namespace in which the checkup shall be executed.
Done.

2022-07-27 10:26 UTC, orelmisan commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +A checkup shall be required to mark all objects created by it, in order to help users recognize leftover objects.
I'm not sure.
We'll need to investigate it.

2022-07-27 10:26 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/d2bb236c4db31c2879c872f5c9d2af3aa3925e5b..a897a0d960fb6151662f866c7a0873036c8e479a): Answered a [comment](https://github.com/kiagnose/kiagnose/pull/126#discussion_r930868926).

2022-07-27 18:16 UTC, EdDev approved these changes
Thank you!

I find the implementation steps a bit hard to understand, but I think the state of this proposal is very good as is.

2022-07-27 18:16 UTC, EdDev commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +A checkup shall be required to mark all objects created by it, in order to help users recognize leftover objects.
The only way I can think of making sure it does it, is to certify checkups in namespaces we know exactly what exists and therefore can scan/track the created objects in it.

At the moment, I think this is not in our scope.

2022-07-28 08:30 UTC, RamLavi submitted a review, later dismissed
/lgtm

2022-08-01 09:08 UTC, ormergi reviewed
Hi Orel thanks for posting the design, please see my inline comments.

2022-08-01 09:12 UTC, orelmisan commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +- I need to manually verify that the checkup had cleaned after itself.
That's right.
A checkup will have the permissions to interact / create objects in the target namespace.

2022-08-01 09:16 UTC, orelmisan commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +## Additional Required Permissions
> I suggest changing this section in a way it will also describe the permission Kiagnose will no longer need.

Because the ephemeral namespace feature stays, we cannot remove permissions (yet).

> Also, I think it's worth mentioning that the permissions to the ConfigMap and ServiceAccount can be granted to change concrete objects (and not any object of these types).

Kiagnose has to be able to delete any `ConfigMap` or `ServiceAccount` in order to perform its teardown correctly.

2022-08-01 09:19 UTC, orelmisan commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +4. Kiagnose shall not delete a non-ephemeral namespace.
It is a requirement for Kiagnose to not delete a non-ephemeral namespace.
There are two places where a namespace is deleted:
1. If an error had occurred during the setup stage (after namespace creation).
2. During the teardown stage.

2022-08-07 11:15 UTC, ormergi commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +4. Kiagnose shall not delete a non-ephemeral namespace.
Right, but the way it is now with the numbering makes me think it's one of the steps of the new logic.

2022-08-07 11:22 UTC, ormergi commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +- I need to manually verify that the checkup had cleaned after itself.
It doesn't make sense to me that Kiagnose needs to clean after the checkup (delete objects the checkup created).
Given that at any point in time, the checkup could create a new object (e.g: pod) the target namespace, 
how is it going to be enforced?

2022-08-07 11:22 UTC, ormergi commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +Kiagnose should be given “delete” permissions of the following objects:
nit: given -> granted with.

2022-08-07 11:26 UTC, orelmisan commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +- I need to manually verify that the checkup had cleaned after itself.
There is no sentence saying that Kiagnose shall clean after the checkup.

2022-08-07 11:28 UTC, orelmisan commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +Kiagnose should be given “delete” permissions of the following objects:
Done.

2022-08-07 11:28 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/a897a0d960fb6151662f866c7a0873036c8e479a..f5328b0ea403975e3557cc4e008147001a48f725): Rebase
Fixed a small [nit](https://github.com/kiagnose/kiagnose/pull/126#discussion_r939650754).

2022-08-07 12:40 UTC, ormergi commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +- I need to manually verify that the checkup had cleaned after itself.
Sorry for the noise I got it wrong.

2022-08-08 05:29 UTC, RamLavi approved these changes
/lgtm

2022-08-08 06:34 UTC, EdDev approved these changes
Thank you.

2022-08-08 06:34 UTC, EdDev commented on docs/design-proposals/execute_checkup_in_existing_ns.md
> +4. Kiagnose shall not delete a non-ephemeral namespace.
It is a nit, I do not think it is worth blocking on this.

2022-08-08 10:48 UTC, ormergi approved these changes
LGTM

2022-08-08 11:17 UTC, merged