checkup: Name results CM after user-supplied CM
kiagnose/kiagnose pull request #127
Opened 2022-07-20 07:13 UTC by orelmisan

Currently, the results ConfigMap object's name is constant.
As a preliminary step to checkup execution in a target namespace,
name the results ConfigMap with the following format:
`<user-supplied-CM-name>-results`

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-07-27 18:30 UTC, EdDev requested changes
Looks nice. I only had some small comments.

Why is it a draft?

2022-07-27 18:30 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +	checkupName := testCheckupName
Why do you need a variable?

2022-07-27 18:30 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +		checkupName := testCheckupName
same question, why a variable?

2022-07-28 08:05 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +	checkupName := testCheckupName
Its not really needed.
We can use the constant name directly.

2022-07-28 08:05 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +		checkupName := testCheckupName
Its not really needed.
We can use the constant name directly.

2022-07-28 08:07 UTC, orelmisan commented
[Change 1](https://github.com/kiagnose/kiagnose/compare/284c26c85da0082a0a80563bf1d8d2a4ed83c70f..3d3208825278f76d6f31aa784359d4c1c4539ec1): Rebase.
[Change 2](https://github.com/kiagnose/kiagnose/compare/3d3208825278f76d6f31aa784359d4c1c4539ec1..b59286f6c670368d4464f2efdd521eb5a34239a3): Answered comments [1](https://github.com/kiagnose/kiagnose/pull/127#discussion_r931421845) and [2](https://github.com/kiagnose/kiagnose/pull/127#discussion_r931431217).

2022-07-28 08:09 UTC, orelmisan commented
> Why is it a draft?

I wanted to merge it after other PRs in order to make the rebase easier.
It doesn't matter that much.

2022-07-28 08:12 UTC, EdDev approved these changes

2022-07-28 08:16 UTC, merged