checkup, tests: Split TestCheckupTeardownShould()
kiagnose/kiagnose pull request #140
Opened 2022-08-01 08:20 UTC by orelmisan

Currently, `TestCheckupTeardownShould()` has several subtests.
It is long and difficult to change.

Split each subtest of `TestCheckupTeardownShould()` to a new test.

2022-08-01 08:39 UTC, RamLavi requested changes
looks like the commits have the same title..
could you change it so to something more informative?

2022-08-01 08:44 UTC, orelmisan commented
> looks like the commits have the same title.. could you change it so to something more informative?

Thank you for the review @RamLavi.
The scenarios' names are quite long and don't fit nicely in the subject line.
Do you have any suggestions?

2022-08-01 08:51 UTC, RamLavi commented
> > looks like the commits have the same title.. could you change it so to something more informative?
> 
> Thank you for the review @RamLavi. The scenarios' names are quite long and don't fit nicely in the subject line. Do you have any suggestions?

As this change is just moving around code to function with no added logic, I would squash them.

2022-08-01 08:55 UTC, orelmisan commented
> > > looks like the commits have the same title.. could you change it so to something more informative?
> > 
> > 
> > Thank you for the review @RamLavi. The scenarios' names are quite long and don't fit nicely in the subject line. Do you have any suggestions?
> 
> As this change is just moving around code to function with no added logic, I would squash them.

IMO if this PR had only one commit, it would be harder for a reviewer to verify that code had just moved without changing.

2022-08-01 09:00 UTC, RamLavi commented
> > > > looks like the commits have the same title.. could you change it so to something more informative?
> > > 
> > > 
> > > Thank you for the review @RamLavi. The scenarios' names are quite long and don't fit nicely in the subject line. Do you have any suggestions?
> > 
> > 
> > As this change is just moving around code to function with no added logic, I would squash them.
> 
> IMO if this PR had only one commit, it would be harder for a reviewer to verify that code had just moved without changing.

The two better options I see are either squash or keep it split with unique commit titles.. both are good by me
I would avoid keeping the commit title the same, as it's not informative. 
But I would not insist.

2022-08-01 09:06 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/3d0b24756fa865cae2b76a4f24ef3790db4e20dc..758a6cbe9b2bfbb8596b14b62cb742f96f1e4feb): Commits subjects.

2022-08-01 09:07 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/758a6cbe9b2bfbb8596b14b62cb742f96f1e4feb..6168c895a70d48faf4111dd1fda7e72f73e81eac): Commits subjects.

2022-08-01 09:10 UTC, RamLavi approved these changes
Thanks for considering my input :) 
/lgtm

2022-08-01 09:42 UTC, ormergi submitted a review, later dismissed

2022-08-01 09:46 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func TestTeardownShouldFailWhenDeleteClusterRoleBindingsFails(t *testing.T) {
You can do this and keep a nice structure and still have it flatten in terms of nesting:

```
func TestCheckupTeardownShould(t *testing.T) {
    testTeardownShouldFailWhenDeleteClusterRoleBindingsFails(t)
    testTeardownShouldFailWhenDeleteClusterRoleBindingsTimeoutExpires(t)
    ...
}
```

2022-08-01 11:09 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +func TestTeardownShouldFailWhenDeleteClusterRoleBindingsFails(t *testing.T) {
Thanks.
Done.

2022-08-01 11:20 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +	const expectedErr = "failed to delete ClusterRoleBinding"
@ormergi I think we have a bug in this line.
I think it should be:
```suggestion
	const expectedErr = "failed to delete Namespace"
```

2022-08-01 14:12 UTC, EdDev approved these changes

2022-08-02 08:34 UTC, RamLavi approved these changes
/lgtm

2022-08-02 09:58 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +	const expectedErr = "failed to delete ClusterRoleBinding"
At line 280 we configure the tests client with the error it will return on namespace delete,
Line 282 calls Teardown() which sends a delete namespace using that client.
Note that there is no actual bug, the error content doesn't have meaning in this test it could be set to "foo".
But yes the current message is wrong.

2022-08-02 10:07 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +	const expectedErr = "failed to delete ClusterRoleBinding"
Would you mind to send a PR to fix it?

2022-08-02 11:55 UTC, merged