checkup: Introduce target Namespace
kiagnose/kiagnose pull request #142
Opened 2022-08-01 12:34 UTC by orelmisan

Currently, checkups are executed in ephemeral Namespace objects.

This change enables checkup execution in a target Namespace - the Namespace in which the user-supplied ConfigMap object is at.

Create and delete an ephemeral namespace only if the user-supplied ConfigMap object is at the "kiagnose" namespace.
Else, setup all objects in the target Namespace.

Signed-off-by: Orel Misan <omisan@redhat.com>

This PR depends on PR #140.

2022-08-07 12:55 UTC, EdDev requested changes
Review of the 1st commit.

2022-08-07 12:55 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +}
I am not clear why we need this.

2022-08-07 12:55 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +	assertNamespaceExists(t, testClient.Clientset, testTargetNs)
I do not think you need to validate that the `Create` succeeds beyond asserting its returned error.

2022-08-07 12:55 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +	assertNamespaceDoesntExists(t, testClient.Clientset, expectedEphemeralNamespaceName)
How is the ephemeral namespace relevant here? I was under the impression this test checks the explicit target-ns.

2022-08-07 13:02 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +		namespace:           ephemeralNamespace,
Agreed.

2022-08-07 13:04 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	if c.namespace != nil {
Thank you for the suggestion.
For now I rather keep thinks simpler, but we can do it in a follow-up PR if you think it has benefits.

2022-08-07 13:05 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +}
So Kiagnose will not delete the target namespace.
In the next commits it holds the teardown logic, which is different from the current teardown logic.

2022-08-07 13:06 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +	assertNamespaceExists(t, testClient.Clientset, testTargetNs)
Ok.

2022-08-07 13:06 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +	assertNamespaceDoesntExists(t, testClient.Clientset, expectedEphemeralNamespaceName)
I wanted to check that the ephemeral namespace is not created by mistake.

2022-08-08 06:21 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +		namespace:           ephemeralNamespace,
Done.

2022-08-08 06:21 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +	assertNamespaceExists(t, testClient.Clientset, testTargetNs)
Done.

2022-08-08 06:23 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/3373c7eb0a35752234bc9cd51e928550d63aaa6f..afddb3640770147736b8c8afa41509babd825902): Renamed `Checkup.namespace` to `Checkup.ephemeralNamespace`.
Removed two assertions that a namespace exists after its creation in unit tests.

2022-08-08 11:53 UTC, orelmisan commented
Rebase.

2022-08-08 12:02 UTC, RamLavi requested changes
added some comments,
But more importantly, did we explore the option to use OwnerReference?

2022-08-08 12:22 UTC, orelmisan commented
> added some comments, But more importantly, did we explore the option to use OwnerReference?

Most of this PR is handling the tear down process when a checkup executes in a target namespace.
As the commit progress, it can be seen that a certain order of tear down should be in place (in order to strip the privileges from the checkup):
1. Delete the checkup Job and its underlying Pod.
2. Delete the ClusterRoleBindings.
3. Delete the RoleBinding to the ConfigMapWriter Role.
4. Delete the ServiceAccount.
5. Delete the ConfigMapWriter Role.

AFAIU, when using OwnerReference we don't have control over the order in which objects are deleted.

2022-08-08 12:24 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	if err := configmap.Delete(c.client, c.resultConfigMap.Namespace, c.resultConfigMap.Name); err != nil {
Prior to reaching this place in the code, the results were fetched, the Job was deleted and all of the RBAC related objects were removed.

2022-08-09 13:16 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +}
I just saw it is used in the next commit to add more content to it.

2022-08-09 13:41 UTC, orelmisan commented
Added documentation regarding the feature in the main README file, and in the checkups' README files.

2022-08-09 13:45 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +	deletePolicy := metav1.DeletePropagationForeground
I must admit, I am not sure if this is considered safe (or safer from the default background option).
In any case, I would suggest to say a few words about this in the commit, explaining your reasoning you choose it.

2022-08-09 13:58 UTC, EdDev reviewed
Looks very nice!

2022-08-10 05:43 UTC, orelmisan commented
> > vm latency checkup, e2e: Run checkup in a target namespace
> 
> IIUC this means that we no longer check the ephemeral NS usage, right? If this is the case, please mention it in the commit message.

Done.

2022-08-10 05:43 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	const errPrefix = "teardown"
Done.

2022-08-10 05:43 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	if err := configmap.Delete(c.client, c.resultConfigMap.Namespace, c.resultConfigMap.Name); err != nil {
Done.

2022-08-10 05:44 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +		errs = append(errs, err)
Moved the usage of `var errs []error` to the first commit that needs more than one error.

2022-08-10 05:45 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +}
Moved it to the first commit which is doing a teardown action.

2022-08-10 05:45 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	if c.ephemeralNamespace != nil {
Done.

2022-08-10 05:52 UTC, orelmisan commented on kiagnose/internal/checkup/job/job.go
> +	deletePolicy := metav1.DeletePropagationForeground
Added reasoning to the commit message.
Can you please elaborate why do you think it is not considered safe?

2022-08-10 05:53 UTC, orelmisan commented
Changes [1](https://github.com/kiagnose/kiagnose/compare/7bec0bd191fc1a3407da46314b787ed8ac33a946..f84b9d171cd87ca24738467ceb4bb60d0812aa06) and [2](https://github.com/kiagnose/kiagnose/compare/f84b9d171cd87ca24738467ceb4bb60d0812aa06..69447cf693152844c5b05462725c4423d7492a31): Answered review comments by @RamLavi and @EdDev.

2022-08-10 06:50 UTC, RamLavi commented
> > added some comments, But more importantly, did we explore the option to use OwnerReference?
> 
> Most of this PR is handling the tear down process when a checkup executes in a target namespace. As the commit progress, it can be seen that a certain order of tear down should be in place (in order to strip the privileges from the checkup):
> 
> 1. Delete the checkup Job and its underlying Pod.
> 2. Delete the ClusterRoleBindings.
> 3. Delete the RoleBinding to the ConfigMapWriter Role.
> 4. Delete the ServiceAccount.
> 5. Delete the ConfigMapWriter Role.
> 6. Delete the results ConfigMap.
> 
> AFAIU, when using OwnerReference we don't have control over the order in which objects are deleted.

I would try nonetheless just to see, it would make the teardown responsibilities out of our hands. 
Even if it does needs ordering, perhaps if we ever let go of the RBAC roles responsibilities then we won't need to worry about that.

2022-08-10 08:01 UTC, RamLavi commented
> I would try nonetheless just to see, it would make the teardown responsibilities out of our hands.

we talked about it offline, I understand why we can't use it now. 
I would reconsider doing it once/if we ever renounce our rback responsibilities.

2022-08-10 08:01 UTC, RamLavi approved these changes
/lgtm

2022-08-11 10:46 UTC, EdDev approved these changes
Thank you!

2022-08-11 10:46 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +	deletePolicy := metav1.DeletePropagationForeground
It may be unsafe because it requires the dependent objects to be deleted first, which may actually fail and therefore stuck this operation, or even cause it to fail.

If something else blocks the deletion of the dependent, it is a deadlock.

Said all that, I am not sure what is the best approach in general. It may be good enough here.
The explanation you added to the commit seems convincing.
For the long run, some thought about how to delete things and the risks of each approach may need exploration.

2022-08-11 10:46 UTC, merged