docs: Add a proposal to reduce Kiagnose's permissions
kiagnose/kiagnose pull request #147
Opened 2022-08-11 18:56 UTC by orelmisan

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-08-11 19:08 UTC, orelmisan commented
@phoracek

2022-08-16 06:51 UTC, RamLavi requested changes
Looks good! added some comments

2022-08-16 06:51 UTC, RamLavi commented on docs/design-proposals/permissions_reduction_proposal.md
> +1. To use a user-supplied pre-configured ServiceAccount, to execute a checkup with.
```suggestion
1. To use a user-supplied pre-configured ServiceAccount, with which the checkup will be executed.
```

2022-08-16 06:51 UTC, RamLavi commented on docs/design-proposals/permissions_reduction_proposal.md
> +2. Remove the ability to execute checkups in an ephemeral namespaces.
```suggestion
2. Remove the ability to execute checkups inside ephemeral namespaces.
```

2022-08-16 06:51 UTC, RamLavi commented on docs/design-proposals/permissions_reduction_proposal.md
> +Kiagnose deployment shall include the following objects:
not sure I understand, AFAIR deployment object does not have these fields

2022-08-16 06:51 UTC, RamLavi commented on docs/design-proposals/permissions_reduction_proposal.md
> +A checkup deployment shall include the following objects:
ditto

2022-08-16 06:51 UTC, RamLavi commented on docs/design-proposals/permissions_reduction_proposal.md
> +The Kiagnose Job shall delete all objects it created during its execution:
what about ownerRefenrence? isn't that doable now?

2022-08-16 06:51 UTC, RamLavi commented on docs/design-proposals/permissions_reduction_proposal.md
> +## Implementation Steps
I am missing the mechanism to prevent us from hijacking namespaces, we should run checkups only on namespaces that have a "kiagnose-enabled" label

2022-08-16 07:52 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +Kiagnose deployment shall include the following objects:
```suggestion
Kiagnose deployment manifest shall include the following objects:
```
The meaning was to [this](https://github.com/kiagnose/kiagnose/blob/main/manifests/kiagnose.yaml) file, and not to K8s Deployment object.

2022-08-16 09:23 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +## Implementation Steps
It is contained in PR #126 as an optional feature.
I'm in favor of implementing it, but I don't think it belongs in this document.

2022-08-16 09:25 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +The Kiagnose Job shall delete all objects it created during its execution:
We still need to create and remove a Role (and RoleBinding) to enable the checkup to update its results ConfigMap.
So this option is still not applicable.

2022-08-16 09:26 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +A checkup deployment shall include the following objects:
Same answer as in the [previous comment](https://github.com/kiagnose/kiagnose/pull/147#discussion_r946448147).

2022-08-16 09:27 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +1. To use a user-supplied pre-configured ServiceAccount, to execute a checkup with.
Done.

2022-08-16 09:27 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +2. Remove the ability to execute checkups in an ephemeral namespaces.
Done.

2022-08-16 09:28 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +Kiagnose deployment shall include the following objects:
Fixed the wording.

2022-08-16 09:28 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +A checkup deployment shall include the following objects:
Fixed the wording.

2022-08-16 09:29 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/fcf3a55548a2c20b0f80d3e09bf78a96fc748e41..2bb28fa487c16773e1e3fadf32d1dfe37c764ba1): Answered @RamLavi's comments.
Added a limitation to the `spec.serviceAccountName` input field.

2022-08-17 06:11 UTC, RamLavi commented on docs/design-proposals/permissions_reduction_proposal.md
> +| spec.serviceAccountName | Existing serviceAccount for the checkup’s Job                            | True         | `default` ServiceAccount name is not allowed |
why is default not allowed?

2022-08-17 06:17 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +| spec.serviceAccountName | Existing serviceAccount for the checkup’s Job                            | True         | `default` ServiceAccount name is not allowed |
Kiagnose has to give the input ServiceAccount another permission - the ability to update the results ConfigMap.
If we'll allow the `default` ServiceAccount as an input, every Pod that will be created in that namespace (without a ServiceAccount or with the default) will have that extra permission.

2022-08-17 07:18 UTC, RamLavi commented on docs/design-proposals/permissions_reduction_proposal.md
> +| spec.serviceAccountName | Existing serviceAccount for the checkup’s Job                            | True         | `default` ServiceAccount name is not allowed |
So Kiagnose is mutating the input ServiceAccount? isn't that a bit intrusive?

2022-08-17 07:22 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +| spec.serviceAccountName | Existing serviceAccount for the checkup’s Job                            | True         | `default` ServiceAccount name is not allowed |
This input ServiceAccount is supposed to be dedicated to a specific checkup.
Kiagnose will not mutate the ServiceAccount, it will bind one Role to it, and remove the binding at the teardown stage.

2022-08-17 07:57 UTC, RamLavi commented on docs/design-proposals/permissions_reduction_proposal.md
> +| spec.serviceAccountName | Existing serviceAccount for the checkup’s Job                            | True         | `default` ServiceAccount name is not allowed |
I think it's better than I originally thought, but just to understand, why aren't we giving this responsibility to the ServiceAccount creator (i.e. the sysAdmin)?

2022-08-17 08:08 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +| spec.serviceAccountName | Existing serviceAccount for the checkup’s Job                            | True         | `default` ServiceAccount name is not allowed |
Currently checkups write their results to the results ConfigMap which is created by Kiagnose.
Checkups are provided with the namespace and name of this results ConfigMap as an input (using env vars).
In order for the checkups to be able to write to this ConfigMap, Kiagnose creates a Role with write access to a single results ConfigMap (by name).

If the user will be responsible for creating a results ConfigMap and the accompanying Role and RoleBinding, IMO it will:
1. Affect two consecutive (or parallel) runs of the checkup - the results ConfigMap will contain data from a previous run.
2. Add more manual labor on the user.

I think Kiagnose should automate every action that is not privileged and requires a human decision.

2022-08-17 15:44 UTC, ormergi reviewed
Thank you for this proposal, overall looks good.

There are a bunch of comments that are related to the doc formatting, it seems to be different than other docs we already have (e.g: details of the new solution are at Overview section), 
Is it on purpose?

Also, as a reader I find it confusing the way the doc is structured where there is a sub-title before describing a part of a flow.
It would be easier to understand if there were less sub-titles that district the follow of the thing you want to describe where it make sense.
For example Overview section, Checkup Execution sub-title.

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +# Summary
Please consider moving the details to the Motivation/Overview section, in a way the reader could understand the problem and the proposed solution in a few sentences, I added a few suggestions.

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +3. Remove the ephemeral namespace feature.
I am not sure it's a goal, it's a requirement in order to implement (1) and (2).

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +3. Remove the majority of the RBAC-related permissions Kiagnose has.
```suggestion
The proposed solution is to reduce the permissions required for Kiagnose to operate by moving the responsibility of creating the checkup ServiceAccount and its permissions to the user.
```

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +# Overview
I am a little bit confused, it seems that this section describes the proposed solution instead of providing background about the current state and operation flow.
I think the details about the proposal should go to Proposal section (maybe after User Stories).

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +3. Checkup Job connected to the pre-deployed checkup’s ServiceAccount object.
```suggestion
The Kiagnose Job shall be created in the `kiagnose` namespace and create the following objects in the target namespace:

1. Results ConfigMap.
2. Role and RoleBinding to the user-supplied `ServiceAccount` so the checkup could write its results to the
   results `ConfigMap`.
3. Checkup Job associated with user-provided ServiceAccount.
```

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +
```suggestion
Kiagnose shall be deployed to an existing Namespace, including:
- ServiceAccount
- ClusterRole
- ClusterRoleBinding
```

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +
```suggestion
A checkup shall be deployed to an existing Namespace, including:
- ServiceAccount.
- Role (optional).
- RoleBinding (optional).
- ClusterRole (optional).
- ClusterRoleBinding (optional).
```

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +
```suggestion
The user should provide a ServiceAccount granted with the necessary permissions the checkup requires.
The Checkup configuration `ConfigMap` shall include the name of the user-provided ServiceAccount name.
```

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +
```suggestion
The checkup execution flow is not changed.
```

2022-08-17 15:44 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +Kiagnose shall not delete the user-supplied `ServiceAccount` or any of its user-supplied permissions.
```suggestion
Kiagnose shall delete only the objects it created during execution:
- Job
- RoleBinding
- Role
- Results ConfigMap

Kiagnose shall not delete the user-supplied `ServiceAccount` or any of its user-supplied permissions.
```

2022-08-17 17:53 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +| spec.serviceAccountName | Existing serviceAccount for the checkup’s Job                            | True         | `default` ServiceAccount name is not allowed |
> I think it's worth adding a note about default service accounts.

Do you have a suggestion for this note's phrasing?

2022-08-17 17:55 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +- Kubernetes cluster administrators.
No, because this proposal is only applicable to users that are able to manually trigger a Job in the `kiagnose` namespace.

2022-08-17 17:58 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +- I want to deploy Kiagnose with less powerful cluster-wide privileges.
> Maybe "I want to deploy Kiagnose without cluster-admin previliges"

Even after the proposed change, in order to deploy `kiagnose` you still need to have the ability to:
1. Create a namespace (`kiagnose`).
2. Create a ServiceAccount in that namespace.
3. Create a ClusterRole and a ClusterRoleBinding.

The "thing" that is less powerful is the ClusterRole, it has less privileges.
Pleas see PR #150 for more details.

2022-08-17 18:00 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +- I want to be able to monitor and observe if the checkup is undergoing or finished.
Yes, it is taken from the [design doc](https://github.com/kiagnose/kiagnose/blob/main/docs/kiagnose_design.md) IIRC.

2022-08-18 13:32 UTC, phoracek commented on docs/design-proposals/permissions_reduction_proposal.md
> +## Kiagnose Deployment
Is any of this different from the current state?

2022-08-18 13:32 UTC, phoracek commented on docs/design-proposals/permissions_reduction_proposal.md
> +## Checkups Deployment
The title is confusing since this text below is not deploying a checkup. Perhaps "checkup execution pre-requirements"?

2022-08-18 13:32 UTC, phoracek commented on docs/design-proposals/permissions_reduction_proposal.md
> +2. Role and RoleBinding to the user-supplied `ServiceAccount` so the checkup could write its results to the
Any reason to make an exception about "supplied service account"? If we required provider of the checkup to document role and rolebinding for a config map as a part of they spec, we remove all management of RBAC.

2022-08-18 14:01 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +## Kiagnose Deployment
There is a mistake in part.
Kiagnose deployment should stay the same.
Thanks.

2022-08-18 14:07 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +## Kiagnose Deployment
It will just be granted fewer privileges.

2022-08-18 14:12 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +2. Role and RoleBinding to the user-supplied `ServiceAccount` so the checkup could write its results to the
We can move the responsibility of creating the results ConfigMap to the checkups.
It will indeed remove all RBAC responsibility from Kiagnose, but will require all checkups to have an additional permission.

2022-08-18 14:13 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/2bb28fa487c16773e1e3fadf32d1dfe37c764ba1..ddf3dd7e0024452798e503a5d24e17a816b2e2df): Changed "Kiagnose deployment" content.

2022-08-18 14:16 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +
This whole section was a mistake copied from a non-relevant proposal.

2022-09-15 08:04 UTC, ormergi commented on docs/design-proposals/permissions_reduction_proposal.md
> +| spec.serviceAccountName | Existing serviceAccount for the checkup’s Job                            | True         | `default` ServiceAccount name is not allowed |
Similar to what you mentioned above, something like:

> When the default service account is being used for the checkup it will be granted permission to update the result configmap.
> New pods that will be created with the default SA (if no other was specified) will be able to update the checkup result configmap and potentially cause unexpected results.

2022-09-15 08:09 UTC, orelmisan commented on docs/design-proposals/permissions_reduction_proposal.md
> +| spec.serviceAccountName | Existing serviceAccount for the checkup’s Job                            | True         | `default` ServiceAccount name is not allowed |
The "default" ServiceAccount name is an illegal input value in order to avoid this problem. 
A [link](https://github.com/kiagnose/kiagnose/blob/2c517160510ff406a95494b65cc622818441849e/kiagnose/internal/config/cmparser.go#L114) to the implementation.

2022-10-27 09:30 UTC, orelmisan commented
Rebase.
This design proposal was implemented and made obsolete by the changes in PR #189.
I suggest to merge it as-is for documentation purpose.
Any more work on it is useless IMO.

2022-10-30 13:21 UTC, EdDev commented
> Rebase. This design proposal was implemented and made obsolete by the changes in PR #189. I suggest to merge it as-is for documentation purpose. Any more work on it is useless IMO.

Once there are reviews in place, I think they need to be addressed.
The only way to ignore them is to close this PR and declare the same (i.e. "any more work on this is useless").

2022-10-30 13:23 UTC, orelmisan commented
This design proposal was implemented and made obsolete by the changes in PR https://github.com/kiagnose/kiagnose/pull/189.

2022-10-30 13:23 UTC, closed without merging