Remove ephemeral namespace feature
kiagnose/kiagnose pull request #149
Opened 2022-08-15 19:11 UTC by orelmisan

Currently, kiagnose has a feature to execute a checkup in a dedicated ephemeral [Namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/).
This causes Kiagnose to require very high, cluster-wide permissions for its operation. For example:

1. Get, List, Create, delete and Watch `Namespace` objects.
2. Get, List, Create and Delete `ServiceAccount` objects.
3. Get, List, Create, Delete and Bind `ClusterRole` and `Role` objects.

This change will:
1. Remove Kiagnose's permissions regarding namespaces.
2. Limit checkup execution to existing namespaces.

This PR partly implements the proposal introduced in PR #147.
This PR depends on PR #148.

2022-08-16 11:49 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/dbf1f762401b5a472e84e265bdf39e76826ae2da..45506602ad016a81365700e9622800ce0ecef682): Convert `TestCheckupSetupShould()` to use a target namespace instead of removing it.

2022-08-17 10:34 UTC, RamLavi reviewed
in commit `checkup, tests: Remove ref to ephemeral ns`, 
typo: successful a successful --> a successful

2022-08-17 10:47 UTC, orelmisan commented
> in commit `checkup, tests: Remove ref to ephemeral ns`, typo: successful a successful --> a successful

Thanks for the heads up.
Done.

2022-08-17 11:38 UTC, RamLavi commented on manifests/kiagnose.yaml
> -      - get
perhaps we should keep the "get/list" option? We would need to return it when supporting label check. If you plan to return it on a future PR that's ok as well

2022-08-17 11:44 UTC, RamLavi requested changes
Shouldn't [this](https://github.com/kiagnose/kiagnose/pull/149/files#diff-56ab2098f9d79345b936802584dc1eec10db04404184b6ef4328b98229ad071dR56) go away as well?

2022-08-17 11:44 UTC, orelmisan commented on manifests/kiagnose.yaml
> -      - get
I plan to return it when we'll implement this feature.
Until then, no code is using this permission so I think it would be best to remove it.

2022-08-17 11:45 UTC, RamLavi commented
> Shouldn't [this](https://github.com/kiagnose/kiagnose/pull/149/files#diff-56ab2098f9d79345b936802584dc1eec10db04404184b6ef4328b98229ad071dR56) go away as well?

never mind I missed to commit comment about it

2022-08-17 11:46 UTC, orelmisan commented
> Shouldn't [this](https://github.com/kiagnose/kiagnose/pull/149/files#diff-56ab2098f9d79345b936802584dc1eec10db04404184b6ef4328b98229ad071dR56) go away as well?

It should.
The commit message states that there is still one last reference to it, that will be removed in the follow-up PR which will remove almost all code regarding Roles and ClusterRoleBindings

2022-08-17 18:40 UTC, ormergi reviewed
Thanks for the PR, nice work!

I find it challenging to review due to the PR structure and commits order.
I suggest the change the PR structure to make it easier to review and most importantly make the commits atomic (as possible) as follows:
- Introduce new logic, new tests and adapted tests
- Remove redundant tests
-  checkup: Remove redundant variable
- Update readme

The least is to order the commits as above if it's possible.

Let me know if it works for you.

Regarding the commit "checkup, tests: Convert Job failures to target ns" claim to fix a bug, I think it should be done on a follow-up PR.
Updating the readme can also be moved to a follow-up PR, up to you.

2022-08-18 10:44 UTC, RamLavi submitted a review, later dismissed
/lgtm

2022-08-21 09:10 UTC, EdDev reviewed
Looks good, I had only a few comments inline.

2022-08-21 09:10 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +	if c.job != nil {
> Also fix a bug caused by trying to reference a nil pointer
> when trying to delete a Job that had failed to be created.

I do not understand why this was needed. Could you please explain?

2022-08-21 09:41 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +					Roles:        nil,
There is no need to explicitly set these.
I'll remove them so it will be implicit.

2022-08-21 09:41 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +					Roles:        nil,
There is no need to explicitly set these.
I'll remove them so it will be implicit.

2022-08-21 09:41 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +		targetNs := &corev1.Namespace{
Yes.

2022-08-21 09:43 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	if c.job != nil {
One of the tests causes the `c.job` member to become `nil` because of an induced failure.
Then, the `Teardown()` panics.
Without this change, the unit tests shall not pass.

2022-08-21 10:26 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +		targetNs := &corev1.Namespace{
Done.

2022-08-21 10:26 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +					Roles:        nil,
Done.

2022-08-21 10:26 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +					Roles:        nil,
Done.

2022-08-21 11:02 UTC, orelmisan commented
Changes [1](https://github.com/kiagnose/kiagnose/compare/f80838a3bdc33cdeaa9f295e674e05009bb5b14e..2593b7edaab7851be60d2762dd9afa539f2c6bf4) and [2](https://github.com/kiagnose/kiagnose/compare/2593b7edaab7851be60d2762dd9afa539f2c6bf4..4c7d711af4dc6d527362e8b630334985dfa00df6) Answered @EdDev's review comments.

2022-08-21 11:03 UTC, orelmisan commented
Updated `docs/checkup_api.md` file.

2022-08-21 11:07 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> -	return c.teardownWithTargetNamespace()
IMO, it would make [this](https://github.com/kiagnose/kiagnose/pull/149/commits/1f19129d710946f4ac9a8dbfb7b7f881e04f107f) commit harder to understand if everything was done at once.
That is why I've made this change in the [following commit](https://github.com/kiagnose/kiagnose/pull/149/commits/962f0fff3ac4169980432de917703ae380b49910).

2022-08-21 11:10 UTC, orelmisan commented on README.md
> +Kiagnose can execute a checkup in an existing Namespace.
Done.

2022-08-21 11:10 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/027f858f123007618e5151b26136e63aff995ba4..f80ab639a02183668c51f6297070df23163f1218): Answered @ormergi's [comment](https://github.com/kiagnose/kiagnose/pull/149#discussion_r948152430).

2022-08-21 12:09 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +	if c.job != nil {
Ok, thanks.

2022-08-21 12:11 UTC, EdDev approved these changes
Thanks!

2022-08-21 12:57 UTC, RamLavi approved these changes
/lgtm

2022-08-21 13:10 UTC, orelmisan commented
Rebase

2022-08-21 14:03 UTC, EdDev approved these changes
Thanks!

2022-08-21 14:03 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> -	return c.teardownWithTargetNamespace()
Looks like a nit to me. I can understand both arguments, either way it is not worth debating it too much.

2022-08-21 14:03 UTC, merged