Checkup spec: read and parse checkup's spec from ConfigMap object
kiagnose/kiagnose pull request #15
Opened 2022-04-05 13:56 UTC by orelmisan

This add the ability to read and parse  checkup's spec from a ConfigMap object.

2022-04-05 17:17 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/66bff36aa0f3db018bcfc23d180186e755ab5bbb..edaaa90f089d16eb2f227ae7bdefa8ee0cba5bb1): Fixed a problem discovered by the linter.

2022-04-06 12:30 UTC, EdDev commented on kiagnose/mainflow.go
> +func readConfigMapFullNameFromEnv() (namespace, name string, err error) {
This should not be here, but hidden in some package.

2022-04-07 06:20 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/81957fe3100b8474c3dd428df0bb0f9be635f4e7..7f40b7036a5466a7bec415ee999f346c897e091b): Changed a commit message.

2022-04-07 08:18 UTC, orelmisan commented
Changes: Optimized the unit test code.

2022-04-07 08:32 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/65691c0adf658ea9aa0c19573d97431a00913552..5ba741e6a9ce2583af23c85a1141141f72f73022): Fixed linter problems.

2022-04-07 13:47 UTC, EdDev requested changes

2022-04-07 13:47 UTC, EdDev commented on kiagnose/internal/checkup/spec_test.go
> +		defer os.Unsetenv(checkup.ConfigMapNameEnvVarName)
I prefer our unit tests to be "pure", in the sense they are not to depend on the OS.

Per what I actually see in these tests, it is also not needed. The production code does not call `os.*`, so I am unclear why it is used at all.

2022-04-07 13:47 UTC, EdDev commented on kiagnose/internal/checkup/spec_test.go
> +func checkNewSpecLoaderFailure(t *testing.T, expectedError string) {
I find this helper problematic for several reasons:
- It hides the main test operation, mixing both execution of the tested production code and the assertions.
- That you expect a specific error text, which does not seem to be a public API (i.e. it can change and therefore break all these tests).
- That you use `os.Environ()` and therefore depend on the OS, when there is nothing that requires it.
- That you create a fake client, but you do not really have to.

2022-04-07 13:47 UTC, EdDev commented on kiagnose/internal/checkup/spec_test.go
> +	assert.Nil(t, specLoader)
It is a common practice to ignore the returned value in case of error.
No one should trust the value in case of an error, so we do not need to check it.

2022-04-07 13:47 UTC, EdDev commented on kiagnose/mainflow.go
> +	"k8s.io/client-go/rest"
I prefer not to see such a dependency at this top level.
Barring it deep under an inner package makes it cleaner IMO. (e.g. [this](https://github.com/kiagnose/kiagnose/pull/9/files#diff-c810fb751f76dc7919d84b25d9611683296c4e3648b45d588ba7db3af1954038R20))

2022-04-07 13:47 UTC, EdDev commented on kiagnose/mainflow.go
> +	env := os.Environ()
This is an implementation detail I prefer to be deep inside the package that implements it.

2022-04-07 13:47 UTC, EdDev commented on kiagnose/mainflow.go
> +	}
I would have preferred to see a separation between the `checkup` package and the loading/importing of the configuration.
To have such a separation, I imagine a totally independent package that is instantiated and then instructed to load the configuration, similar to what you just did.

I am unclear why I need a `*Loader`, I think from a usage perspective, this can be enough:
```
conf, err := config.New(clientset)
if err != nil { return err }

confData, err := conf.Load()
if err != nil { return err }
```

In the `config` package I expect to see a `config` file that has the general/common parts and in a `configmap` the things specific to configmaps. Same for `envvar` and other implementation specifics.
Considering that we do want to more in the future away from them, we want to change as little as possible at the business logic or common areas.

2022-04-11 12:34 UTC, orelmisan commented on kiagnose/internal/checkup/spec_test.go
> +		defer os.Unsetenv(checkup.ConfigMapNameEnvVarName)
This was removed.

2022-04-11 12:35 UTC, orelmisan commented on kiagnose/mainflow.go
> +	"k8s.io/client-go/rest"
Done.

2022-04-11 12:35 UTC, orelmisan commented on kiagnose/mainflow.go
> +	env := os.Environ()
This was removed.

2022-04-11 13:57 UTC, orelmisan commented
Changes: Fixed code review comments + linter errors.

2022-04-12 09:54 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/baae1eaeddbcede3194a2bbc676c2c7509cec323..fd48f7f2987eb4a710e672574b78f36e29621257): Moved types form loader_test.go to outside of Test*() functions.
Also changed their field names according to an offline code-review comment by @ormergi.

2022-04-12 11:20 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/fd48f7f2987eb4a710e672574b78f36e29621257..cf1d4c7071850ada0d22df9da2b04a5fa79df61b): Changed Config.Params to Config.EnvVars of type `[]corev1.EnvVar`.

2022-04-12 15:29 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/e0d7a0f6299fb4fd640e46192b4f7b0bc3210846..bcb79833db1d963b3cc7de46893568817dba6841): Added `config.ErrRoleNameIsIllegal`.

2022-04-13 06:24 UTC, EdDev requested changes

2022-04-13 06:24 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +func splitRoleName(fullName string) (namespace, name string, err error) {
Why are you using named return values? This is not a common practice and is usually reserved for cases where you must (e.g. using a defer that wants to change the returned value).

2022-04-13 06:24 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +	configMapName      string
Looking at this after looking at all the rest of the code, it looks to me like these 3 values are the only ones needed for a loader. All the rest are results of intermediate steps which do not really need to be preserved in this object state.

2022-04-13 06:24 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +)
It seems to me like all globals here are used in specific tests (or groups) and not shared between many.
So it would be safer and more easily read if placed near the usage as possible.

Please try to follow this with other variables, I have may missed others.

2022-04-13 06:24 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +		assert.NotNil(t, loader)
I think that checking that it is not a nil is not very useful, could you check against something you expect to see in the output that has some explicit meaning?
Such asserts have value during development, but less value at the end (unless you can check for some explicit result).

2022-04-13 06:24 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +	fakeClient := fake.NewSimpleClientset()
You can inline this, but is it even needed for these tests?

2022-04-13 06:24 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +		fakeClient := fake.NewSimpleClientset()
Can you pass a `nil` instead of a fake? You do not really need the fake in these tests.

2022-04-13 06:24 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +func newFakeClientset(namespace,
This seems to be a clientset with stuff in it. Can you please name it to express that?

2022-04-13 06:24 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +	roles []*rbacv1.Role) *config.Config {
I would prefer one liner, even if it is long. It is hard to read it like this.

Same for the others.

2022-04-13 08:39 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +func (l *Loader) getConfigMapFullNameFromEnv(env map[string]string) (err error) {
1. The named returned value was a leftover, thanks for catching it.
2. Agreed.

2022-04-13 09:13 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +func splitRoleName(fullName string) (namespace, name string, err error) {
Our linter requires it:
```
./automation/make.sh 
kiagnose/internal/config/loader.go:179:1: unnamedResult: consider giving a name to these results (gocritic)
func splitRoleName(fullName string) (string, string, error) {
^
```

2022-04-13 11:51 UTC, orelmisan commented on kiagnose/mainflow.go
> +func readConfigMapFullNameFromEnv() (namespace, name string, err error) {
Done.

2022-04-13 11:52 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +func (l *Loader) getConfigMapFullNameFromEnv(env map[string]string) (err error) {
Done.

2022-04-13 11:53 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +		checkupConfig: &Config{},
This was changed, and taken out of config.Loader.

2022-04-13 11:53 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +	}
Done.

2022-04-13 11:53 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +	configMapName      string
Done.

2022-04-13 11:57 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/bcb79833db1d963b3cc7de46893568817dba6841..ea90db57115a224a2328eae590b1f5684e32ef9a): Fixed comments from code review in production code.

2022-04-13 12:12 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +	fakeClient := fake.NewSimpleClientset()
Replaced it with nil.

2022-04-13 12:13 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +		fakeClient := fake.NewSimpleClientset()
Replaced it with nil.

2022-04-13 12:31 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/ea90db57115a224a2328eae590b1f5684e32ef9a..cbe4d70fbee84e205150a79cc1ee17385fbf6fc8): Fixed comments from code review in unit test code.

2022-04-13 14:42 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/cbe4d70fbee84e205150a79cc1ee17385fbf6fc8..3df113b0ca02f8742dc59b9b13d37d2932a2f8e8): Added a test case - fail when ConfigMap object doesn't exists.

2022-04-14 05:55 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/3bafbf849f1e0ab20ce67258d9c9e6ad338650d1..f9bdef8ead13148dffaecf433eb81abe87bd5590): Moved low level K8s client usage to a dedicated function.
Try to get ClusterRole and Role objects, only after successful parsing of their names.

2022-04-14 08:56 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/f9bdef8ead13148dffaecf433eb81abe87bd5590..68792f2fa76a70b2ddcd45295ec313b30c4d49f9): Extracted the parsing logic from config.Loader to a new entity.

2022-04-14 09:30 UTC, orelmisan commented
Change: Fixed code review comments regarding unit test code.

2022-04-14 11:33 UTC, EdDev reviewed
I had some comments but I am ok with proceeding in this state as is and fixing/improving as a followup PR.

Review and check if you want to take some of the suggestions now.
And most importantly, please check this is working ok against a real `ConfigMap` if you can.

2022-04-14 11:33 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +func (l *Loader) getRoles(roleNames []string) ([]*rbacv1.Role, error) {
nit: You do not need the get really, it is redundant.

2022-04-14 11:33 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +		splitName, err := splitRoleName(roleName)
nit: `fullRoleName` ?

2022-04-14 11:33 UTC, EdDev commented on kiagnose/internal/config/parser.go
> +func newConfigMapParser(client kubernetes.Interface, env map[string]string) (*configMapParser, error) {
Can you also name the file with relation to the ConfigMap? e.g. `cmparser`

2022-04-14 11:33 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +	}
It does not seem to be a responsibility of a parser to get the object. A parser parses, it is not suppose to know how to fetch the object.

But I think this can be improved in parallel to the next step, so for now I tend to just let it roll.

2022-04-14 11:33 UTC, EdDev commented on kiagnose/internal/config/parser.go
> +		return err
I think you are not testing this path.

2022-04-14 11:33 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +			return nil, err
I think you are not testing this path.

2022-04-14 11:33 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +			return nil, err
I think you are not testing this path.

2022-04-14 11:57 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +func (l *Loader) getClusterRoles(clusterRoleNames []string) ([]*rbacv1.ClusterRole, error) {
`l.clusterRoles` looks off to me.

2022-04-14 12:02 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +	}
I agree that its not the parser's responsibility.

2022-04-14 12:04 UTC, orelmisan commented on kiagnose/internal/config/parser.go
> +		return err
It is tested in a scenario when the ConfigMap doesn't exists.
When we'll have E2E tests, they should also test read permission problems.

2022-04-14 12:04 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +			return nil, err
It is tested in a scenario when the Role doesn't exists.
When we'll have E2E tests, they should also test read permission problems.

2022-04-14 12:04 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +			return nil, err
It is tested in a scenario when the ClusterRole doesn't exists.
When we'll have E2E tests, they should also test read permission problems.

2022-04-14 12:41 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/0931821973a9544544444c33b6c711e5f2bb97ec..fc259ce518132787efff1cf669409783843339f3): Fixed code review comments.

2022-04-14 12:49 UTC, EdDev commented on kiagnose/internal/config/parser.go
> +		return err
The unit tests do not simulate the error occurring here, which means this condition is not evaluated and covered.

2022-04-14 12:51 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +			return nil, err
This still needs to be covered by unit tests.

2022-04-14 12:52 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +func (l *Loader) getClusterRoles(clusterRoleNames []string) ([]*rbacv1.ClusterRole, error) {
I do not like `get`, but this is a nit, I will not insist.

2022-04-14 12:54 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/fc259ce518132787efff1cf669409783843339f3..6bf2db6e17030bfe16049fe1144e30c97d12315d): Moved ConfigMap namespace and name back to loader.go.

2022-04-14 13:07 UTC, orelmisan commented on kiagnose/internal/client/client.go
> +func GetK8sClientset() (*kubernetes.Clientset, error) {
Done.

2022-04-14 13:11 UTC, EdDev approved these changes
Thank you!

2022-04-17 08:20 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +			return nil, err
The call to `Get()` returns an error if there is no ClusterRole with the requested name.

2022-04-17 08:21 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +			return nil, err
The call to `Get()` returns an error if there is no Role with the requested `namspace/name`.

2022-04-18 06:24 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/23ab02e01cef696d6b1c3d0c603e17751abe48c0..6db629219d4484072c5541b1c9726d49edcc5e6b): Rebase and integration with PR #9.

2022-04-18 10:32 UTC, ormergi commented on kiagnose/internal/config/loader.go
> +type Loader struct {
It would make Loader{} easier to change (e.g moving to CRD) if it would hold an instance of a parser,
it could also make it easier to test as you could replace it with a stub on tests.

2022-04-18 10:32 UTC, ormergi commented on kiagnose/internal/config/loader_test.go
> +func TestLoaderLoadShouldFail(t *testing.T) {
Please add tests to cover client errors e.g: when it fails to fetch Role's ClusterRole's or ConfigMap's
similar to what we do at `checkup` tests.

2022-04-18 10:32 UTC, ormergi commented on kiagnose/internal/config/loader_test.go
> +	}
I think those tests should have their own test suite at `cmparser` package, 
it would make it easier to test Loader{} as you could replace it the parser with a stub.
Will you give it a try?

2022-04-18 10:32 UTC, ormergi commented on kiagnose/mainflow.go
> +func Run(env map[string]string) error {
I think mainflow.Run() should read env by it self instead of receiving it as parameter,
it should at least validate ConfigMap name and namespace env vars are valid as it is critical 
requirement for it to work.
It is not the scope of the "config loader" to validate it.

2022-04-18 11:09 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +}
There is now a configmap package containing both functions.

2022-04-18 11:11 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/6db629219d4484072c5541b1c9726d49edcc5e6b..088d2010d0fcb2ddb72db853ea5c54b7e2e03b4f): Added a configmap package to unify actions against a ConfigMap object.

2022-04-18 11:21 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +			return nil, err
Done.

2022-04-18 11:22 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/088d2010d0fcb2ddb72db853ea5c54b7e2e03b4f..d24bc743c40da32d9b9058d1ef1e5188b6b18aed): Put the logic of `splitRoleName()` inline.

2022-04-18 11:25 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +			assert.Equal(t, testCase.expectedConfig, actualConfig)
IIUC assert.ElementsMatch() works on slices.
Here we have a slice inside a struct so it won't help in this case because we are comparing structs.

2022-04-18 11:27 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +	t.Run("when ConfigMap doesn't exist", testLoaderFailureWhenConfigMapIsMissing)
Done.

2022-04-18 11:28 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/d24bc743c40da32d9b9058d1ef1e5188b6b18aed..230c3553275929c26f313afcec5ba8b57c7f281f): Inlined testLoaderFailureWhenConfigMapIsMissing()

2022-04-18 13:05 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +type Loader struct {
The tests in loader_test.go are also covering 100% of the parser code.

2022-04-18 13:07 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +func NewLoader(client kubernetes.Interface, env map[string]string) (*Loader, error) {
As we have discussed offline, the environment variables validation logic was moved to Loader.Load().
NewLoader() doesn't return an error any more.

2022-04-18 13:10 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +func TestLoaderLoadShouldFail(t *testing.T) {
This is covered by three tests:
1. [Failure to get a ConfigMap](https://github.com/kiagnose/kiagnose/pull/15/files#diff-9c52ee6d71999c83d9e358fc8c604002291553b5351a4c710ac89fdc1b662206R157).
2. [Failure to get a ClusterRole](https://github.com/kiagnose/kiagnose/pull/15/files#diff-9c52ee6d71999c83d9e358fc8c604002291553b5351a4c710ac89fdc1b662206R192).
3. [Failure to get a Role](https://github.com/kiagnose/kiagnose/pull/15/files#diff-9c52ee6d71999c83d9e358fc8c604002291553b5351a4c710ac89fdc1b662206R197).

2022-04-18 13:10 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +	}
The tests in loader_test.go are also covering 100% of the parser code.

2022-04-18 13:11 UTC, orelmisan commented on kiagnose/mainflow.go
> +func Run(env map[string]string) error {
The validation was moved to Loader.Load().

2022-04-18 13:37 UTC, orelmisan commented
Change: Fixed commit messages.

2022-04-18 13:56 UTC, EdDev reviewed
First commit

2022-04-18 13:56 UTC, EdDev commented on kiagnose/internal/configmap/configmap.go
> +func GetData(client kubernetes.Interface, namespace, name string) (map[string]string, error) {
The commit says it moves the the package up, but in fact you also introduce a new method.

I would just move it, reasoning that it also is to be shared with the config package.
Then, when you actually need that method, to introduce it.

BTW, when you add it, it will fit nicer below the `Create` (just a nit).

2022-04-18 13:58 UTC, EdDev reviewed
Second commit.

2022-04-18 13:58 UTC, EdDev commented on kiagnose/internal/rbac/rbac.go
> +func GetClusterRole(client kubernetes.Interface, name string) (*rbacv1.ClusterRole, error) {
Same here, better introduce it when you actually use it.

2022-04-18 14:08 UTC, EdDev reviewed
commit 3

2022-04-18 14:08 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +	var err error
I think you need this only further below. Try to place it close to it being needed.

2022-04-18 14:08 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +	if err != nil {
Can be inlined

2022-04-18 14:22 UTC, orelmisan commented on kiagnose/internal/configmap/configmap.go
> +func GetData(client kubernetes.Interface, namespace, name string) (map[string]string, error) {
Done.

2022-04-18 14:22 UTC, orelmisan commented on kiagnose/internal/rbac/rbac.go
> +func GetClusterRole(client kubernetes.Interface, name string) (*rbacv1.ClusterRole, error) {
Done.

2022-04-18 14:26 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +	if err != nil {
Without this, one linter fails, without the previous one, a different linter fails.

2022-04-18 14:27 UTC, orelmisan commented
Change: Changed commit messages.

2022-04-18 14:34 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +type Loader struct {
In this case, I think it is actually very easy to keep the parser internal and not expose it as an API.
By doing so, the tests are not aware it even exists and therefore should not be affected if it changes (or replaced).

There are cases where this is not possible (e.g. the k8s client) due to external dependencies, but here it is.
It is also easy to check all permutations through the `Loader` API, at least with the current input/output logic options.

2022-04-18 14:34 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +func TestLoaderLoadShouldFail(t *testing.T) {
The client errors seem to be covered by just making sure the fetched object is not in the fake client.
It was illusive to me too at first.

2022-04-18 14:34 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +	if err != nil {
Why would `if err := parser.Parse(); err != nil {...}` fail?

2022-04-18 14:45 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +	if err != nil {
```
if err := parser.Parse(); err != nil {
	return nil, err
}
```

```
./automation/make.sh 
kiagnose/internal/config/loader.go:68:5: shadow: declaration of "err" shadows declaration at line 61 (govet)
        if err := parser.Parse(); err != nil {
           ^
```

2022-04-18 14:56 UTC, EdDev commented on kiagnose/internal/config/loader.go
> +	if err != nil {
Pfff... just a matter of naming (and line 61 should have been removed).
Not going to block on this nit.

2022-04-18 14:56 UTC, EdDev approved these changes
Thank you!

2022-04-18 15:31 UTC, ormergi commented on kiagnose/internal/config/loader_test.go
> +	}
I think this can be simplified by passing `[]ClusterRoles` and `[]Roles` directly to `fake.NewSimpleClientset()`.

2022-04-18 15:31 UTC, ormergi commented on kiagnose/internal/config/loader_test.go
> +			description:   "when Role name is illegal",
Do you think it make sense to cover more cases of `RolesKey`, such as `/myrole` `myns/` `ns//role` `""`?

What you think about adding similar test for `ClusterRoleKey` does it make sense?

2022-04-18 15:31 UTC, ormergi commented on kiagnose/mainflow.go
> -	l := launcher.New(checkup.New(c, "", 0, nil, nil, nil), reporter.New())
Looks like a leftover

2022-04-18 15:32 UTC, ormergi commented
@orelmisan 
Thanks for the changes it look much better!

I have some more comments, most of them are suggestions to simplify the code even more,
Please take a look and see if it make sense to do.

2022-04-18 18:15 UTC, EdDev reviewed
I answered here in an attempt to separate the nits from the ones which merit attention once detected.
Looking forward to see this finalized.

2022-04-18 18:15 UTC, EdDev commented on kiagnose/mainflow.go
> -	l := launcher.New(checkup.New(c, "", 0, nil, nil, nil), reporter.New())
?

2022-04-19 06:00 UTC, orelmisan commented on kiagnose/internal/config/cmparser.go
> +func (cmp *configMapParser) Parse() error {
The parser internal state is different than the Config struct.
The image and timeout fields are the same but:
1. The parser holds raw map of strings for params, while Config holds []EnvVar.
2. The parser holds names of ClusterRole and Role objects, while Config holds a slices of ClusterRole and Role.

2022-04-19 06:02 UTC, orelmisan commented on kiagnose/internal/config/cmparser.go
> +	ErrRoleNameIsIllegal     = errors.New("illegal Role name")
This allows us to publish (some) of the errors that this package produces.

2022-04-19 06:03 UTC, ormergi commented on kiagnose/internal/config/cmparser.go
> +	ErrRoleNameIsIllegal     = errors.New("illegal Role name")
I am not talking about formatting strings, just extracting the message to const and create the error where needed:
```
const errNotValid = "not valid"
...
func foo () err {
    return errors.New("errNotValid")
}
```
Currently we do not provide errors as part of the API, isnt it?

2022-04-19 06:05 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +	const envVarErrFmtString = "missing required environment variable %q"
Done.

2022-04-19 06:10 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +	}
Done.

2022-04-19 06:11 UTC, ormergi commented on kiagnose/internal/config/cmparser.go
> +func (cmp *configMapParser) Parse() error {
> Considering that the parsing includes multiple functions, each requiring to pass the raw data, the usage of receivers seems reasonable to me.

Just to be clear, changing Parse() to static also means getting rid of the helpers receivers so each will be static as well.

I am not insisting on this change.

2022-04-19 06:19 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +func (l *Loader) getClusterRoles(clusterRoleNames []string) ([]*rbacv1.ClusterRole, error) {
Done.

2022-04-19 06:19 UTC, orelmisan commented on kiagnose/internal/config/loader.go
> +func (l *Loader) getRoles(roleNames []string) ([]*rbacv1.Role, error) {
Done.

2022-04-19 06:19 UTC, ormergi commented on kiagnose/internal/config/loader_test.go
> +			assert.ErrorContains(t, err, testCase.expectedErrorContains)
Errors may change over time meaning it will be necessary to change the tests accordingly, 
I think we should avoid assenting on error message content when possible.

Using `assert.Error()` will simplify the tests since there will be no need to pass `expectedErrorContains`
on each test case.

2022-04-19 06:20 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +			assert.ErrorContains(t, err, testCase.expectedErrorContains)
Here we want to differentiate between different errors, not just to assert that an error had occurred.

2022-04-19 06:23 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +			fakeClient := newFakeClientWithObjects(configMapNamespace, configMapName, testCase.configMapData, nil, nil)
Done.

2022-04-19 06:27 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/fcff5c7929d9f62e7d54623a7d0479367d6560bd..7197d634f0a7cf4d9a7e338ff614d2426ca700b4): Answered code review comments.

2022-04-19 06:32 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +			fakeClient := newFakeClientWithObjects(configMapNamespace, configMapName, testCase.configMapData, testCase.clusterRoles, testCase.roles)
I've had problems making this compile.

2022-04-19 06:35 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +		},
Can you please elaborate?

2022-04-19 06:35 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +	}
Can you please elaborate?

2022-04-19 06:36 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +	}
I've had problems making it compile.

2022-04-19 06:36 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +			description:   "when Role name is illegal",
There is a full ticket regarding configuration validation.
IMO this should be handled there.

2022-04-19 06:37 UTC, orelmisan commented on kiagnose/mainflow.go
> -	l := launcher.New(checkup.New(c, "", 0, nil, nil, nil), reporter.New())
This is a code that was deleted.
What is wrong with it?

2022-04-19 06:39 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/7197d634f0a7cf4d9a7e338ff614d2426ca700b4..de035b2fcca73c3908c64e56d18e50ab190f19e6): Fixed a small bug in `newFakeClientWithObjects()`

2022-04-19 06:42 UTC, ormergi commented on kiagnose/mainflow.go
> -	l := launcher.New(checkup.New(c, "", 0, nil, nil, nil), reporter.New())
Correct me if I am wrong but this change was introduced on commit #4 and and deleted at commit #5.

2022-04-19 07:14 UTC, ormergi commented on kiagnose/internal/config/loader_test.go
> +		},
```
{TypeMeta: metav1.TypeMeta{Kind: "ClusterRole", APIVersion: rbacv1.GroupName},ObjectMeta: metav1.ObjectMeta{Name: "cluster_role1"}},
```

2022-04-19 07:14 UTC, ormergi commented on kiagnose/internal/config/loader_test.go
> +	}
```
{TypeMeta: metav1.TypeMeta{Kind: "Role", APIVersion: rbacv1.GroupName}, ObjectMeta: metav1.ObjectMeta{Name: "role2", Namespace: "default"}}
```

2022-04-19 07:14 UTC, ormergi commented on kiagnose/mainflow.go
> -	l := launcher.New(checkup.New(c, "", 0, nil, nil, nil), reporter.New())
Correct me if I am wrong but this change (line 44) was introduced on commit #4 and and deleted at commit #5.

2022-04-19 07:17 UTC, ormergi commented on kiagnose/internal/config/cmparser.go
> +	ErrRoleNameIsIllegal     = errors.New("illegal Role name")
@EdDev  I am not talking about formatting strings, just extracting the message to const and create the error where needed:
```
const errNotValid = "not valid"
...
func foo () err {
    return errors.New("errNotValid")
}
```
@orelmisan the errors are only used at tests, and they can use the error message instead.
I think this package should not expose the errors until there is a need for it.

2022-04-19 07:18 UTC, ormergi commented on kiagnose/internal/config/loader_test.go
> +	}
Sorry for the noise, I checked it again and it works when passing *RoleList and *ClusterRoleList instead of []*Role and []*ClusterRoleList.

2022-04-19 07:20 UTC, orelmisan commented on kiagnose/mainflow.go
> -	l := launcher.New(checkup.New(c, "", 0, nil, nil, nil), reporter.New())
Commit 4 is to introduce the Config loading to mainflow.
Commit 5 is to integrate the config loading with the checkup.

Is there something do you think we should do here?

2022-04-19 07:22 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +			assert.ErrorContains(t, err, testCase.expectedErrorContains)
IMO we should check that the error we expect is the actual error we are getting.

2022-04-19 07:25 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +		},
IMO it makes it less readable.

2022-04-19 07:25 UTC, orelmisan commented on kiagnose/internal/config/loader_test.go
> +	}
IMO it makes it less readable.

2022-04-19 07:27 UTC, ormergi commented on kiagnose/mainflow.go
> -	l := launcher.New(checkup.New(c, "", 0, nil, nil, nil), reporter.New())
Remove this line https://github.com/kiagnose/kiagnose/pull/15/commits/79420429daaf952650e57f41cb4f37c7a47ace58#diff-4ec73023f96b17dcaab6fb900294476b4a985df1fac89d1545944edc5fc6e163R44

2022-04-19 07:29 UTC, ormergi commented on kiagnose/internal/config/cmparser.go
> +func (cmp *configMapParser) Parse() error {
@orelmisan I didnt meant to use `configMapParser` as the result of Parse() not `Config` struct.

2022-04-19 07:29 UTC, orelmisan commented on kiagnose/mainflow.go
> -	l := launcher.New(checkup.New(c, "", 0, nil, nil, nil), reporter.New())
It won't compile without it.
Unless we do:
```go
_, err := configLoader.Load()
```

2022-04-19 08:12 UTC, orelmisan commented on kiagnose/internal/config/cmparser.go
> +func (cmp *configMapParser) Parse() error {
IIUC you want the configMapParser (lets say ParseResults) as the result of Parse().
We can do it in a future PR.

2022-04-19 08:27 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/de035b2fcca73c3908c64e56d18e50ab190f19e6..4cd6195c2b5ec591ef11d3f2fad0210d3e9642ea): Fixed a review comment.

2022-04-19 08:29 UTC, orelmisan commented on kiagnose/mainflow.go
> -	l := launcher.New(checkup.New(c, "", 0, nil, nil, nil), reporter.New())
@ormergi Done.

2022-04-19 08:30 UTC, ormergi approved these changes
Thanks for the changes, good work!

There are these two comments https://github.com/kiagnose/kiagnose/pull/15#discussion_r852673792
https://github.com/kiagnose/kiagnose/pull/15#discussion_r852173990, if you think it will take more work then it seems we can do it on a follow up PR.

2022-04-19 08:31 UTC, ormergi commented on kiagnose/internal/config/cmparser.go
> +func (cmp *configMapParser) Parse() error {
Fair enough

2022-04-19 08:32 UTC, ormergi commented on kiagnose/internal/config/cmparser.go
> +	ErrRoleNameIsIllegal     = errors.New("illegal Role name")
@orelmisan @EdDev thanks for explaining.

Looking at this again, I was confused since on tests the assertions is done on the error message content and not on its type, I guess we can improve them later on.

2022-04-19 08:34 UTC, ormergi commented on kiagnose/internal/config/loader.go
> +	}
Sorry I wasn't clear about saying this is a nit.

2022-04-19 08:36 UTC, ormergi commented on kiagnose/internal/config/loader.go
> +}
Great, thanks!

2022-04-19 08:36 UTC, ormergi commented on kiagnose/internal/config/loader.go
> +func NewLoader(client kubernetes.Interface, env map[string]string) (*Loader, error) {
Great, thanks it looks much better.

2022-04-19 08:40 UTC, ormergi commented on kiagnose/internal/config/loader.go
> +type Loader struct {
@EdDev understood, thanks for explaining!

2022-04-19 08:52 UTC, EdDev approved these changes
Thank you!

I have considered the still open issues from the reviews and I think it is safe to merge this as is.
Thank you @ormergi for the thorough review.

2022-04-19 08:52 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +			assert.ErrorContains(t, err, testCase.expectedErrorContains)
The cleanest solution would have been to assert against an error type or instance.
You can introduce improvements to this in following changes if you like, at this stage I do not consider this a blocker.

2022-04-19 08:52 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +			fakeClient := newFakeClientWithObjects(configMapNamespace, configMapName, testCase.configMapData, testCase.clusterRoles, testCase.roles)
I agree this is an improvement, but I will take this change in even without it.
Feel free to post this change in a following PR.

2022-04-19 08:52 UTC, EdDev commented on kiagnose/internal/config/loader_test.go
> +			description:   "when Role name is illegal",
The code was introduced in this change, so tests should have been covering various scenarios of it here.
Said that, I will take the chance and take this change in even without this part.
Consider improving this in a following change.

2022-04-19 08:52 UTC, merged