vm-latency, reporter: Enhance results tests
kiagnose/kiagnose pull request #156
Opened 2022-09-05 13:06 UTC by RamLavi

This PR enhances the reporter unit tests

2022-09-05 15:42 UTC, orelmisan reviewed
Thank you for the PR @RamLavi.
Please see the inline comments.

2022-09-05 15:42 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
AFAIU, `Reporter.Report()` is only called [once](https://github.com/kiagnose/kiagnose/blob/3dac964846dc62170cf1cf725c79c162e5e35fad/checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go#L59).
I think this test case cannot happen with the production code.
@ormergi please correct me if I'm wrong.

2022-09-05 15:42 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			description:   "on checkup failed completion",
```suggestion
			description:   "on checkup failure",
```

2022-09-05 15:42 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
Please consider moving `testReporter` initialization to `setup()`

2022-09-05 15:42 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	}
Please consider adding a factory function for `configMapClientStub`:
```go
func newConfigMapClientStub(failUpdateConfigMap error) *configMapClientStub {
    return &configMapClientStub{
      configMapData: map[string]string{},
      failUpdateConfigMap: failUpdateConfigMap,
  }
}
```

2022-09-06 09:01 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
hmm.. this is an already existing test, I just expanded it, so I would be surprised if it's a non relevant case.
@ormergi ?

2022-09-06 09:03 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
since the returned value of `reporter.New()` is not public, then I can't.

2022-09-06 10:07 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			description:   "on checkup failed completion",
Done

2022-09-06 10:24 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
Looks like Report() is called one time only in the test, I think its fine.

@RamLavi is there a difference between this test and then line [72](https://github.com/kiagnose/kiagnose/pull/156/commits/3e65a22b405f132678c1ed9aeb541002ea5a6215#diff-2d21b1780f545bd92df143499f288130aaf54c3bde3f23c77cb40c1530d3cee2R72-R74)?

2022-09-06 10:30 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			}
Please consider exposing `reporter.formatStatus()` instead each of the status keys,
they are considered as an implementation detail that may change over time and break the tests.

2022-09-06 10:40 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	}
I suggest to not set gloabl var for the tests client + setup() because the next dev the write a test would need to remember it there.
I would initialize the client at each test according to what is needed instead.
WDYT?

2022-09-06 10:44 UTC, ormergi reviewed
Thanks for the PR, please see my inline comments.

2022-09-06 11:05 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
yes, in `status is initialized` Report is sent with empty status `status.Status{}`
and in the new one it is sent with non empty `status.Status`

2022-09-06 11:05 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
> Looks like Report() is called one time only in the test, I think its fine.

Yes, but on the production code it will not have these expected values.

2022-09-06 11:07 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			}
I don't think it's a good idea
if there will be a bug in formatStatus we will not see it in the unit test anymore.

2022-09-06 11:08 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
It took me by surprise TBH.
IMO it should be exported, I'll open a PR to export it.

2022-09-06 11:14 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	}
I think using the same testClient variable is a better approach than introducing it each test, but it's not a must in this case.. 
Will remove this commit and fix accordingly

2022-09-06 11:29 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
PR #159.

2022-09-06 11:37 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			}
If reporter.Report() is changed, these tests need to be changed accordingly, in case a bug is introduced it will also manifest in the test and it also won't be visible, isn't it?

Note that this test suite `TestReportShouldRunSuccessfullyWhen` is not about the correctness of the conversion from `Status{}` to `map[string]string`, it is merely a sanity check.

2022-09-06 12:08 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	}
#159 was opened in order to export `Reporter{}` to enable using it as a global variable in tests where it can be avoided, I think this is wrong.

2022-09-06 12:16 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	}
@ormergi can you please elaborate why do you think it is wrong?

2022-09-06 12:33 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			}
I share @RamLavi's opinion the test should be against an independent set of expected results.

2022-09-06 12:55 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	}
> @ormergi can you please elaborate why do you think it is wrong?

I think setting tests objects as globals is wrong, it requires more cognitive effort for the reader to figure our where these objects came from and how they initialize. 
In this test suite it may seem neglectable, but as there are more tests its will be noticeable, FWIW I experienced it myself in other projects.
I also think that exporting Reporter{} just to use it as global in tests where it can be avoided (by setting it in each test) is wrong.

2022-09-06 13:00 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	}
> I also think that exporting Reporter{} just to use it as global in tests where it can be avoided (by setting it in each test) is wrong.

Can you please write it in PR #159?

2022-09-06 14:23 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
@ormergi @RamLavi can we remove this test case?

2022-09-07 08:06 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
removed the setup after offline talk with Or

2022-09-07 08:23 UTC, ormergi reviewed
Thanks for the changes.

Regarding testing the conversion from `Status` to `map[string]string` a while back we had a discussion about whether it it's right to have such test, If I remember correctly, we concluded that this test is not effective because it will require a change every time the code it tests changes. 
Also because there is no actual logic to test most of it is variable assignments.

Even though such test would be considered not effective, it gives an indication that the checkup results ConfigMap data is according to the checkup Status as expected, without the need to check it manually with e2e test.

I think that it's okay to have it on a separate test suite until we start using a CustomResource for the checkup object.

Note: using a CustomResource instead of the checkup results ConfigMap which would include a Status object we could assert in tests and require no conversions.

2022-09-07 08:41 UTC, RamLavi commented
> Thanks for the changes.
> 
> Regarding testing the conversion from `Status` to `map[string]string` a while back we had a discussion about whether it it's right to have such test, If I remember correctly, we concluded that this test is not effective because it will require a change every time the code it tests changes. Also because there is no actual logic to test most of it is variable assignments.

maybe it was right then, but I think that right now we are not checking the values of the results, and we should. 

> Even though such test would be considered not effective, it gives an indication that the checkup results ConfigMap data is according to the checkup Status as expected, without the need to check it manually with e2e test.
> 
> I think that it's okay to have it on a separate test suite until we start using a CustomResource for the checkup object.

There are 2 ways we can test the values:
1. (Your suggestion) add a unit test in `launcher_test.go` where we have access to the configmap and check there. 
pros: we don't need to expose the const variables.
cons: no logic was added in launcher regarding the configmap, so there is no reason to check it there.
2. (my suggestion) add unit tests in `reporter_test.go`
pros: we're checking as closest to the actual code
cons: we have to expose the variables consts/the entire function (I prefer the former).

in this case I think exposing some const variables is the better approach.

> Note: using a CustomResource instead of the checkup results ConfigMap which would include a Status object we could assert in tests and require no conversions.

no argument here - and when we do so - the tests should be in `reporter_test.go` IMO.

2022-09-07 09:47 UTC, ormergi commented
@RamLavi 
> maybe it was right then, but I think that right now we are not checking the values of the results, and we should.
> 

I think it still stands, what's on the stack is having not ideal test vs. coverage and reducing the time it would take to debug it.

> in this case I think exposing some const variables is the better approach.

Maybe I didn't explain myself correctly, I was saying I am fine with having a tests that check the conversion at the reporter test, just put them in their own func to express that it checks the conversion.

2022-09-07 10:09 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
removed it , so yes

2022-09-07 10:09 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	}
removed the golbal

2022-09-11 08:11 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +func newConfigMapClientStub(failUpdateConfigMap error) *configMapClientStub {
Is it still necessary?

2022-09-11 08:11 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			description:   "on checkup failure",
Currently, when the checkup fails, the status Results{} is not populated, according to this test one might think that it is.
I suggest keeping each scenario in its own t.Run(), so the failure scenario will not assert status Results{}, WDYT?

2022-09-11 14:05 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +func newConfigMapClientStub(failUpdateConfigMap error) *configMapClientStub {
it wasn't necessary from the beginning :) 
but I think using a factory function is a good call here, as it helps readability...

2022-09-12 08:36 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			description:   "on checkup failure",
but the results are updated at the start of t.Run(), so they are indeed updated in this case.

2022-09-12 11:17 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +func newConfigMapClientStub(failUpdateConfigMap error) *configMapClientStub {
IMO there is not much of improvement to readability in this case :sweat_smile: 
See how its going to be used:
```
c := newConfigMapClientStub(expectedErr)
vs.
c := &configMapClientStub{}
c := &configMapClientStub{failUpdateConfigMap: expectedErr}
```
Having said all that, feel free to leave it as is.

2022-09-12 11:22 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			description:   "on checkup failure",
Yes, but there is no such scenario, if the checkup fails at` Run()` it will eventually report only `succeeded` and `failureReason`.
this tests show otherwise, that results are reported whether the checkup failed or not, which IMO may confuse the reader thinking this is how the production code works.

2022-09-12 11:41 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +func newConfigMapClientStub(failUpdateConfigMap error) *configMapClientStub {
I will, thanks :)

2022-09-12 11:42 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			description:   "on checkup failure",
ok I'll remove it

2022-09-12 11:50 UTC, ormergi approved these changes
Thanks for the changes!

2022-09-13 05:53 UTC, RamLavi commented
> IMO we should add a test case of a failed setup/execution/whatever scenario that updates `succeeded` and `failureReason` to `false` and `some reason` respectively.

@orelmisan please refer @ormergi's comment on this:
```
Yes, but there is no such scenario, if the checkup fails at Run() it will eventually report only succeeded and failureReason.
this tests show otherwise, that results are reported whether the checkup failed or not, which IMO may confuse the reader thinking this is how the production code works.
```
Since upon failure there wont be conversion data on the configmap, I tend to agree with Or, we should not document otherwise.

2022-09-13 07:22 UTC, orelmisan commented
> Since upon failure there wont be conversion data on the configmap, I tend to agree with Or, we should not document otherwise.

`succeeded` and `failureReason` should be filled in case of a failure, so why can't we test it?

2022-09-13 08:01 UTC, RamLavi commented
> > Since upon failure there wont be conversion data on the configmap, I tend to agree with Or, we should not document otherwise.
> 
> `succeeded` and `failureReason` should be filled in case of a failure, so why can't we test it?

[Done](https://github.com/kiagnose/kiagnose/compare/2f650ceb260d497cb2cbb792f05079b2ff7fc06f..544b760105e02b5069432c3d0fd4c733e2549c2e)

2022-09-13 10:22 UTC, orelmisan reviewed
Thank you for the changes @RamLavi.
Please see the inline comments.

2022-09-13 10:22 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.succeeded":                     fmt.Sprintf("%t", true),
nit:
```suggestion
			"status.succeeded":                     strconv.FormatBool(true),
```

2022-09-13 10:22 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			FailureReason: []string{"some reason"},
Please consider testing more than one failure reason, so we will know that the conversion is performed correctly, for example:
```go
FailureReason: []string{"some reason", "some other reason"},
```

2022-09-13 10:22 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.succeeded":     fmt.Sprintf("%t", false),
nit:
```suggestion
			"status.succeeded":     strconv.FormatBool(false),
```

2022-09-13 10:25 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			FailureReason: []string{"some reason"},
I think it should come as an additional test. WDYT?

2022-09-13 13:21 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			FailureReason: []string{"some reason"},
why not

2022-09-13 13:22 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.succeeded":     fmt.Sprintf("%t", false),
Done

2022-09-13 13:24 UTC, RamLavi commented
@orelmisan fixes [here](https://github.com/kiagnose/kiagnose/compare/544b760105e02b5069432c3d0fd4c733e2549c2e..540dab940319771c995daa656abc696b544a5fa8)

2022-09-13 14:32 UTC, orelmisan requested changes

2022-09-13 14:32 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason":                 "",
Please move the constants from `reporter.formatStatus()` to the top of the file `reporter.go`, export them and use them here.

2022-09-13 14:32 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason": "some reason",
Same

2022-09-13 14:32 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason": "some reason, some other reason",
Same.

2022-09-13 14:40 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason":                 "",
This change will make this file consistent with the framework's [reporter tests](https://github.com/kiagnose/kiagnose/blob/main/kiagnose/internal/reporter/reporter_test.go).

2022-09-14 05:44 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason":                 "",
I don't see a value in exporting these consts only for test in this particular case. 
this test should document what we expect to see. the way we format it, it not the issue tested.

2022-09-14 05:45 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason": "some reason",
same answer

2022-09-14 05:45 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason": "some reason, some other reason",
same answer

2022-09-14 05:53 UTC, orelmisan approved these changes

2022-09-14 06:18 UTC, EdDev reviewed
I had only small comments to add.

>  vm-latency, reporter: Add conversion test 

I think this commit needs reasoning. From the subject line, it is not clear what was missing.
A sentence or two would be nice, explaining why this change was needed.

2022-09-14 06:18 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +func newConfigMapClientStub(failUpdateConfigMap error) *configMapClientStub {
I tend to agree it adds nothing useful.
If you take into account it is a test, can enter a single line and avoids the need to pass an explicit `nil` as input, not having this is a plus IMO.

2022-09-14 06:18 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
nit: Can this be an one-liner?

2022-09-14 06:18 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	t.Run("on checkup failure", func(t *testing.T) {
nit: Can you separate the new test (from the previous one) with a newline?

2022-09-14 06:18 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			FailureReason: []string{"some reason"},
It would be better if the correlated data of the reason (`"some reason"`) is expressed as a const and used as input and output expectation.

2022-09-14 06:18 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			FailureReason: []string{"some reason", "some other reason"},
same, correlate the input and the output by placing these as constants.

2022-09-14 06:18 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	c.configMapData = data
Isn't this operation makes the factory initialization of the map redundant (line 134)?

2022-09-14 06:18 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
This seems to repeat as a common setup. Consider moving it directly under `TestReportShouldSuccessfullyConvertResultValues` before the sub-tests are called.

2022-09-14 06:57 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		testClient := newConfigMapClientStub(nil)
how about 
```suggestion
		var updateConfigMapErr error
		testClient := newConfigMapClientStub(epdateConfigMapErr)
```

2022-09-14 07:01 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		testClient := newConfigMapClientStub(nil)
It could make one think we actually inject the error.

2022-09-14 07:04 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
yep :)

2022-09-14 07:05 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	t.Run("on checkup failure", func(t *testing.T) {
Done

2022-09-14 07:08 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			FailureReason: []string{"some reason"},
Added
```
	const (
		someFailureReason      = "some reason"
		someOtherFailureReason = "some other reason"
	)
```

2022-09-14 07:15 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
didn't know it's possible :)
Done

2022-09-14 07:15 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			FailureReason: []string{"some reason", "some other reason"},
Done

2022-09-14 07:17 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	c.configMapData = data
yep. nice catch :)

2022-09-14 07:19 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		testClient := newConfigMapClientStub(nil)
My solution is [this](https://github.com/kiagnose/kiagnose/pull/156#discussion_r970344846).
But if you want to keep it, then `var noError error` is what I meant.

2022-09-14 07:20 UTC, RamLavi commented
@EdDev fixed [here](https://github.com/kiagnose/kiagnose/compare/540dab940319771c995daa656abc696b544a5fa8..940c721287312d2af6b5fe12af65e9ced5884fcb)

2022-09-14 07:27 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
I do not see it changed.
I would suggest not to resolve conversations before getting the commenter ack, it will make it easier to track it and not assume resolution prematurely.

2022-09-14 07:27 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	c.configMapData = data
Which in turn makes the whole factory redundant IMO.

2022-09-14 07:29 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
It is not always possible. If the tests mutate the objects in a way it interferes, then it is not possible.

2022-09-14 08:01 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
Please note that these are shared between tests (the tests that comes after the first test do not receive a fresh object).
Maybe consider:
```go
var testClient configMapClientStub
var testReporter *reporter.Reporter

setup := func() {
	testClient = newConfigMapClientStub(updateConfigMapErr)
	testReporter = reporter.New(testClient, testNamespace, testConfigMapName)
}
```

and than call `setup()` in the beginning of each test.

2022-09-14 08:02 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		)
ACK :)

2022-09-14 08:07 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	c.configMapData = data
I won't insist but I think it improves readability.. tell me if you feel strongly against it.

2022-09-14 08:08 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason": someFailureReason + ", " + someOtherFailureReason,
I don't think it's important how we set the string, as long as it is as expected.

2022-09-14 08:09 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
usually I would concur, but in this case (as was already discussed in previous comments) I don't think it's necessary to use a setup function.

2022-09-14 08:12 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason": someFailureReason + ", " + someOtherFailureReason,
My suggestion supports concatenation of arbitrary number of failure reasons.
Its not critical at the moment, thus marked as a nit.

2022-09-14 08:13 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
I am against setting test objects (client, reporter, etc..) as globals they are prone to bugs, as the test suite grows and more tests are added it's harder to follow and it makes the reader search where they are initialized and what kind of magic setup() does.
Also, once a test requires a slightly different setup, `setup()` will require a change or removal (when it won't fit all tests).

2022-09-14 08:16 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	c.configMapData = data
I do won't insist, but I have trouble agreeing with your argument.
I do not think you gain anything by using a function.

Lets compare:
`newConfigMapClientStub(nil)`
vs
`&configMapClientStub{}`

`newConfigMapClientStub(UpdateConfigMapErr)`
vs
`&configMapClientStub{failUpdateConfigMap: UpdateConfigMapErr}`

2022-09-14 08:19 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
It is not global, it is limited to the specific tests that have been added here and these do not need different objects.
They are also very close to each other.

I have no string feeling to any other the options.

2022-09-14 08:22 UTC, RamLavi commented
@EdDev fixed [here](https://github.com/kiagnose/kiagnose/compare/05d91add5df9f8fe0e138f6ca7e6974d4dac003e..9eaff975ddb6db29faeace0a0ff7e3a1af4382b5)

2022-09-14 08:47 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		testClient := newConfigMapClientStub(noError)
I have considered. my conclusion hasn't changed.

2022-09-14 08:51 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		testClient := newConfigMapClientStub(noError)
There have been 2 other conversations this has been the subject of.
Please continue the discussion there, there is no need to open a 3rd one now.

2022-09-14 09:16 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +		testClient := newConfigMapClientStub(noError)
I commented here because this is the relevant diff, no intention to make more noise.

2022-09-14 09:19 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	c.configMapData = data
Since the last thread is resolved, I am commenting here for visibility:

I think [this](https://github.com/kiagnose/kiagnose/pull/156/files/2bc06754d355f3f5f19f516da461b5b1efe40f55#diff-2d21b1780f545bd92df143499f288130aaf54c3bde3f23c77cb40c1530d3cee2R39-R40) is an example of why this function is redundant, it enforces you to use it where it's not really needed and not in the way it should be used (passing not initialized error just to make it work, not much different than specifying nil).
 
*If this is not the right thread, let me know which one is it.

2022-09-14 09:59 UTC, orelmisan commented
[Second](https://github.com/kiagnose/kiagnose/pull/156/commits/9eaff975ddb6db29faeace0a0ff7e3a1af4382b5) commit message:
> Currently the reporter does not check the values are as expected.
Added test to check that the conversion is correct.

I suggest to add:
Currently the reporter **tests** does....

2022-09-14 10:33 UTC, RamLavi commented
@orelmisan @ormergi @EdDev removed the factory function. see [here](https://github.com/kiagnose/kiagnose/compare/9eaff975ddb6db29faeace0a0ff7e3a1af4382b5..f01a05d3095036661c0540a6b22db9ace0e91b0e)
In the future let's keep these kind of discussions more to the point, and in one place.

2022-09-14 10:36 UTC, ormergi approved these changes
Thanks for the changes!

2022-09-14 10:39 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	c.configMapData = data
I removed the factory, I'm also convinced it is not needed. resolving this issue

2022-09-14 10:59 UTC, ormergi approved these changes

2022-09-14 11:01 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +			"status.failureReason":                 "",
This is not a blocker and could happen in a follow-up PR.

2022-09-14 11:03 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
> +	testReporter := reporter.New(testClient, testNamespace, testConfigMapName)
`reporter.reporter` is stateless to its not a major issue at the moment.
We could change it in a follow up PR.

2022-09-14 11:04 UTC, orelmisan approved these changes
Thank you for the changes @RamLavi.

2022-09-14 11:21 UTC, EdDev approved these changes
Raising

2022-09-14 11:22 UTC, merged