vmlatency: Use checkup UID as label value
kiagnose/kiagnose pull request #173
Opened 2022-09-20 12:00 UTC by orelmisan

Currently, the source and target VMIs have a label `latency-check-vm` with a hard-coded empty string value.
This prevents execution of multiple instances of this checkup in parallel (for more details see issue #164).

1. Add a new `CHECKUP_UID` environment variable in the API between the framework and the checkup.
2. Add the checkup's UID as the value of the "latency-check-vm" label.

To get checkup's UID:
```bash
kubectl get cm -n <target-namespace> <cm-name> -o jsonpath='{.metadata.uid}'
```

To list VMI objects by checkup's UID:
```bash
kubectl get vmis -n <target-namespace> -l latency-check-vm=<checkup-UID>
```

Depends on PR #169.
Replaces PR #171.

2022-09-21 14:22 UTC, ormergi commented
It seems that this PR now overlaps with #165 in the sense of randomizing the node affinity label.

2022-09-21 15:54 UTC, orelmisan commented
> It seems that this PR now overlaps with #165 in the sense of randomizing the node affinity label.

That is right.
This was the result of our offline discussion - instead of using the user-supplied ConfigMap name as an identifier for the checkup, use its UID.
We've also agreed that this UID shall be used as the value for the label on the VMIs.

2022-09-22 07:29 UTC, ormergi commented
> This was the result of our offline discussion - instead of using the user-supplied ConfigMap name as an identifier for the checkup, use its UID.

I mean for the last commit, where the UID is being used for the affinity label, this overlaps with this PR.

2022-09-22 08:38 UTC, RamLavi commented
the PR desc does not mention the motive. can you specify that?

2022-09-22 09:01 UTC, orelmisan commented
> the PR desc does not mention the motive. can you specify that?

From the PR description:
> Currently, the source and target VMIs have a label latency-check-vm with a hard-coded empty string value.
This prevents execution of multiple instances of this checkup in parallel (for more details see issue https://github.com/kiagnose/kiagnose/issues/164).

2022-09-22 11:14 UTC, RamLavi reviewed
I may be missing something, but where are we actually consuming this? all I see is insertion and validation. where do we add it as a the label value?

2022-09-22 11:27 UTC, orelmisan commented
> I may be missing something, but where are we actually consuming this? all I see is insertion and validation. where do we add it as a the label value?

https://github.com/kiagnose/kiagnose/pull/173/files#diff-d60aa090110dbe4421acf2db6a61ce9c88ae82264bd0e66ddc999917378b3c22R144

2022-09-22 11:58 UTC, RamLavi approved these changes
ahh, missed the last commit. 
/lgtm

2022-10-02 09:42 UTC, ormergi requested changes
I think PR should not depend on #166, it can stand on its own.
The last commit overlaps with #165, you could remove it and let #165 do the integration as we concluded offline.

2022-10-02 14:36 UTC, orelmisan commented
> I think PR should not depend on #166, it can stand on its own. The last commit overlaps with #165, you could remove it and let #165 do the integration as we concluded offline.

I believe you are referring to PR #169 and not PR #166 which was merged.
Without the refactor to `config.New()`, the linter fails because of high cyclomatic complexity.

The last commit suggests an alternative mechanism to set the value of the VMI label to the UID from the user-supplied CM, instead of generating it on the fly, as was suggested in PR #165.
This solves the [issue](https://github.com/kiagnose/kiagnose/pull/165#pullrequestreview-1113312737) raised in PR #165.

Do you have any comments regarding the code?

2022-10-03 09:55 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/251685b4590b4cea46976296c8a29c073a15a493..8d1adc108953a0c02e0775a901c12a5628d6b037): Rebase

2022-10-03 10:11 UTC, ormergi requested changes

2022-10-03 10:11 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	vmLabel := vmi.Label{Key: LabelLatencyCheckVM, Value: uid}
Please change the label name and variable name to `LabelLatencyCheckUID = "latency-check/uid"` so it describes it correctly.

2022-10-03 11:12 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/4b2406dcf1bc7230c1e3707de519a460a0d08e38..88e8593186ecdd6a525473d5d3e1c5bcf47ce18b): Rebase.

2022-10-03 11:15 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	vmLabel := vmi.Label{Key: LabelLatencyCheckVM, Value: uid}
Done.

2022-10-03 13:04 UTC, RamLavi approved these changes
/lgtm

2022-10-03 14:49 UTC, ormergi approved these changes

2022-10-05 17:48 UTC, EdDev approved these changes
I had one comment which I would have considered a blocker, but at the stage of the project, it is unlikely that we have any usage/user who can be affected.

Nevertheless, I suggest to be careful and be explicit when breaking compatibility.
It is also a good opportunity to add a section into the documentation and future designs about these scenarios.

2022-10-05 17:48 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +		return ErrInvalidCheckupUID
While this is a minor incident at this stage, this should not have been overseen:
The change breaks compatibility with the previous kiagnose core. One could have upgraded on but not the other.

At the minimum this needs to be mentioned in the change and in the changelog.
A better solution would have been to have an alternative (randomizing an UID?).
For the long run, we need to focus on such cases and provide guidelines or tooling to handle them.

2022-10-06 10:21 UTC, merged