vmlatency: Randomize VMI names
kiagnose/kiagnose pull request #202
Opened 2022-11-03 10:47 UTC by orelmisan

Currently, source and target VMI names are hard-codded. This prevents simultaneous execution of multiple checkup instances in the same namespace.

VMIs names will have a random string prefix:
`latency-check-source-<random string>`
`latency-check-target-<random string>`

Partially solves issue #164.

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-11-07 07:16 UTC, RamLavi submitted a review, later dismissed
/lgtm

2022-11-07 07:50 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/namegenerator/namegenerator.go
> +func (ngs Stub) Name(prefix string) string {
why do you put the stub here and not on each test module?

2022-11-07 08:13 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/namegenerator/namegenerator.go
> +func (ngs Stub) Name(prefix string) string {
The stub is being used at `checkup_test.go` and `launcher_test.go`.
I'm open to suggestions if you think there is a better place to put it.

2022-11-07 09:09 UTC, EdDev requested changes

2022-11-07 09:09 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/namegenerator/namegenerator.go
> +func (ngs Stub) Name(prefix string) string {
- I do not think it is common to create stubs in production code, even if it means duplication.
- I would prefer to avoid this stub completely. The information of what VMI is created is saved in the results field and can be retrieved using `Results()`. Can you use that instead to determine the name of the VMI?

2022-11-07 09:20 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/namegenerator/namegenerator.go
> +func (ngs Stub) Name(prefix string) string {
> * I do not think it is common to create stubs in production code, even if it means duplication.

I'll remove it from here.

> * I would prefer to avoid this stub completely. The information of what VMI is created is saved in the results field and can be retrieved using `Results()`. Can you use that instead to determine the name of the VMI?

This name stub is used to randomize the VMI name upon its creation.

2022-11-07 09:26 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/23bda5831a6624b8f87bd2b005a10ca6f7d6af86..8be2d31c540972459492e163422a5322faaa3775): Moved `nameGeneratorStub` to `checkup_test.go` and `launcher_test.go`.

2022-11-07 09:50 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/namegenerator/namegenerator.go
> +func (ngs Stub) Name(prefix string) string {
I do not think we are interested in testing the randomization.
And the name of the VMI you can get from the results, you do not need a stub. What am I missing here?

2022-11-07 09:56 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/namegenerator/namegenerator.go
> +func (ngs Stub) Name(prefix string) string {
> I do not think we are interested in testing the randomization.

We are not testing the randomization.

> And the name of the VMI you can get from the results, you do not need a stub. What am I missing here?

The results do not contain the VMIs names.

We use the VMIs names in order to check the pod anti affinity or node affinity.

2022-11-08 07:36 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/namegenerator/namegenerator.go
> +func (ngs Stub) Name(prefix string) string {
> The results do not contain the VMIs names.

Yes, you are right. I got confused with the checkup members.
I think you can still solve it without complicating the production code with an object (to allows stubbing in tests).
I can think now of two options:
- Add getters for the VMI/s from the checkup object.
- Take advantage of the known prefix, list the VMI/s, filter the one relevant and use it.

The second seems less intrusive and moves the work to the tests. I think that would be my favorite.

2022-11-08 11:53 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/8be2d31c540972459492e163422a5322faaa3775..693a1b02cbc8361704033b9c1d80503f1bece347): Removed `nameGenerator` dependency from checkup.

2022-11-08 12:49 UTC, EdDev reviewed
How come `go.mod` has not changed?
You added `k8s.io/apimachinery/pkg/util/rand` but I see only things removed (not added).

2022-11-08 12:55 UTC, EdDev submitted a review, later dismissed
Thanks!

2022-11-08 13:35 UTC, merged