Introduce python based e2e tests
kiagnose/kiagnose pull request #203
Opened 2022-11-03 14:49 UTC by EdDev

Introduce an E2E test suite, based on the pytest testing framework.

The tests mimics the existing `kubevirt-vm-latency` checkup e2e test which is implemented in a `bash` script.

Following changes are planned to include:
- Remove the `bash` e2e tests.
- Push the test-image to the registry and auto-build it per need (when the Dockerfile or the requirements.txt files change).

2022-11-06 09:34 UTC, ormergi commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +  e2e-test-py:
I think this job missing this step https://github.com/kiagnose/kiagnose/blob/fc5e7f757c6af9ab534fc2b82a2926383b5d7fac/.github/workflows/checkup-kubevirt-vm-latency.check.yaml#L85-L86

2022-11-06 09:52 UTC, EdDev commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +  e2e-test-py:
OMG, let me try...

2022-11-07 19:09 UTC, EdDev commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +  e2e-test-py:
Fixed this one and the emulation thing.
Done.

2022-11-22 14:36 UTC, ormergi reviewed
Very nice work!
Please see my inline comments

2022-11-22 14:36 UTC, ormergi commented on test/e2e/vmlatency/vmlatency_test.py
> +def test_successful_run(kclient, checkup_sa, checkup_deployment, nad):
nit: I would call `checkup_role_binding` and `configmap_role_binding` fixtures directly instead of `checkup_deployment`to make it easier to understand what is necessary to run a checkup.
Also, its note the actual deployment of the checkup.

2022-11-27 08:22 UTC, RamLavi requested changes
added some comments

2022-11-27 08:22 UTC, RamLavi commented on test/e2e/vmlatency/vmlatency_test.py
> +        assert "true" == data.get("status.succeeded")
Although it will be written in the printed CM, no?

2022-11-27 12:03 UTC, orelmisan reviewed
Thank you very much for the PR @EdDev.
Please see the inline comments.

2022-11-27 13:35 UTC, orelmisan commented
WDYT about moving the e2e under the vm latency directory?
They are specific to this checkup.

2022-12-01 13:15 UTC, EdDev commented
> WDYT about moving the e2e under the vm latency directory? They are specific to this checkup.

e2e tests are about testing everything.
I also prefer to see all e2e tests under a separate subtree.

I think this also correlates with other projects we work on these days (e.g. kubevirt).

2022-12-01 16:24 UTC, ormergi commented on test/e2e/conftest.py
> +def checkup_configmap_role(kclient, project_ns) -> Role:
> I think that the configmap has only one role at the moment, so I do not see what is not clear about it. This returns the role of the checkup configmap.
> 

Not clear what permissions the role grants.

> I do not mind naming it per the name, i.e. `checkup_configmap_access_role`, but I think it is a nit not worth discussing further. If you want me to change it to the option above, let me know here.
> 

Yes it's a nit I also mentioned it.
I don't like the option above, one might think it enables reading only, this is why I suggested that name at my first comment.

> > to help the reader understand what it enables.
> 
> The reader does not need to understand the details, just to know it needs a role for the configmap. What this role includes is an implementation detail, which one may want to delve in or not.

What the role include is what is interesting and it's not an implementation details its mandatory for the checkup to work.

2022-12-01 16:46 UTC, EdDev commented on test/e2e/conftest.py
> +def checkup_configmap_role(kclient, project_ns) -> Role:
> What the role include is what is interesting and it's not an implementation details its mandatory for the checkup to work.

I disagree. As someone that writes a new test, I do not need to know what are these permissions, it is part of the test tooling and it allows the test author to need to know less.

2022-12-06 11:44 UTC, RamLavi approved these changes
/lgtm

2022-12-07 07:44 UTC, ormergi commented on test/e2e/vmlatency/conftest.py
> +def checkup_role(kclient, project_ns) -> Role:
I guess I got it wrong.

2022-12-07 07:58 UTC, ormergi commented on test/e2e/vmlatency/conftest.py
> +    return NetworkAttachmentDefinition(
I find it confusing, to represent already created objects in tests, what you think about using the name and namespace of the tests net-attach-def directly where necessary?

If you are going to keep it, could you please change the name to `network_attachmetn_definiton`?

2022-12-07 07:58 UTC, ormergi commented on test/e2e/vmlatency/vmlatency_test.py
> +            attempt_timeout = timeout / attempts
I am not sure which intermediate steps there are for a job, the end results are pretty much the same as what I tested.
Maybe increasing the timeout would do.

Anyway, eventough it was usful when developing I think it should be removed so it's not an integral part of the test.

2022-12-07 07:58 UTC, ormergi commented on test/e2e/vmlatency/vmlatency_test.py
> +    with resource_dump(config_map) as cm:
Is is possible to define an object for the config-map (e.g: checkup-config-map) and have the `resource_dump` logic as part of it similar to job.py?

I think it would make the code easier to understand and reuse.

2022-12-07 07:58 UTC, ormergi commented on test/e2e/vmlatency/vmlatency_test.py
> +def test_successful_run(kclient, checkup_sa, checkup_role_binding, configmap_role_binding, nad):
nit: nad --> net_attach_def

2022-12-07 08:21 UTC, EdDev commented on test/e2e/vmlatency/conftest.py
> +    return NetworkAttachmentDefinition(
As someone that writes a test, I do not think I need to know if it is actually created by the fixture or it returns a representation of it.
At the test layer, you are not suppose to care.
If the actions will move to the test code itself, then this can be adjusted here without touching a single test, that is in my view a good abstraction.

Regarding the name, I think this is nitpicking. We all use the alias NAD and no one is getting confuse over it. Having a long name will not make it any clearer IMO.
But if it will keep bothering you, I won't object if you send a PR to change it.

2022-12-07 08:21 UTC, EdDev commented on test/e2e/vmlatency/vmlatency_test.py
> +def test_successful_run(kclient, checkup_sa, checkup_role_binding, configmap_role_binding, nad):
This has been already commented on the fixture name itself.

2022-12-07 08:21 UTC, EdDev commented on test/e2e/vmlatency/vmlatency_test.py
> +    with resource_dump(config_map) as cm:
`resource_dump` is generic to all namespaced resources.
If it will be used in other test files, it can be promoted to a more common location.

At this stage, I think anything beyond this is a premature improvement.

2022-12-07 08:21 UTC, EdDev commented on test/e2e/vmlatency/vmlatency_test.py
> +            attempt_timeout = timeout / attempts
if there is a problem, we will see no changes until it is too late.
We are interested in seeing intermediate updates to the report in order not to miss them.

I guess the most appropiate solution to this is the use of a watcher.
If I am not mistaken, it was added recently to the lib so we could use it instead of this approach.

Anyway, I prefer not to invest in this now.

2022-12-07 09:59 UTC, EdDev commented
change: Rebase to trigger the CI before merging.

2022-12-07 10:57 UTC, ormergi commented on test/e2e/vmlatency/vmlatency_test.py
> +            attempt_timeout = timeout / attempts
What do you mean by "intermediate updates to the report"?

I think we already get enough information from the job log that is exported.

2022-12-07 11:05 UTC, EdDev commented on test/e2e/vmlatency/vmlatency_test.py
> +            attempt_timeout = timeout / attempts
We do not get information from the VMIs, Pods etc... See what we print on each attempt under `teardown_logging`.
There is a good chance that at some point in time, these are already gone and we have nothing to debug with.

2022-12-07 11:15 UTC, ormergi commented on test/e2e/vmlatency/vmlatency_test.py
> +    with resource_dump(config_map) as cm:
I think that having it generic at this point is some kind of premature improvement, it would make it easier to understand if it was similar to the job object.
Not insisting on it.

2022-12-07 11:35 UTC, RamLavi approved these changes
/lgtm

2022-12-07 12:15 UTC, ormergi approved these changes
Thanks for the changes

2022-12-07 12:58 UTC, orelmisan approved these changes
Thank you for the changes @EdDev

2022-12-07 12:58 UTC, orelmisan commented on test/e2e/vmlatency/job.py
> +    with Job(
The checkup Job now contains a security context which is not present here.
Currently the kind cluster is not forcing the security policy, so we can add it in a follow-up PR.

2022-12-07 13:02 UTC, merged