cmd: Add main function
kiagnose/kiagnose pull request #21
Opened 2022-04-18 08:51 UTC by orelmisan

This adds a main function to kiagnose.
This is a required step in order to build an image.

2022-04-18 09:54 UTC, EdDev reviewed
Thanks, nice and simple.

We need in the same PR the CI coverage as well.
That means:
- Scripts executing the build.
- CI running the script (build).

2022-04-18 09:54 UTC, EdDev commented on kiagnose/cmd/main.go
> +	"github.com/kiagnose/kiagnose/kiagnose/internal/environment"
This is not suppose to compile. The whole point of having `internal` was to make sure no one can do this.

Anyway, I do not think it deserve to exist there, it can be placed in the cmd IMO and does not require direct testing as (almost) no logic is involved. If you still think it is worth having the unit tests, then just place them under `kiagnose` with the code.

2022-04-18 09:54 UTC, EdDev commented on kiagnose/cmd/main.go
> +		log.Fatalln(err.Error())
Maybe you should add some high level description that `kiagnose` execution failed.

2022-04-18 09:56 UTC, EdDev commented on kiagnose/internal/environment/environment.go
> +		splitKeyValue := strings.Split(entry, "=")
I think there is a need to check that it of len 2, otherwise return an error or just ignore.

2022-04-18 10:12 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/556e84e6a0ae5be5ed88d47a5b1ee017dece36e5..98b9020aa0e0837fb88eec2a7ac839d24acbd7d5): Answered code review comments.

2022-04-18 10:15 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/98b9020aa0e0837fb88eec2a7ac839d24acbd7d5..fee2f67a86259fbde912610b88d12470aa347601): Removed magic number.

2022-04-18 10:16 UTC, orelmisan commented on kiagnose/internal/environment/environment.go
> +		splitKeyValue := strings.Split(entry, "=")
Done.

2022-04-18 10:18 UTC, orelmisan commented on kiagnose/cmd/main.go
> +		log.Fatalln(err.Error())
I've added a description with the following format:
`$PROGRAM_NAME had failed: $ERR_DESCRIPTION`
Does that works for you?

2022-04-18 10:19 UTC, orelmisan commented on kiagnose/cmd/main.go
> +	"github.com/kiagnose/kiagnose/kiagnose/internal/environment"
Removed `environment_test.go`.
Moved `environment.go` under `cmd`.

2022-04-18 15:15 UTC, EdDev requested changes
Nice.

The reason it fails is because it tried to run checks that it should not.
Just need to fix the default condition:
```diff
-if  [ -z "${OPT_LINT}" ] && [ -z "${OPT_UNIT_TEST}" ]; then
+if  [ -z "${OPT_LINT}" ] && [ -z "${OPT_UNIT_TEST}" ] && [ -z "${OPT_BUILD_CORE}" ]; then
     OPT_LINT=1
     OPT_UNIT_TEST=1
+    OPT_BUILD_CORE=1
 fi
 ```

2022-04-18 15:15 UTC, EdDev commented on automation/make.sh
> +        BUILD_CORE=1
Lets keep the same format pattern: `OPT_BUILD_CORE`

2022-04-18 15:15 UTC, EdDev commented on .github/workflows/check.yaml
> +        version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
I think we should be ok with a single version. WDYT?
We already check the unit tests with multiple version of golang, so I do not think we need this one checked as well.

2022-04-19 04:38 UTC, EdDev commented
Here are the changes needed:

- https://github.com/kiagnose/kiagnose/pull/23/commits/aeb669039f15b6947f1a00bd342d49cebbf1bf29
- https://github.com/kiagnose/kiagnose/pull/23/commits/729642cb03537ecfce7283bd8f69673b51002397#diff-78ef9dc8d6ce0002e26fc4adde9d00123acd7a7c214da456a828814850c7d9e2R57-R64

2022-04-19 06:39 UTC, ormergi reviewed
Nice work

2022-04-19 06:39 UTC, ormergi commented on kiagnose/cmd/main.go
> +		log.Fatalf("%s had failed: %v", os.Args[0], err)
Why is it necessary to pass `os.Args[0],` cant we print "kiagnose exit with an error" or something like that?

2022-04-19 06:39 UTC, ormergi commented on automation/make.sh
> +        BUILD_CORE=1
Note that this script run all the operations it provides when no args are being passed to it.
I think it should be initialized so it will be run by default when no args are being passed,
similar to `OPT_LIST`  and `OPT_UNIT_TEST`.

2022-04-19 06:39 UTC, ormergi commented on automation/make.sh
> +    --build-core)
Until we have other stuff to build I think you can call it just `build`.

2022-04-19 06:39 UTC, ormergi commented on .github/workflows/check.yaml
> +  build:
Note that when running unit tests it also build the code, unless we use the binary (building a container the runs the binary for example) I dont think we need another Github action.

2022-04-19 07:00 UTC, orelmisan commented on automation/make.sh
> +        BUILD_CORE=1
Done.

2022-04-19 07:02 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/7deae5a565eea52f20145b2cf33c63bc03e06f0b..1517af07dc70c8dbc94307da26d3d9c94d208d74): Answered code review comments.

2022-04-19 07:05 UTC, orelmisan commented on kiagnose/cmd/main.go
> +		log.Fatalf("%s had failed: %v", os.Args[0], err)
It gives us the flexibility of not hard coding it.

2022-04-19 07:07 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/1517af07dc70c8dbc94307da26d3d9c94d208d74..b197242d7953ff71e7b194c3bc1004dcdd8340e3): Changed .github/workflows/check.yaml according to https://github.com/kiagnose/kiagnose/commit/729642cb03537ecfce7283bd8f69673b51002397#diff-78ef9dc8d6ce0002e26fc4adde9d00123acd7a7c214da456a828814850c7d9e2R57-R64

2022-04-19 07:11 UTC, orelmisan commented on automation/make.sh
> +        BUILD_CORE=1
Done.

2022-04-19 07:11 UTC, orelmisan commented on automation/make.sh
> +    --build-core)
We have an image to build on PR #22 .

2022-04-19 08:56 UTC, EdDev commented on .github/workflows/check.yaml
> +  build:
It does not build `main`.
If we will have a step that includes it, we can adjust as needed.

2022-04-19 08:58 UTC, EdDev submitted a review, later dismissed
Thanks!

2022-04-19 08:58 UTC, EdDev commented
@orelmisan , please rebase.

2022-04-19 09:00 UTC, orelmisan commented
Change: Rebase.

2022-04-19 09:07 UTC, EdDev approved these changes
Thank you!

2022-04-19 09:07 UTC, merged