vmlatency, checkup: Add OwnerReference to VMIs
kiagnose/kiagnose pull request #211
Opened 2022-11-13 10:28 UTC by orelmisan

Add OwnerReference to source and target VMIs, in order to garbage-collect them when the user-supplied ConfigMap is deleted.

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-11-13 10:43 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/a87e120685c5237f5c445616382f85121bb023d1..41cee3b1cf6c5fe71c168e79b75d754961609410): Updated commit message and PR description

2022-11-13 11:20 UTC, ormergi requested changes
@orelmisan how did you verify that it actually works? (I am asking because we don't have e2e tests yet).

2022-11-13 11:20 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		vmi.WithOwnerReference(uid, configMapName),
nit: Please more it to be the first option of the builder (line 134).

2022-11-13 11:20 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +func New(c vmi.KubevirtVmisClient, uid, namespace, configMapName string, params config.Config, checker checker) *checkup {
Please consider renaming `configMapName` field to something like `owner`/`ownerName`/`ownerObject`.
Having it like that is a bit confusing and doesn't help me understand that the owner is the checkup config-map (it can be understood from mainflow.go line 55).

2022-11-13 11:51 UTC, orelmisan commented
> @orelmisan how did you verify that it actually works? (I am asking because we don't have e2e tests yet).

I've tested it locally:
1. Disabled the teardown.
2. Listed the VMIs to see they are still there.
3. Removed the user-supplied ConfigMap,
4. Listed the VMIs to see they are removed.

2022-11-13 11:53 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +func New(c vmi.KubevirtVmisClient, uid, namespace, configMapName string, params config.Config, checker checker) *checkup {
The problem is that the owner'st kind is hard-codded to "ConfigMap".
So it will look weird IMO.

2022-11-13 11:54 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		vmi.WithOwnerReference(uid, configMapName),
Done.

2022-11-13 14:25 UTC, orelmisan commented
Change: Get the ownerReference as an input to checkup.New(), so checkup will not care what object is in the owner reference.
@ormergi could you please take another look?

2022-11-13 14:29 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +func New(c vmi.KubevirtVmisClient, uid, namespace, configMapName string, params config.Config, checker checker) *checkup {
This parameter was removed.

2022-11-13 14:30 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/c2a5782482675395b93ddf209a0c95e0901719ab..7480c40cd29cf9d66ab29e3eda9bc1f4a56ede7e): Removed unused explicit field initialization.

2022-11-13 14:35 UTC, ormergi submitted a review, later dismissed
Thanks for the changes, nice work!

With this change, we won't need to worry about leftovers when we will introduce the "retain" flag for debugging as the VMs will be deleted once the config-map is deleted.

2022-11-14 08:18 UTC, RamLavi approved these changes
/lgtm

2022-11-14 10:56 UTC, ormergi requested changes
I prefer how it was before, the UID should be explicitly defined in the checkup object.
Taking it from another object is actually moving the responsibility of the UID to the checkup.

Also, IMO having the code more compact doesn't worth it in this case.
The amount of parameters you need to pass to functions (`checkup.New` and `newLatencyCheckVmi`) is reduced but it doesn't improve readability.

2022-11-14 11:22 UTC, orelmisan commented
> I prefer how it was before, the UID should be explicitly defined in the checkup object.
Taking it from another object is actually moving the responsibility of the UID to the checkup.

> Also, IMO having the code more compact doesn't worth it in this case.
The amount of parameters you need to pass to functions (checkup.New and newLatencyCheckVmi) is reduced but it doesn't improve readability.

The UID is used in two places:
1. OwnerReference.
2. Value of the label that is used for podAntiAffinity.

Why is it important to explicitly get it?
The value is the same.

Several interfaces where cleaned, why is it a bad thing in your opinion?

2022-11-14 16:00 UTC, orelmisan commented
Rebase

2022-11-16 09:49 UTC, EdDev requested changes

2022-11-16 09:49 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +	ownerReference := metav1.OwnerReference{
I would like to move the mainflow skeleton to the kiagnose package so it can serve other checkups.
By adding this ownership here, it will cause the skeleton to be too specific and not generic. Using the configmap as the owner is not always correct, I can think of other checkup authors that will prefer to do something completely different.

As this is specific to a checkup, I think you should move this to the checkup itself to do.
If you need to place additional info for the checkup to compose this configuration, add it to the config struct, which is checkup specific.

2022-11-16 09:56 UTC, EdDev commented
> > I prefer how it was before, the UID should be explicitly defined in the checkup object.
> > Taking it from another object is actually moving the responsibility of the UID to the checkup.
> 
> > Also, IMO having the code more compact doesn't worth it in this case.
> > The amount of parameters you need to pass to functions (checkup.New and newLatencyCheckVmi) is reduced but it doesn't improve readability.
> 
> The UID is used in two places:
> 
>     1. OwnerReference.
> 
>     2. Value of the label that is used for podAntiAffinity.
> 
> 
> Why is it important to explicitly get it? The value is the same.
> 
> Several interfaces were cleaned, why is it a bad thing in your opinion?

The cleanup came on the expense of an nontrivial dependency.
The skeleton has explicitly used the UID of the configmap, but it is a generic decision.
The suggested change says that the UID used is up to the checkup package (not the mainflow skeleton) itself to decide and the decision is to take it from the owner object.

Considering that other checkups will be written, we can either provide a default UID (of the configmap) through a skeleton lib or not provide one at all. If we provide it, the checkup writer could still override it.
If we will not provide it, it means the responsibility is completely on the checkup writer and we cannot assist her with this thing.

I prefer we do provide the UID from above explicitly, and it is up to the specific checkup to use it or use something else.

And as I commented before, the owner object as an input is the real problem IMO.

2022-11-17 12:39 UTC, orelmisan commented
In an offline meeting with @EdDev we've concluded that its more logical to use the checkup's Job underlying Pod as the owner, because it is most probably be removed, unlike the user-supplied ConfigMap which could linger.

One option discussed to get the Pod's name and UID is using downward API as environment variables.

2022-11-21 08:41 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/db9c910cc4070f6aee0474b906a0d68128b8baaf..cdf8aa3d1eeae5150015f7d0561e44622f8a190b): Create the ownerReference inside the checkup, based on the Pod's UID and name.

[Change 2](https://github.com/kiagnose/kiagnose/compare/cdf8aa3d1eeae5150015f7d0561e44622f8a190b..4a5303a56274b58575f130d23d81f102fad5db6f): Added a test to check that ownerReference is not created when Pod's UID is unknown.

2022-11-22 11:48 UTC, EdDev reviewed
Second commit:
> in order to get the Pod's name

I guess you meant ID not name, right?

2022-11-22 11:58 UTC, orelmisan commented
> Second commit:
> 
> > in order to get the Pod's name
> 
> I guess you meant ID not name, right?

Yes, thank you.

2022-11-22 12:00 UTC, orelmisan commented
Changed the [second](https://github.com/kiagnose/kiagnose/pull/211/commits/3f891dddc8988e368c0d8139e650edeb0ffbc003) commit's message in order to answer @EdDev's [comment](https://github.com/kiagnose/kiagnose/pull/211#pullrequestreview-1189901802).

2022-11-22 12:16 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +	ownerName := environment.PodName(env)
I would have prefered this to come in through the `cfg`, which is specific to the checkup.

Can we add it to the baseConfig? Then it will pass to the checkup config which may or may not make use of it.
WDYT?

2022-11-22 13:02 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +	ownerName := environment.PodName(env)
We could add it to the base config.
It would require some changes to the `config.go` file in kiagnose and to `config.New()` in the checkup.

2022-11-24 11:53 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +	ownerName := environment.PodName(env)
I've published PR #224 to complete the changes required to answer this comment.

2022-11-24 15:10 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/55b61f7859324ddd7fd1ed140cd11cadd9c146c3..915c45878630e1dca5e8f2b431066932b5a0b556): Inserted the Pod's name and UID to the checkup's config.
This is an answer to @EdDev's [comment](https://github.com/kiagnose/kiagnose/pull/211#discussion_r1029256028).

2022-11-24 15:21 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/b49b0ae055e767435fdfa29c6653615c234e6078..a4969656ecf9576a8a62ed871f5c41c81b817d00): Aligned the order of the Pod name and UID to be uniform.

2022-11-24 15:27 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/a4969656ecf9576a8a62ed871f5c41c81b817d00..ef5ed4f05d719aaff47cda075d50bf7b78155bb1): Fixed a bug in `TestCheckupSetupShouldNotCreateOwnerReferenceWhenPodUIDIsEmpty()`.

2022-11-28 07:46 UTC, EdDev approved these changes
Very nice, thank you!

2022-11-28 07:46 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	PodUID                               string
nit: I think the conversion to `types.UID` should have been already been done here.

Not that critical though.

2022-11-28 07:48 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	PodUID                               string
I'll create a follow-up PR.
Thanks.

2022-11-28 07:48 UTC, merged