vmlatency:  Align 'spec' and 'status' field names format
kiagnose/kiagnose pull request #228
Opened 2022-11-29 17:08 UTC by ormergi

Currently, the status fields and params fields are in different formats, params fields are snake case and the status fields are camel case.

Change the params fields to be aligned with status fields camel case format, its common format in k8s eco-system.

The current changes do not remove the old form parameters completely and they **can** be used.
The old form parameters should be removed when deprecated completely.

2022-11-29 17:20 UTC, orelmisan reviewed
Thank you for the PR @ormergi.
Could you please update the following files to use the new API?
`checkups/kubevirt-vm-latency/automation/e2e.sh`
`checkups/kubevirt-vm-latency/README.md`

2022-11-30 08:52 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	"reflect"
Is it possible to implement this functionality without the usage of advanced language features such as reflection and generics?

2022-11-30 09:29 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	"reflect"
See the first commit, it doesn't include reflection usage.

2022-11-30 09:40 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	}
Maybe we could do use setters and call them twice:
1. With the new API.
2. With the old API.

```go
func (c *Config) SetNetworkAttachmentDefinitionName(rawNetworkAttachmentDefinitionName string) {
    if c.NetworkAttachmentDefinitionName != "" {
        return
     }
     c. NetworkAttachmentDefinitionName = NetworkAttachmentDefinitionName
}
```


And then call it:
```go
c.SetNetworkAttachmentDefinitionName(NetworkNameParamName)
c.SetNetworkAttachmentDefinitionName(NetworkNameDeprecatedParamName)
```

WDYT?

2022-11-30 10:15 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	}
Please note that the parameters are taken from `baseConfig` map.

2022-11-30 10:20 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	"reflect"
Using advanced language features is not a bad thing, sometimes we use them w/o even noticing :slightly_smiling_face: 

The main idea in the second commit is to use reflections to dynamically construct the config object according to a list of parameters we intent to support.
It enables adding or removing parameters w/o changing the logic (controlled by the parameters list).

2022-11-30 10:40 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	}
Yes, my bad:
```go
c.SetNetworkAttachmentDefinitionName(baseConfig.Params[NetworkNameParamName])
c.SetNetworkAttachmentDefinitionName(baseConfig.Params[NetworkNameDeprecatedParamName])
```

2022-12-04 16:30 UTC, ormergi commented
> Thank you for the PR @ormergi. Could you please update the following files to use the new API? `checkups/kubevirt-vm-latency/automation/e2e.sh` `checkups/kubevirt-vm-latency/README.md`

Done

2022-12-05 09:47 UTC, ormergi commented
Rebased

2022-12-05 15:02 UTC, orelmisan reviewed
Thank you for the changes @ormergi.

2022-12-06 07:40 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	"reflect"
> Thus IMO, there is no need to have an advanced code to constantly support it.

@orelmisan the changes that make use of `reflect` controllers the checkup parameters (what parameters there are and how they will be parsed), it is meant to stay regardless of the deprecation period of the parameters.

2022-12-06 07:41 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	"reflect"
> Thus IMO, there is no need to have an advanced code to constantly support it.

@orelmisan the changes that make use of `reflect` controllers the checkup parameters (what parameters there are and how they will be parsed), it is meant to stay regardless of the deprecation period of the parameters.

2022-12-06 07:42 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	"reflect"
>Thus IMO, there is no need to have an advanced code to constantly support it.

@orelmisan the changes that make use of reflect controllers the checkup parameters (what parameters there are and how they will be parsed), it is meant to stay regardless of the deprecation period of the parameters.

2022-12-06 07:44 UTC, ormergi commented
> Thus IMO, there is no need to have an advanced code to constantly support it.

@orelmisan the changes that make use of reflect controllers the checkup parameters (what parameters there are and how they will be parsed), it is meant to stay regardless of the deprecation period of the parameters.

2022-12-06 07:59 UTC, ormergi commented
I moved the second commit to its own PR https://github.com/kiagnose/kiagnose/pull/229

2022-12-06 09:09 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +			SampleDurationSecondsDeprecatedParamName, SampleDurationSecondsParamName)
Done

2022-12-06 11:23 UTC, RamLavi submitted a review, later dismissed
/lgtm

2022-12-06 12:04 UTC, EdDev requested changes

2022-12-06 12:04 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +			SampleDurationSecondsDeprecatedParamName, SampleDurationSecondsParamName)
Duplicating here the check seems wrong to me.
If we take advabtage of the prev suggestion, then:
```go
value := readConfig(baseConfig.Params, SampleDurationSecondsDeprecatedParamName, SampleDurationSecondsDeprecatedParamName)
if sampleDuration, err = strconv.Atoi(value); err != nil {
    return Config{}, fmt.Errorf("%q parameter is invalid: %v", SampleDurationSecondsParamName, err)
}
```

2022-12-06 12:04 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	} else if value, exists := baseConfig.Params[DesiredMaxLatencyMillisecondsDeprecatedParamName]; exists {
Same

2022-12-08 07:21 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +const (
Done

2022-12-08 07:21 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +			SampleDurationSecondsDeprecatedParamName, SampleDurationSecondsParamName)
Done

2022-12-08 07:22 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	}
@orelmisan I have changed the code to have the check more generic following another review, please take another look.

2022-12-08 07:22 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	}
Done

2022-12-08 07:22 UTC, ormergi commented
@EdDev @orelmisan please take another look.

2022-12-08 07:36 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	} else if value, exists := baseConfig.Params[DesiredMaxLatencyMillisecondsDeprecatedParamName]; exists {
Donw

2022-12-08 07:48 UTC, EdDev approved these changes
Thank you!

I will not block this on not changing thenew  e2e tests accordingly, but note that this means it is not really complete until it is done. Please consider to add a follow up PR with the needed changes.

We should soon deprecate the script tests in favor of the pytest one.

2022-12-08 07:48 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +const (
nit: I think you could have commented the whole block once.

2022-12-08 07:50 UTC, RamLavi approved these changes
/lgtm

2022-12-08 07:57 UTC, orelmisan approved these changes
Thank you @ormergi.

2022-12-08 08:02 UTC, merged