Update CHANGELOG
kiagnose/kiagnose pull request #245
Opened 2023-03-01 11:21 UTC by orelmisan

Update the CHANGELOG with v0.3.0 release notes.

Depends on PR #244.

2023-03-01 15:36 UTC, EdDev requested changes
We should merge this CHANELOG from the 0.2 branch, to see a linear version history.

2023-03-02 07:26 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/a4917b49000a52e41f0fa046caca2f0046ca9874..c0bb8d8d8dc50a691504e496c3ccf883820246d9): Added version history from the 0.2 branch.

2023-03-02 07:27 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/c0bb8d8d8dc50a691504e496c3ccf883820246d9..5143c6b8f1f2aa6c22dcfccd9a2623d94486b629): Rebase

2023-03-02 07:33 UTC, EdDev commented on CHANGELOG
> + - VM latency checkup is now running as a standalone application and using Kiagnose packages as a library
Can you just list here the diff from the last release? Some things here repeat from the ones below.

2023-03-02 07:38 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/5143c6b8f1f2aa6c22dcfccd9a2623d94486b629..404220d4eebdbcdbc95db3b00f5333f9c5aced8a): Removed from v0.3.0 items that were previously mentioned in v0.2.x.

2023-03-02 07:38 UTC, orelmisan commented on CHANGELOG
> + - VM latency checkup is now running as a standalone application and using Kiagnose packages as a library
Done.

2023-03-02 07:41 UTC, EdDev approved these changes
Thanks!

2023-03-02 07:49 UTC, merged