Start and wait for a checkup Job to finish
kiagnose/kiagnose pull request #27
Opened 2022-04-19 13:02 UTC by ormergi

This PR introduce the logic for actually executing a checkup in a cluster.

With this PR changes the framework will create a batch Job to run the checkup image
and waits for it to finish.

A Job is considered as finished when its status has 'Completed' or 'Failed' condition.

2022-04-19 13:28 UTC, orelmisan reviewed
Thank you for the PR @ormergi.
Please see the inline comments for the first commit.

2022-04-19 13:28 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +		{description: "with no addition env vars"},
*additional

2022-04-19 13:28 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +func TestCheckupRunShouldCreateJob(t *testing.T) {
nit: Please consider changing this function's name to `TestCheckupRunShouldCreateAJob`

2022-04-19 13:28 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +func TestCheckupRunShouldFailWhen(t *testing.T) {
Is it possible to simulate the following errors using the fake client?
1. Failure to fetch the image.
2. Checkup exiting with a non zero exit code.

Do we want to simulate these kinds of errors in the unit tests?

2022-04-19 13:42 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +		{description: "with no addition env vars"},
Done

2022-04-19 13:44 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
>  	return nil
I guess that this will be the integration point with the component that will read the checkup results from the results ConfigMap.
We need to think on which errors can we try to read the results.

2022-04-19 13:44 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +			assert.NoError(t, testCheckup.Run())
How is the checkup running successfully without the `Setup()`?

2022-04-19 13:44 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +		assert.ErrorContains(t, testCheckup.Run(), expectedErr)
How is the checkup running without calling setup()?

2022-04-19 13:44 UTC, orelmisan commented on kiagnose/internal/checkup/job/job.go
> +	jobWatcher, err := client.Jobs(job.Namespace).Watch(context.Background(), metav1.ListOptions{LabelSelector: jobLabel})
Can you please consider using an informer?
It should have an advantage over raw watch, for example it can recover from a momentary communication failure.

2022-04-19 13:47 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +func TestCheckupRunShouldFailWhen(t *testing.T) {
Can we differentiate between these problems?

2022-04-20 14:49 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/f7331e95b4d7953b82ffc44cea0ed81a823eadc4..dba2c4e0f011978ffff344c657f8efd4e2269ce3): Addressed code review comments.
Also use context with timeout when waiting for the checkup job to finish.

2022-04-20 15:00 UTC, ormergi commented on kiagnose/internal/checkup/job/job.go
> +	jobWatcher, err := client.Jobs(job.Namespace).Watch(context.Background(), metav1.ListOptions{LabelSelector: jobLabel})
As we concluded offline due to the complexity using an informer brings using bare watcher is good enough for now.
I posted new PR for using informer https://github.com/kiagnose/kiagnose/pull/32

2022-04-24 07:40 UTC, orelmisan commented on kiagnose/internal/checkup/job/job.go
> +	jobWatcher, err := client.Jobs(job.Namespace).Watch(context.Background(), metav1.ListOptions{LabelSelector: jobLabel})
Thank you for the effort.

2022-04-24 07:41 UTC, EdDev requested changes

2022-04-24 07:41 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func TestCheckupRunShouldFailWhen(t *testing.T) {
@orelmisan , why do we need to differentiate between different errors? Is there a different action to take if the error differs?
I would even claim that you do not even covered here all the error types that can be raised, moreover, there may be others added (or removed) in the future.
As I see it, if there is no differentiation on the production code about what to do when a specific error is detected, there is no point in covering it in tests.

2022-04-24 07:41 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
>  	return nil
I think that the question was about how this "waiting" here integrates with the need to record its run status on the result ConfigMap.

So let me ask this in a more specific manner:
- If the wait ends without a timeout, is the job still around to query its status?

2022-04-24 07:41 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +				{Type: condition}}}}
nit: Can you place this in one line?
It is hard to see the relation between opened and closed braces.. It will be nice to see blocks like this:
```
foo{
    boo{
        zoo{..{}}
    }
}
```

I wander if we can enforce this with a formatter.

2022-04-24 07:41 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +	const JobNameLabel = "job-name"
Where is this coming from?

2022-04-24 07:41 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +	log.Printf("'%s/%s' Job watcher obtained", job.Namespace, job.Name)
Why do we need this? If it was not obtained, we get an error, no?

2022-04-24 07:41 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +			}
If we will log this for every job change, it will be too verbose IMO.
I do not think this needs to exist in the production code.

2022-04-24 07:41 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +		}
`return condition.Type == batchv1.JobComplete || condition.Type == batchv1.JobFailed`

2022-04-24 07:41 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +		case event := <-eventsCh:
`watcher.Stop()` closes the channel?

2022-04-24 07:41 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +func TestCheckupRunShouldFailWhen(t *testing.T) {
Can we deduce it from another source?

This is important for loading (or not) the checkup's results from its ConfigMap.

2022-04-24 07:42 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
>  	return nil
This could lead to reading an empty ConfigMap object.

2022-04-24 07:44 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +			assert.NoError(t, testCheckup.Run())
I just don't understand how the checkup is run without its supporting objects created by Setup().
Can you please elaborate?

2022-04-24 18:17 UTC, ormergi reviewed
@orelmisan @EdDev please take another look I resolved some code review comments and answered questions.

2022-04-24 18:17 UTC, ormergi commented on kiagnose/internal/checkup/job/job.go
> +		}
Note that Job status conditions can be `Completed` `Failed` or `Suspended`, other than that it seems that its possible to add any other arbitrary condition to the Job status (according to doc status.conditions can be patched)
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/#JobStatus

2022-04-25 09:23 UTC, EdDev requested changes

2022-04-25 09:23 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +		}
Based on that information, this is not complete then. Right?

2022-04-25 09:23 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +	actualJob, err := testClient.Tracker().Get(gvr, checkup.NamespaceName, checkup.JobName)
Is it possible to use a simple `Get` here? Do you need the `Tracker()` in this check?

2022-04-25 09:23 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func assertJobCreated(t *testing.T, testClient *testsClient, image string, timeout time.Duration, envVars []corev1.EnvVar) {
This helper does 3 things, hiding a lot of things from the tests, which in this case could have assisted the reader to understand better.

WDYT about this (at the test):
```
createdJob := ...
expectedJob := ...
assert.Equal(t, createdJob, expectedJob)
```

2022-04-25 09:23 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +		assert.ErrorContains(t, testCheckup.Run(), context.DeadlineExceeded.Error())
It will be better to assert on the error type/indentity if possible. Is it possible without changing the production code?

2022-04-25 12:29 UTC, ormergi reviewed
Addressed code review comments

2022-04-25 12:29 UTC, ormergi commented on kiagnose/internal/checkup/job/job.go
> +		}
From what I tested a Job is considered to be finished when `Complete` or `Failed` conditions exists,
this is why we look for these conditions at Job status.

2022-04-25 12:29 UTC, ormergi commented on kiagnose/internal/checkup/job/job.go
> +	log.Printf("'%s/%s' Job watcher obtained", job.Namespace, job.Name)
Done

2022-04-25 13:02 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +		}
I think it says you need to check the `conditions.status` value for `true` as well.

2022-04-26 06:03 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/ddd9397e459fcae68131837cbc7de147393b015a..2c5d72ed1160fc06d54ad2820f72cb4778a40eee): Check conditions.status when watching the checkup Job.

2022-04-26 06:43 UTC, EdDev commented on kiagnose/internal/checkup/job/job.go
> +		}
This seems incorrect to me: I think the `||` logical expression needs to be parenthesized.

Please check how you can cover this bug in the tests.

2022-04-26 06:45 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +		assert.ErrorContains(t, testCheckup.Run(), context.DeadlineExceeded.Error())
Lets proceed as is, this is good enough.

2022-04-26 11:26 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
>  	return nil
Sorry for the confusion this is correct ttlSecondsAfterFinished will trigger the job to delete and activeDeadlineSeconds trigger it to stop.

2022-04-26 13:29 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/013bd721262d165867fc2c756baf6be0b1a2ab61..65acadcccf133d5b606016f10f9056f006367250): Change the injected Job event condition definition to be explicit on tests, and cover the case that was mentioned at https://github.com/kiagnose/kiagnose/pull/27#discussion_r858336398

2022-04-26 13:34 UTC, EdDev approved these changes
Thank you!

2022-04-26 14:40 UTC, merged