kubevirt-vm-latency: Intorduce skeleton
kiagnose/kiagnose pull request #41
Opened 2022-04-28 06:45 UTC by ormergi

This PR Introduce the skeleton for Kubevirt VM Latency checkup and few
wiring to concrete objects including:
-   Runner:     responsible for top level logic flow
-   Checkup:  responsible for spinning up VM's and check latency between them.
-   Reporter:  responsible for reporting execution results (e.g: latency measurement results)

The Checkup and Reporter introduced with an empty implementations.
kubevirt-vm-latency: Intorduce skeleton.

**Depends on #40**

2022-05-01 09:14 UTC, EdDev requested changes

2022-05-01 09:14 UTC, EdDev commented on checkups/kubevirt-vm-latency/latencycheck/internal/reporter/reporter.go
> +type reporter struct {
Having this named as the package name is problematic.
One of them needs to be changed.

2022-05-01 09:14 UTC, EdDev commented on checkups/kubevirt-vm-latency/latencycheck/internal/reporter/reporter.go
> +	"github.com/kiagnose/kiagnose/checkups/kubevirt-vm-latency/latencycheck/internal/runner"
This is a dependency which you wanted to avoid by the interface, but you still need it. It is a smell.

2022-05-01 09:27 UTC, orelmisan reviewed
Thank you for the PR @ormergi.
Please see the inline comments.

2022-05-01 09:27 UTC, orelmisan commented on checkups/kubevirt-vm-latency/latencycheck/internal/reporter/reporter.go
> +	namespace string
Please consider adding `configMap` prefix to `name` and `namespace`.

2022-05-01 09:27 UTC, orelmisan commented on checkups/kubevirt-vm-latency/latencycheck/internal/runner/runner.go
> +func (s *status) Succeed() bool {
Please consider renaming it to `Succeeded()`.

2022-05-01 09:27 UTC, orelmisan commented on checkups/kubevirt-vm-latency/latencycheck/mainflow.go
> +func Run() error {
I think a configuration fetching logic should be called here (and added as a package).

2022-05-01 17:52 UTC, ormergi reviewed
[Changes](https://github.com/kiagnose/kiagnose/compare/6ef35deebf7dca0aac7e1473d66993ee9d32bc85..0ec9fa457fc0ab2580077b03eafb8383928ce0ba)

2022-05-01 17:57 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/mainflow.go
> +	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
After struggling Kubevirt client on another PR, it seems that the only client that includes console verb ("kubevirt.io/client-go") wont receive context as parameter and create new context.Background() on each operation.
I will remove it for now.

2022-05-01 17:57 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/internal/runner/runner.go
> +type Report interface {
It seems that there will be dependency between `runner` and `reporter` as one is composited form the other,
Following our discussion offline I will remove this interface, and change Report() to receive `map[string]string` instead.

2022-05-01 17:58 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/internal/runner/runner.go
> +func newStatus() *status {
`status` related code is moved to new file, it also include some changes following other comments.

2022-05-01 17:59 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/internal/runner/runner.go
> +package runner
To me it sounds better, I think launcher is better fit for "heavier" stuff, I dont mind changing it.

2022-05-01 18:00 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/internal/runner/runner.go
> +		status:   newStatus(),
Its not a must for now, I will change it to be local.

2022-05-01 18:00 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/internal/runner/runner.go
> +	succeeded      bool
I will change it accordingly, thanks for the heads up.

2022-05-01 18:01 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/internal/reporter/reporter.go
> +	namespace string
Done

2022-05-01 18:01 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/internal/runner/runner.go
> +func (s *status) Succeed() bool {
Done

2022-05-01 18:06 UTC, ormergi commented
@EdDev @orelmisan please take another look

2022-05-01 19:00 UTC, EdDev commented on checkups/kubevirt-vm-latency/latencycheck/mainflow.go
> +	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
What does that mean? That we cannot gracefully terminate?

2022-05-01 19:22 UTC, EdDev commented on checkups/kubevirt-vm-latency/latencycheck/mainflow.go
> +func Run() error {
> Do you think its worth to add an empty implementation for them?

Yes, it will be easier to understand, reason and avoid reverting stuff.
But this is not a must, up to you.

2022-05-01 19:32 UTC, EdDev commented on checkups/kubevirt-vm-latency/latencycheck/internal/runner/runner.go
> +type Report interface {
Not sure why `map[string]string`, but I will try to see at the new implementation and comment there.

2022-05-02 14:09 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/mainflow.go
> +	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
I think that If we use `kubevirt.io/client-go` to console the VM's, the console operation wont terminate gracefully,
other operations could be terminated gracefully when done with different client that receive context's (e.g: controller-runtime).

2022-05-02 14:27 UTC, ormergi commented on checkups/kubevirt-vm-latency/latencycheck/mainflow.go
> +func Run() error {
Done

2022-05-02 14:33 UTC, ormergi commented
Changes [1](https://github.com/kiagnose/kiagnose/compare/1dc3139cedd4c1ea5bc06f7fc200fd65aeb521c7..6429e88a1f69b215928e9301bb00d1c3d1bf60be) and [2](https://github.com/kiagnose/kiagnose/compare/6429e88a1f69b215928e9301bb00d1c3d1bf60be..881fe717410ae1792669a48444a487c6f7965d47): Added Client and Config packages with empty implementations

2022-05-02 14:44 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/1dc3139cedd4c1ea5bc06f7fc200fd65aeb521c7..d856dc9020f56e8cc5f6b70c606840f2648011ef): Added Client and Config packages with empty implementations.

2022-05-03 10:59 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/d856dc9020f56e8cc5f6b70c606840f2648011ef..7fe903f06891ee2aba366fccdd34fe5f0f360456): Define an interface between Checkup, Launcher and Reporter

2022-05-04 05:13 UTC, EdDev reviewed
Reviewed "kubevirt-vm-latency: Add testify dependencies ".

2022-05-04 05:13 UTC, EdDev commented on checkups/kubevirt-vm-latency/go.mod
> +require github.com/stretchr/testify v1.7.1
Can you try and redirect it to the root vendor location? It does not make sense to keep this twice.

2022-05-04 06:58 UTC, ormergi commented
[Changes ](https://github.com/kiagnose/kiagnose/compare/7cb88a96fe25800a358544b4a1708e44c1e93492..cabccc95832e8994aa23dc985819fcfe13c66e38): Get rid of Runner naming

2022-05-04 07:06 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/cabccc95832e8994aa23dc985819fcfe13c66e38..bedd19b90ec791ebf6341020a33efbec2079e9e1): Add missing files license

2022-05-04 07:14 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/bedd19b90ec791ebf6341020a33efbec2079e9e1..145c135f722c657d6818187e376489538aa31caf): Fix Launcher tests function name

2022-05-04 07:27 UTC, ormergi commented
@EdDev @orelmisan I pushed new commits with those changes we will have the most basic 
checkup that includes loading env var and writing results to ConfigMap.
Please take a look, let me know what you think.
If this is too much I can split it to few PR's.

2022-05-04 07:34 UTC, EdDev commented
> @EdDev @orelmisan I pushed new commits with those changes we will have the most basic checkup that includes loading env var and writing results to ConfigMap. Please take a look, let me know what you think. If this is too much I can split it to few PR's.

The linter added notes inline of some problems.
I did start looking at this but you seem to push now frequently. Please notify again when you finished.

2022-05-04 09:27 UTC, orelmisan reviewed
Thank you @ormergi for this PR.

I believe the last three commits should be split to two follow up PRs:
1. Reporting the results.
2. Introducing the Kubevirt client.

2022-05-04 09:27 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/reporter/configmap/configmap.go
> +/*
IMO this commit should be split to a PR of its own.

2022-05-04 09:29 UTC, orelmisan commented
@ormergi Please remove or strike-through `Depends on #40` in the PR description.

2022-05-04 09:31 UTC, orelmisan commented on checkups/kubevirt-vm-latency/cmd/main.go
> +	"github.com/kiagnose/kiagnose/checkups/kubevirt-vm-latency/latencycheck"
@ormergi  Can you please change `check` to `checkup`?
They don't have the same meaning.

2022-05-08 13:45 UTC, EdDev requested changes
Reviewed until the `kubevirt-vm-latency, config: Load checkup parameters from env` commit (including).
Specifically with the config parsing commit, it would have been helpful you describe in the commit what it includes (which config params, who have defaults and who are mandatory, etc).

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/client/client.go
> +type Client struct{}
This is suppose to be a placeholder for the `kubevirt` client?

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/checkup/checkup.go
> +func (c *checkup) Preflights() error {
I think it can say singular, like the others.

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/status/status.go
> +	return &Status{Results: &Results{}}
Why it returns a pointer?

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/checkup/checkup.go
> +	"github.com/kiagnose/kiagnose/checkups/kubevirt-vm-latency/vmlatencycheck/internal/status"
I'm not sure if this dependency is required.
If it is, we should see it later on and not now.
(and if it can be avoided, it is better)

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config.go
> +	DefaultDesiredMaxLatencyMilliseconds = math.MaxInt
To avoid this magic import, can we just use here a hard value like 1 hour?

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config.go
> +	sampleDuration, err := strconv.Atoi(env[SampleDurationSecondsEnvVarName])
Seems you ignore invalid values here and in the next one. Why?
If this is intentional, please elaborate in the commit message.

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config_test.go
> +	t.Run("succeed", func(t *testing.T) {
There are many reasons it can succeed, so it is not clear what this scenario is trying to check.

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config_test.go
> +		assert.NotNil(t, testConfig)
I think you know what to expect, right? If so, please assert against the expectation.

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config_test.go
> +		assert.NoError(t, err)
Usually the error is asserted first.

2022-05-08 13:45 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config_test.go
> +			assert.Nil(t, testConfig)
I do not think this needs assertion. On error, the value is not defined and we should not say anything else to the reader.

2022-05-09 05:49 UTC, EdDev requested changes
Finished passing over all the commits.

The last two commits can be extracted away to a different PR, reducing the size of this one.

I would also like to see redirections to the root vendor folder and reduce duplication.
We are currently maintaining all in the same monorepo, therefore we better take advantage of it and be consistent with versioning and reduce storage load from the repo.

Lastly, please try to review again the commit messages, some require some fixes to make it simpler and clearer. I will try to be more specific in the next review round.

2022-05-09 05:49 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/reporter/configmap/configmap.go
> +func UpdateData(ctx context.Context, clt corv1client.CoreV1Interface, namespace, name string, data map[string]string) error {
It looks like this function is updating the whole ConfigMap, not only the data. In practice it overrides it.
Therefore, calling it just `Update` is a bit more accurate.

2022-05-09 05:49 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/reporter/configmap/configmap.go
> +type ErrUpdateConfigMap struct {
The reasoning for this error type in the commit message and in the tests usage is not that strong.
There is a single error returned, which means there is no need to differentiate between returned errors.
Perhaps you can explain why asserting for the existence of the error is not enough.

2022-05-09 05:49 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/reporter/reporter_test.go
> +}
This is used once and seems an overkill at this stage.
How about:
```go
func failCondifMapUpdate(c *fake.Clientset, err error) {
    c.PrependReactor("update", "configmaps", func(_ clienttesting.Action) (bool, runtime.Object, error) {
		return true, nil, err
    })
}
```

2022-05-09 05:49 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/reporter/reporter.go
> +}
Why is this needed now? Is it serving something significant?

2022-05-09 12:08 UTC, ormergi commented on checkups/kubevirt-vm-latency/go.mod
> +require github.com/stretchr/testify v1.7.1
In general I agree they should be separated, at this point in time I this its fine because it should be easy to 
move it to another repo.
Thus I did tried to reuse `testify` from the root vendor directory, but I didn't managed to make it work.
I added replace rule to go.mod: `replace github.com/stretchr/testify => ../../vendor/ ../../vendor/github.com/stretchr/testify`
but got the following error from `go mod tidy`:
```
go: github.com/stretchr/testify@v1.7.1 (replaced by ../../vendor/github.com/stretchr/testify): reading ../../vendor/github.com/stretchr/testify/go.mod: open /home/omergi/go/src/github.com/kiagnose/kiagnose/vendor/github.com/stretchr/testify/go.mod: no such file or directory
```
Note that this would work for non vendored packages.

2022-05-09 13:18 UTC, ormergi reviewed
Addressing "kubevirt-vm-latency: Intorduce skeleton" comments

2022-05-09 13:30 UTC, ormergi commented
Changes: [[1]](https://github.com/kiagnose/kiagnose/compare/734bfdcbf3d5e21fb14e13c74bde58fc9b273d75..f765df3d2944d0f2571de641793f0b02c72a2ab4) renaming 
[[2]](https://github.com/kiagnose/kiagnose/compare/f765df3d2944d0f2571de641793f0b02c72a2ab4..bbf6307354b9972fc9bb95f5013d543fd1ab49c3) rename vmlatncycheckup package

2022-05-09 13:37 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/reporter/reporter.go
> +type configMapReporter struct {
How is this passing in the framework?

2022-05-09 13:39 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatencycheck/mainflow.go
> +package vmlatencycheck
I favor `vmlatency`.

2022-05-09 13:46 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config.go
> +	DefaultDesiredMaxLatencyMilliseconds = math.MaxInt
Using `time.Hour` requires some ugly conversions, I will change it to hardcoded hour in milliseconds.

2022-05-09 14:01 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config_test.go
> +	t.Run("succeed", func(t *testing.T) {
The scenario is when both sample duration and desired max latency parameters are missing, 
it is expected that they will set with the default values.
Looking at this test again I see no value in having it, the other two covers it.
I will remove it.

2022-05-09 15:14 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/bbf6307354b9972fc9bb95f5013d543fd1ab49c3..bcdb47b8d954d6e41824e1def37fcc5088b1ca3d): update imports following `vmlatencycheck` rename.

2022-05-09 17:28 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config.go
> +	sampleDuration, err := strconv.Atoi(env[SampleDurationSecondsEnvVarName])
Following our discussion, I change the code to fail if its not valid and added tests.
If the a parameter env var is missing it will still be set with the default.

2022-05-09 17:31 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/bcdb47b8d954d6e41824e1def37fcc5088b1ca3d..ef8e54a2f2e68d7c8c00035c7a3b511e615e7428): Change Config to fail in case optional checkup parameters env vars are invalid (following https://github.com/kiagnose/kiagnose/pull/41#discussion_r867492974)

2022-05-09 17:50 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/bcdb47b8d954d6e41824e1def37fcc5088b1ca3d..b3883d2a1462362b45fc0926be302cfc022370fc): Change Config to fail in case optional checkup parameters env vars are invalid (following https://github.com/kiagnose/kiagnose/pull/41#discussion_r867492974)

2022-05-09 18:24 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/b3883d2a1462362b45fc0926be302cfc022370fc..6be8289f9dbb6ad1525b98018fc9a9e784cad08b): Change Config successful create test to assert the Config{} object instead specific attributes, also remove redundant test.

2022-05-09 18:25 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config_test.go
> +	t.Run("succeed", func(t *testing.T) {
Done

2022-05-09 18:27 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config_test.go
> +			assert.Nil(t, testConfig)
Done

2022-05-10 06:10 UTC, ormergi commented
@EdDev @orelmisan regarding splitting this PR,
The commit "kubevirt-vm-latency, reporter: Format results and update configmap"[ [1]](https://github.com/kiagnose/kiagnose/pull/41/commits/0c3188010e2ff5762d8b9a2912d32d67c76d2881) introduces
tests that requires some k8s dependencies, meaning that moving last two commits out of this PR
will make this PR to not pass CI.
In order to move last two commits to different PR, it is necessary to move out the tests [1] introduces, WDYT?

2022-05-10 09:50 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/6be8289f9dbb6ad1525b98018fc9a9e784cad08b..035525eb4d1c17c76b9fa15f960eb17024df17a9): 
- The last two commits (introduces Kubevirt client dependencies and integration) are removed and will be moved to follow up PR.
- `Reporter` tests are changed to use uses stub client instead of K8S fake client

2022-05-10 12:16 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/035525eb4d1c17c76b9fa15f960eb17024df17a9..dbd21bbf439af569b27d336f5edd5af8889c7512): Add checkup test for visibility of its implementation state.

2022-05-10 13:03 UTC, orelmisan reviewed
Second commit.

2022-05-10 13:03 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
> +func TestLauncherShould(t *testing.T) {
Please consider splitting this function in to three groups:
1. Success scenario.
2. Failures that produces a report.
3. Failures that don't produce a report.

2022-05-10 15:18 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config.go
> +	ResultsConfigMapNamespace string
Is there a problem if  `checkup` "knows" these fields?

2022-05-10 15:22 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/reporter/reporter.go
> +type configMapReporter struct {
Let me rephrase, I've asked how do we have in the framework a struct `reporter.Reporter`?, and here the linter fails it.

2022-05-10 15:25 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config.go
> +	ResultsConfigMapNamespace string
These are different configs for different entities.
We can break it in a future PR if its too much work.

2022-05-10 16:17 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/dbd21bbf439af569b27d336f5edd5af8889c7512..a8871f3fd0461fa55fa933f64312a923fe92ed2e): rename `reporter` struct.

2022-05-10 16:18 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/reporter/reporter.go
> +type configMapReporter struct {
Done

2022-05-10 16:56 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/a8871f3fd0461fa55fa933f64312a923fe92ed2e..433fbdc92567db0aa8fe2bb7fbbe89dc5a312e32): Pass only the necessary parameters to checkup from `Config` ,following https://github.com/kiagnose/kiagnose/pull/41#discussion_r864590878

2022-05-10 16:56 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/config/config.go
> +	ResultsConfigMapNamespace string
Done

2022-05-11 06:43 UTC, EdDev reviewed
Reviewed the "Introduce skeleton" commit.

2022-05-11 06:43 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +func New(_ map[string]string) (*Config, error) {
I have seen no evidence or reasoning that it merits the use of a pointer.
If the is no strong reason to use it, please avoid and use the minimum needed.
(an example of a possible reasoning can be: It is passed to other entities as a pointer)

2022-05-11 06:43 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/status/status.go
> +}
I do not see a specific reason for this data structure to have a factory. Nor why it needs to be a pointer.
If it is due to some futuristic usage, in a following PR, please reason for it there.

2022-05-11 06:43 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/status/status.go
> +	FailureReasons []string
I would prefer to see singular names where possible.
E.g. `FailureCondition`.
But this is a nit.

2022-05-11 06:43 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
> +	"github.com/kiagnose/kiagnose/checkups/kubevirt-vm-latency/vmlatency/internal/status"
Seems like too many components (launcher, reporter, checkup) depend on this data, which means all are tightly coupled.
Although it is not a blocker at the moment, the approach taken in `kiagnose` core is nicer IMO.

2022-05-11 06:43 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
> +func (l *launcher) Run() (runErr error) {
If the method is not going to mutate its members directly, I do not think it should have a pointer receiver.

2022-05-11 06:43 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
> +			runStatus.FailureReasons = append(runStatus.FailureReasons, fmt.Sprintf("report: %v", err))
IMO the called method should add this `report:` prefix, declaring itself.
I do not think that each potential caller needs to specify it, it is not adding information that is relevant to this abstraction layer.

Same for all the rest.

2022-05-11 06:43 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
> +	defer func() {
Please separate with a newline above.

2022-05-11 06:43 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
> +func TestLauncherShould(t *testing.T) {
Prettifying it can be done later (although, arranging it well and in tables, may help with adding new tests easier).

2022-05-11 06:43 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +func TestCheckupShouldFailDueToRunNotImplemented(t *testing.T) {
Please drop the `DueToRunNotImplemented`.

Generally speaking, I think this should have been covered through the `launcher` using the production checkup.
Leaving here only scenarios that cannot be reached from the `launcher` in the future.

I am not going to insist on this at the moment, we can improve the tests later.

2022-05-11 06:51 UTC, EdDev reviewed
>  kubevirt-vm-latency, config: Load checkup parameters from env
>
> CheckupParameters struct is definded as pointer as checkup.Checkup
> attribute due to linter error regarding its size.

I prefer this is avoided. I disagree with the linter.
See #51 

But even if this will stay in, it makes it hard for me to review two changes, please split into two, one answering the linter and the other adding the needed.

2022-05-11 07:11 UTC, EdDev reviewed
Reviewed up to the "Load checkup parameters from env" commit.

2022-05-11 07:11 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +func (e ErrInvalidEnvVarValue) Unwrap() error { return e.wrappedError }
Sorry, I (still) do not understand why the custom error type is needed.

2022-05-11 07:11 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	if env == nil {
I am not sure we need to be that defensive here.
We do not expect `vmlatency` to be used as a library by others, and even if someone will use it like that, we could be more generic and say that if the input is "empty", we return a proper error (and that fits both `nil` and an empty map).

Will that work?

2022-05-11 07:11 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +		sampleDuration, err = strconv.Atoi(value)
nit: I think it can be inline in the error below.

2022-05-11 07:11 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +		desiredMaxLatency, err = strconv.Atoi(value)
same, can be inline.

2022-05-11 07:20 UTC, EdDev reviewed
Finished review.

2022-05-11 07:20 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +func New(clt configMapUpdater, configMapNamespace, configMapName string) *reporter {
I can't find where I commented about prefering `c` over `clt`.
Could you change it and check if it exists anywhere else?

2022-05-11 07:20 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +		fmt.Printf("reporting status:\n%s\n", string(raw))
We usually do not print directly to `stdout`.
What does it mean if it fails to parse it?

2022-05-11 07:20 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +	}
This is an example of why a pointer is not always good.

2022-05-11 07:20 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +	if s.Results != nil {
In what scenario this can happen?

2022-05-11 08:51 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/433fbdc92567db0aa8fe2bb7fbbe89dc5a312e32..33b54faaa6dfe8746f6e2f2dba19cfcf38dcdb73): 
- Remove error prefix's from launcher.Run()
- Change Config and Launcher to be used as value instead of pointer
- Move `checkup` failing test to be tested by `launcher` test suite with production `checkup.Checkup{}`.

2022-05-11 09:09 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/33b54faaa6dfe8746f6e2f2dba19cfcf38dcdb73..f0b67712dc94eb6018739a946203178391ad851d): Change `config.Config` pointer usage to value in tests, and fix small issue with launcher test.

2022-05-11 09:14 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/f0b67712dc94eb6018739a946203178391ad851d..c68a6561adc7c6ce957d2106bdea7dbeb535bdff): Rename `FaliureReasons` to singular form.

2022-05-11 09:52 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/db2463857c408c50fa08183e4bf086ad4d629297..eb692a05c3d828906081d0ddcaa68fe5ac4d8186): Change` status.Status{} `pointer usage to value.

2022-05-11 10:21 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/eb692a05c3d828906081d0ddcaa68fe5ac4d8186..be5c681a8311ec220dd29782af46b1f2d83b8901): Change `config.New()` to return an error in case of nil or empty map, and inline `Atoi` `if` closures at config.New().

2022-05-11 10:25 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/be5c681a8311ec220dd29782af46b1f2d83b8901..6de22aacbb7e5aca799146977f93e039544b3621): Rename client argument `clt` to `c`, all over

2022-05-11 10:28 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/6de22aacbb7e5aca799146977f93e039544b3621..872133860dd09c084fdf83aa1dc8a1dfbe760424): Log the checkup results instead of sending it to stdout directly.

2022-05-11 10:50 UTC, ormergi reviewed
@EdDev Thanks for the review.
I addressed most of comments, please take another look.

2022-05-11 10:50 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	if env == nil {
Thanks for explaining, the reason for this is to return meaningful error if `env` is `nil` instead of `ErrResultsConfigMapNameMissing` which will be the first thing to fail.
Looking at this again if `env` is empty it will return `ErrResultsConfigMapNameMissing,
I can fix so it will return `ErrInvalidEnv` is `env` is nil or empty.

Make sense?

2022-05-11 10:50 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +		sampleDuration, err = strconv.Atoi(value)
Done

2022-05-11 10:50 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +		desiredMaxLatency, err = strconv.Atoi(value)
Done

2022-05-11 10:50 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +		fmt.Printf("reporting status:\n%s\n", string(raw))
> We usually do not print directly to stdout.

Sorry this is a mistake, I meant to to use `log.Printf()`, I changed it.

>What does it mean if it fails to parse it?

It means that `data` is not supported cannot be serialized to json,
it is not likely to happen since `data` is of type `map[string]string` which is supported.
Do you think its work to define `data` explicitly?

2022-05-11 10:50 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +func New(clt configMapUpdater, configMapNamespace, configMapName string) *reporter {
Done all over.

2022-05-11 10:50 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +	if s.Results != nil {
In case status.Results is not initialized, status.Results is expected to be initialized by checup.Run().
If checkup.Run() did not executed (for example: due to preflight or setup error) it should be nil,
so that the end results is that only `Succedded` and `FailureReason` appears at the results `ConfigMap`.

2022-05-11 12:02 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/status/status.go
> +}
> As for `Results{}`, it represent the checkup results
> which may be absent if the checkup did not ran, for example due to setup or preflight failure.

I fail to understand why does it matter. If it is `nil` or with defaults (zero values) it should behave the same.
It is also a cognitive burden for me to understand what an embedded pointer means in the struct.

By using pointers all over the complexity of the code increases.
it is hard for me to understand if this is a must or not.

2022-05-11 12:08 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatencycheck/internal/reporter/reporter_test.go
> +}
This was removed right? I can't find it.

2022-05-11 12:13 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	if env == nil {
I think what you can do is check its size (`len`) and but that you solve the problem.

2022-05-11 12:15 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
> +type launcher struct {
I find it confusing that we are using unexported types from other packages.

2022-05-11 12:16 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +		fmt.Printf("reporting status:\n%s\n", string(raw))
Based on the code, you do not do anything with it, even if it fails.
So it seems redundant to me (except maybe for debugging, but I am unsure if that was the intention).

2022-05-11 12:17 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
> +func TestLauncherShould(t *testing.T) {
Fair enough.

2022-05-11 12:19 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +	if s.Results != nil {
I do not see a problem with showing other parameters with a zero value.
But even then you can check for the zero value and not add the burden of a `nil` on the code.

2022-05-11 12:22 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	if env == nil {
If the map is empty, I would expect to see the first mandatory field failing to be parsed.

2022-05-11 12:24 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +		fmt.Printf("reporting status:\n%s\n", string(raw))
I don't see this code anymore, was it removed?

2022-05-11 12:38 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +	r := launcher.New(checkup.New(c, cfg.CheckupParameters), reporter.New(c, cfg.ResultsConfigMapNamespace, cfg.ResultsConfigMapName))
nit: this is a `l`, not a `r`.

2022-05-11 13:57 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +func (e ErrInvalidEnvVarValue) Unwrap() error { return e.wrappedError }
Alright fair enough, I will do it on a follow up PR.

2022-05-11 13:58 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/872133860dd09c084fdf83aa1dc8a1dfbe760424..ebd09da28917af34caa579982b5d8d33986b6c60): Remove custom error type from `config`.

2022-05-11 14:38 UTC, ormergi commented
[Chnages](https://github.com/kiagnose/kiagnose/compare/ebd09da28917af34caa579982b5d8d33986b6c60..a65fb6b7d5a201c69fb1cc98992ab8cc9385a16e): Get rid of using statis.Results as pointer.

2022-05-11 14:54 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter.go
> +	if s.Results != nil {
I changed Results{} pointer usage to value.

2022-05-11 14:57 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/a65fb6b7d5a201c69fb1cc98992ab8cc9385a16e..e42420990ffa6200b446541a164130d9653d916d): Rename launcher local variable name at mainfliow.go

2022-05-11 14:57 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +	r := launcher.New(checkup.New(c, cfg.CheckupParameters), reporter.New(c, cfg.ResultsConfigMapNamespace, cfg.ResultsConfigMapName))
Done

2022-05-11 15:14 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/e42420990ffa6200b446541a164130d9653d916d..dec41cab24e7ba32b2a5a3f31ecbd7c351867b0c): Split converting `CheckupParameters{}` to pointer due to linter error to its own commit, following 
 https://github.com/kiagnose/kiagnose/pull/41#pullrequestreview-968763415

2022-05-11 15:24 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/8cb23c675523b3970e03c486dde945320556b85d..d4a0b450e0ac724454f1395a3aaf2e3fbc199527): Get rid of pointer receiver at `reporter` tests

2022-05-11 15:43 UTC, EdDev reviewed
Thank you!

> kubevirt-vm-latency, checkup: Change CheckupParameters to pointer 

This commit can be dropped, the linter has been adjusted not to fail now.
If you on the other hand want me to send a revert for this after, I am fine with it.

2022-05-11 15:44 UTC, EdDev reviewed
Thank you!

> kubevirt-vm-latency, checkup: Change CheckupParameters to pointer 

This commit can be dropped, the linter has been adjusted not to fail now.
If you on the other hand want me to send a revert for this after, I am fine with it.

2022-05-11 16:15 UTC, ormergi commented
Reabsed on latest main

2022-05-11 16:16 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/33e818613e253f12309a4ac6cf716ee2240c8bdd..69348970bde2114c5af8b43973e215170f5ebdfd): Get rid of `CheckupParameters` pointer usage.

2022-05-11 16:23 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
> +type launcher struct {
@orelmisan in general this is a way to restrict how the object will be created, that way there is no need to expose it.

2022-05-11 16:23 UTC, merged