reporter: Add basic reporting capability
kiagnose/kiagnose pull request #45
Opened 2022-04-28 13:18 UTC by orelmisan

This PR adds basic reporting capability:
1. The `startTimestamp` and `completionTimestamp` are recorded and reported.
2. `succeeded` field is always reported as `false`.
3. `failureReason` field is always reported as `Failure: implement me`.

2022-05-01 05:31 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/35b495cb153df6d4012c0acabd1477720958fa13..ab4b72460310f33290fadf7372b6f38090785e1d): Moved handling and testing of failure cases to first commit.

2022-05-01 07:19 UTC, ormergi reviewed
Hi Orel,

It looks better then first implementation!
I couldn't find the part where `succeeded` and `failureReason` are being set at Launcher.Run(), did I miss something?

It seems that `startTimeStamp`, `completionTimeStamp`, `succeed` and `failureReason` describing the checkup execution, I think it will make more sense if `Launcher{}` would have the `status` instead of `Reporter{}`, its closer to reality which makes it it easier to understated IMO.
It will make the reporter very simple and easier to replace (switching to CRD)
and its seems it will be easier to integrate with the checkup resutls ConfigMap data: 
```
type reporter interface {
	Report(map[string]string) error
}

type status struct {
        succeeded bool
        failureReason
        startTs time.Time
        completionTs time.Time
        checkupResults map[string]string
}

type Launcher struct {
    ...
    status status
}

func (l Launcher) Run() (runErr error) {
	defer func() {
		**l.status.SetCompletionTimestamp(time.Now())**
                **l.status.SetResults(checkup.Results())**
		if reportErr := l.reporter.Report(**l.status.StringsMap()**); reportErr != nil {
        ...
        }
   	**l.status.SetStartTimestamp(time.Now())**
        ...
        l.status.SetSucceeded()
        return nil
 ```

2022-05-01 08:04 UTC, orelmisan commented on kiagnose/internal/reporter/reporter.go
> +		configMap: &corev1.ConfigMap{
In the first time we try to report, the user-supplied ConfigMap object is fetched, so relevant fields are filled.

2022-05-01 08:06 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +		reporterUnderTest.SetStartTimestamp(time.Now())
We can remove it, it doesn't change the test.

2022-05-01 08:09 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +		reporterUnderTest.SetStartTimestamp(time.Now())
Done.

2022-05-01 08:11 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/ab4b72460310f33290fadf7372b6f38090785e1d..ba9e8f15fa0ea811ddfb4daef8360fc96c4d2683): Answered code review comment.

2022-05-01 08:15 UTC, orelmisan commented on kiagnose/internal/reporter/reporter.go
> +	}
Imaging this scenario:
1. The user creates a ConfigMap with all required checkup configuration.
1. The user starts the framework with a reference to the ConfigMap from the previous step.

2022-05-01 08:22 UTC, orelmisan commented
> I couldn't find the part where succeeded and failureReason are being set at Launcher.Run(), did I miss something?

As the PR's description states: 
1. `succeeded` field is always reported as false.
2. `failureReason` field is always reported as Failure: implement me.

`succeeded`, `failureReason` and `results` will be integrated in later PR(s).

2022-05-01 08:35 UTC, orelmisan commented
> It seems that startTimeStamp, completionTimeStamp, succeed and failureReason describing the checkup execution, I think it will make more sense if Launcher{} would have the status instead of Reporter{}, its closer to reality which makes it it easier to understated IMO.
It will make the reporter very simple and easier to replace (switching to CRD)
and its seems it will be easier to integrate with the checkup resutls ConfigMap data:

Please note the the `status` type introduced by this PR is an interface - there is no integration of it with the Launcher.

2022-05-01 10:47 UTC, ormergi commented
> As the PR's description states:
> 
> 1. `succeeded` field is always reported as "false".
> 2. `failureReason` field is always reported as "Failure: implement me".
> 
> `succeeded`, `failureReason` and `results` will be integrated in later PR(s).

@orelmisan It will make more sense if you introduce  `succeeded`, `failureReason` on the same PR with the integration changes.

2022-05-01 11:08 UTC, orelmisan commented
@ormergi Please see @EdDev's suggestion [here](https://github.com/kiagnose/kiagnose/pull/35#issuecomment-1110950878).
This PR covers the second bullet.

2022-05-01 17:59 UTC, EdDev requested changes
First & second commits:

I think the two belong to the same commit because the second show how the first is used (and why it should be like it is).

I have not checked yet the rest, but maybe reporting and setting should always come toghether due to the same reasoning.

I would also check if you can cover the integration between all the components at the `launcher`. Current tests use a `stub, but I think you can use the real thing now and even add the expected assertions.
Generally speaking, I would prefer to see everything exercised through the `launcher` and only scenarios which cannot, see directly on the reporter.

2022-05-01 17:59 UTC, EdDev commented on kiagnose/internal/reporter/reporter_test.go
> +	})
What about when the `Update` fails?

2022-05-01 17:59 UTC, EdDev commented on kiagnose/internal/reporter/reporter_test.go
> +var checkupRawSpec = map[string]string{config.ImageKey: testImageValue, config.TimeoutKey: testTimeoutValue}
It is not clear why the data is useful in the tests below. I have not seen them in use.

2022-05-01 18:44 UTC, EdDev reviewed
The last two commits gives no hint about what are the concretes you intend to pass in.

There are several options, one is to pass an object (that implements the methods), another is to pass a DTO (struct, with no behavior) that was composed in the `launcher`.
I am unclear which is better, but perhaps you can raise reason why one is better than the other.

2022-05-01 18:44 UTC, EdDev commented on kiagnose/internal/reporter/reporter.go
> +		if succeeded := r.status.Succeeded(); succeeded != "" {
I would expect it to be a boolean. Why this is not the case?

2022-05-03 00:58 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/ba9e8f15fa0ea811ddfb4daef8360fc96c4d2683..854d2d8b80ee6d8a47731734d0abea0891a4dce9): Rebase
Answered review comments.

2022-05-03 01:00 UTC, orelmisan commented on kiagnose/internal/reporter/reporter.go
> +		if succeeded := r.status.Succeeded(); succeeded != "" {
It is now a boolean.
This field is reported only if the checkup is completed (completion timestamp is non zero).

2022-05-03 01:02 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +var checkupRawSpec = map[string]string{config.ImageKey: testImageValue, config.TimeoutKey: testTimeoutValue}
This data is simulating the checkup spec provided by the user.
It is used to check that the reporter appends the status data to it, without modifying the spec.

2022-05-03 01:05 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +	})
It is checked in the test where the ConfigMap is deleted after the first fetch:
1. The ConfigMap is fetched and stored.
2. There is a successful update.
3. The test deletes the ConfigMap without the reporter knowing about it.
4. The reporter tries to update the ConfigMap another time but fails because it doesn't exists.

2022-05-03 01:08 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +	})
This was added in the first commit.
From the second commit onward - it is checked twice:
1. After the first report (before Setup()).
2. After the second report (After Teardown() or a failure).

2022-05-03 01:10 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +	t.Run("when user-supplied ConfigMap is deleted after first fetch", func(t *testing.T) {
There are two different code paths, checked by two tests:
1. When the initial ConfigMap fetch fails.
2. When an update to the stored ConfigMap fails.

2022-05-03 01:10 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +		assert.NoError(t, reporterUnderTest.Report())
Done.

2022-05-03 01:10 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +			reporter.StartTimestampKey: startTimestamp.Format(time.RFC3339),
Done.

2022-05-03 01:10 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +	t.Run("when reporting startTimestamp", func(t *testing.T) {
Done.

2022-05-03 01:10 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +	"github.com/stretchr/testify/assert"
Done.

2022-05-03 07:50 UTC, orelmisan commented on kiagnose/internal/reporter/reporter.go
> +	}
@EdDev please see [your comment](https://github.com/kiagnose/kiagnose/pull/35/files#r858751693) from PR #35.

2022-05-03 12:12 UTC, EdDev requested changes

2022-05-03 12:12 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	failOnReportNum int
This seems to assume the inner behavior or the reporting action.
It makes the test fragile as it is strongly bound to the implementation details.

Maybe a software dependency on the behavior will be this: We expect the report to be called twice, once at pre-setup and the second time on teardown.
If we define it like that, you can have two flags: One for the `failReportAtStart` and the second for `failReportAtTeardown`. Seeing that at the test will make things clearer and how you do it it is up to the stub logic.

2022-05-03 12:12 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when first report is failing", func(t *testing.T) {
Please do not use `first` (or `second`) as mentioned in another comment.

2022-05-04 07:47 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/854d2d8b80ee6d8a47731734d0abea0891a4dce9..4bea2f0e7b54a8d51698b41dee0d3544aabb978f): Answered review comments.

2022-05-04 07:49 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when first report is failing", func(t *testing.T) {
Changed "first" to "pre Setup()".
Changed "final" to "post Teardown()".

2022-05-04 07:55 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	failOnReportNum int
The `reporterStub` has tree capabilities:
1. Never fail.
2. Always fail (to cover failure on the pre Setup() report).
3. Fail after teardown (fail on the second reporting).

2022-05-04 07:55 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +func newReporterStub(failReport error, failOnReportNum int) *reporterStub {
Done.

2022-05-04 07:56 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +	currentStatus := status.Status{StartTimestamp: time.Now()}
Changed `currentStatus` to `statusData`.

2022-05-04 07:56 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +	Report(*status.Status) error
Changed to regular struct.

2022-05-04 07:57 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +		assert.NoError(t, fakeClient.CoreV1().ConfigMaps(configMapNamespace).Delete(context.Background(), configMapName, metav1.DeleteOptions{}))
Added a function `injectFailureToAccessCheckupData()`.

2022-05-04 07:57 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +		for i := 0; i < 2; i++ {
Done.

2022-05-04 10:53 UTC, EdDev reviewed
First pass.

2022-05-04 10:53 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when pre Setup() report is failing", func(t *testing.T) {
Please try to avoid using function/method names.
We want to test scenarios, not individual functions.

2022-05-04 10:53 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when post Teardown() report is failing", func(t *testing.T) {
Same

2022-05-04 10:53 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when setup and post Teardown() report are failing", func(t *testing.T) {
same

2022-05-04 10:53 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when run and post Teardown() report are failing", func(t *testing.T) {
same

2022-05-04 10:53 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when teardown and post Teardown() report are failing", func(t *testing.T) {
same

2022-05-04 10:53 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +			&reporterStub{reportErr: errorReport, failReportAfterTeardown: true},
I wish we had a formatter that does it nicely.
I do not understand why gofmt is not consistent in this :/

It is hard to read if there is no consistency in either all the args are on the same line or not.
`foo(a, b, c)`
OR
```
foo(
  a,
  b,
  c,
)
```

This is even more important when the args themselves have args...

2022-05-04 10:53 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when run, teardown and post Teardown() report are failing", func(t *testing.T) {
same

2022-05-04 10:53 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	if r.failReportAfterTeardown && r.reportCount == 2 {
Maybe you should panic if it is more than 2? You now assume this is what will happen, so if it changes, you better know about it.

2022-05-04 10:53 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	if r.reportErr != nil && !r.failReportAfterTeardown {
And another option could have been to input two errors, one for the pre and the other for the post/after.
It would have looked nicer IMO with simpler conditions.

2022-05-04 11:20 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +var checkupRawSpec = map[string]string{config.ImageKey: testImageValue, config.TimeoutKey: testTimeoutValue}
Done.

2022-05-04 11:41 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +	t.Run("when user-supplied ConfigMap is deleted after first fetch", func(t *testing.T) {
Done.

2022-05-04 12:12 UTC, EdDev reviewed
Finished reviewing the 1st commit.

2022-05-04 12:13 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/4bea2f0e7b54a8d51698b41dee0d3544aabb978f..a50fc36a7c97eda5e7c326da5f516101a20f6651): Answered review comments.

2022-05-04 12:24 UTC, EdDev reviewed
Finished reviewing the rest.

2022-05-04 12:24 UTC, EdDev commented on kiagnose/internal/launcher/launcher.go
> +		statusData.Succeeded = false
I do not really mind much, but I think it is redundant.
By default the boolean is false and no where else you set it to true.

2022-05-04 13:01 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +		// Pre Setup() report
Done.

2022-05-04 13:02 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +		statusData.Succeeded = false
IMO it should be explicit to emphasize its not integrated to the checkup.

2022-05-04 13:03 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	if r.reportErr != nil && !r.failReportAfterTeardown {
Done.

2022-05-04 13:03 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	if r.failReportAfterTeardown && r.reportCount == 2 {
Done.

2022-05-04 13:04 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +			&reporterStub{reportErr: errorReport, failReportAfterTeardown: true},
All calls to launcher.New() are now consistent.

2022-05-04 13:04 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when teardown and post Teardown() report are failing", func(t *testing.T) {
Done.

2022-05-04 13:04 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when run and post Teardown() report are failing", func(t *testing.T) {
Done.

2022-05-04 13:04 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when post Teardown() report is failing", func(t *testing.T) {
Done.

2022-05-04 13:04 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("fail when pre Setup() report is failing", func(t *testing.T) {
Done.

2022-05-04 13:08 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	if r.failReportAfterTeardown && r.reportCount == 2 {
Done.

2022-05-08 07:03 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	failAtFinalReport   bool
From the test perspective, I find this messy.
Can you just pass in the error you expect to get and let the `Report` stub calculate it based on the specific error?

If one passes the "start report" error, it will know to raise it one the first attempt.
If one passes the "completion report" error, it will know to raise it only at the second attempt.

This way, you do not need 3 members, but only one.

2022-05-08 07:04 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	if r.reportErr != nil && !r.failReportAfterTeardown {
I continued on a new [thread](https://github.com/kiagnose/kiagnose/pull/45/commits/393e0778847f8573082216528df011622d4cb016#r867445479).
I did not originally meant to pass booleans, that is always a smell.

2022-05-08 07:40 UTC, EdDev commented on kiagnose/internal/launcher/launcher.go
> +		statusData.Succeeded = false
Ok

2022-05-08 07:46 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/012a0a1cbc7d4394866a103170dce0bfe0b211f4..d921a5a3801bce037fb14614b6c0b65cab493dec): Removed redundant members of struct `checkupStub`.

2022-05-08 07:47 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	failAtFinalReport   bool
Done.

2022-05-08 07:51 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	}
Can this be simplified to: `return r.reportErr` ?
Maybe you do not even need to counter now.

If it returns the wrong error, you will catch it.

2022-05-08 07:54 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	}
I think we need to return an error only when it is required.
For example, is the error should be on the second report, IMO we should return `nil`, and not an error.

2022-05-08 07:56 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	}
Right.

2022-05-08 07:59 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	}
Hmm.. but then, why do you need the `	if r.reportErr == nil` condition? Isn't it redundant?

2022-05-08 08:05 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	}
It was a left over and was removed.
Thanks.

2022-05-08 08:05 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/d921a5a3801bce037fb14614b6c0b65cab493dec..862f725325b0b02295d19bfc825b291bad80d3e4): Answered a review comment.

2022-05-08 08:07 UTC, EdDev submitted a review, later dismissed
Thank you!

2022-05-08 13:42 UTC, ormergi reviewed
Please see my inline comments

2022-05-08 13:42 UTC, ormergi commented on kiagnose/internal/launcher/launcher_test.go
> +	errorFailOnFinalReport   = errors.New("final report error")
nit: Please consider renaming `errorFailOnFinalReport` to something like `errorCompletionReport`
it will be easier to understand the test flow as it will be consistent with the test description.

2022-05-08 13:42 UTC, ormergi commented on kiagnose/internal/reporter/reporter.go
> +func (r *Reporter) Report(statusData status.Status) error {
Looking at this again, I think there is no need for the Reporter{} to keep an instance of the `ConfigMap`
it can be used locally instead, I think it will simplify this function and also `reporter.New().`

2022-05-08 13:42 UTC, ormergi commented on kiagnose/internal/reporter/reporter.go
> +	}
I think fetching the `ConfigMap` should not be conditional, its better to always fetch the latest state of the `ConfigMap`
it may prevent unexpected behavior.

2022-05-08 13:42 UTC, ormergi commented on kiagnose/internal/reporter/reporter_test.go
> +	}
nit: I think it will improve visibility if those were called directly (instead of setup()).

2022-05-08 13:42 UTC, ormergi commented on kiagnose/internal/reporter/reporter_test.go
> +}
nit: I think it will improve visibility `Fromat` would be called directly (instead of timestamp())
and save me few scrolls :wink: .

2022-05-08 13:49 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +	t.Run("on checkup start", func(t *testing.T) {
There are two reports:
1. When the checkup starts (right before `Setup()`).
2. After checkup completion (successful or failed.)

"when called once" and "when called more then once", don't emphasize to the reader, on which report are we talking about.

2022-05-08 13:54 UTC, orelmisan commented on kiagnose/internal/reporter/reporter.go
> +func (r *Reporter) Report(statusData status.Status) error {
When you keep the ConfigMap in the reporter's state, you also keep its version.
An update will fail if someone tampers with your ConfigMap object behind your back.
IMO this is the desired behavior.

2022-05-08 14:00 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +}
Please see @EdDev's [comment](https://github.com/kiagnose/kiagnose/pull/45#discussion_r862496080).

We can change it in a later PR if it will disturb us.

2022-05-08 14:01 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +	}
It will cause these lines to be duplicated.

2022-05-08 14:05 UTC, orelmisan commented on kiagnose/internal/reporter/reporter.go
> +	}
The inputs an the outputs of the checkup are strongly connected.
When you are looking at the results, you want to know which inputs has cause them.

By fetching the ConfigMap only once, we ensure that the checkup results / outputs are coming from the checkup inputs defined by the user.

This means that its not possible to change the input during the checkup's execution and prevents unexpected behavior.

2022-05-08 14:08 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +		panic("Report was called more than twice")
Please see @EdDev's [comment](https://github.com/kiagnose/kiagnose/pull/45#discussion_r864696560).

It is done to break the test in case the stub's basic assumptions are broken (for example adding a third report).

2022-05-08 14:12 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +
You are right.

2022-05-08 15:01 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +
Done.

2022-05-08 15:02 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	errorFailOnFinalReport   = errors.New("final report error")
I don't think it grammatically correct.

2022-05-08 15:03 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/862f725325b0b02295d19bfc825b291bad80d3e4..6fe3f9bbcd129c429e978bea3f417f2e9207fc06): Moved the initial report before the deferred function.

2022-05-08 15:27 UTC, EdDev commented on kiagnose/internal/reporter/reporter.go
> +func (r *Reporter) Report(statusData status.Status) error {
> An update will fail if someone tampers with your ConfigMap object behind your back.
> IMO this is the desired behavior.

That is actually a bad side effect.
Someone may touch the object and there is nothing you can do about it. It is expected.
As a simple example, some other controller may label or annotate the configMap.

The only way you are suppose to protect against touching the data is through either a controller or an admission control.
I do not think we need to handle it at the moment, we could be optimistic for now.

I see 3 alternatives:
- Keep it as is and do not support integration with other entities in the k8s client.
- Do not keep the state, and as @ormergi suggested, just fetch it each time and depend on it as the fact.
- Keep the state and at the same time fetch the persisted version, compare the relevant data to see nothing changes, and proceed.

2022-05-08 15:27 UTC, EdDev commented on kiagnose/internal/reporter/reporter.go
> +	}
Commented on the other thread.

2022-05-08 15:27 UTC, EdDev commented on kiagnose/internal/reporter/reporter_test.go
> +	}
@ormergi , What data are you missing in the tests that makes it hard to understand it?

2022-05-08 15:27 UTC, EdDev commented on kiagnose/internal/reporter/reporter_test.go
> +}
When I looked at it, I did not understand what `t.Format(time.RFC3339)` is, and that `RFC3339` tells me nothing useful. It actually makes me go and look for it in the documentation.
But it is a nit, usually I would agree that there is no need to wrap simple stuff.

This is up to the author discretion.

2022-05-09 06:07 UTC, orelmisan commented on kiagnose/internal/reporter/reporter.go
> +	}
> The user ConfigMap `Spec.Data` either empty or nil is semantically the same from the framework perspective, its possible to handle such error (by simply initialize `spec.data`) and there is no need to fail the checkup execution due to that.
> 
> As I mentioned earlier, it will also provide a better UX for the user if it wont fail on such things. Consider the case when a user runs the same checkup twice, between each execution the user will cleanup the config-map data by simply deleting it from the manifest, the framework will then fail due to `Spec.Data` is `nil`.

I see value in keeping the checkup inputs with the checkup outputs.
If the code reaches to the point were the ConfigMap.Data field is nil or empty, it means that someone had deleted the inputs while the checkup is running.
If we go with the approach to just initialize the Data field, in the end there will be only results, with no inputs.

2022-05-09 06:37 UTC, orelmisan commented on kiagnose/internal/reporter/reporter.go
> +func (r *Reporter) Report(statusData status.Status) error {
> * Keep the state and at the same time fetch the persisted version, compare the relevant data to see nothing changes, and proceed.

I favor this approach. We can implement it in a follow-up PR.

2022-05-09 06:56 UTC, EdDev approved these changes

2022-05-09 10:05 UTC, ormergi reviewed
There are 3 different threads discussing similar topic, from my perspective all related to each other : [[1]](https://github.com/kiagnose/kiagnose/pull/45/commits/923d48d847248ec10e73bec9b3c6b906f4119aaa#r867492551) [[2]](https://github.com/kiagnose/kiagnose/pull/45/commits/923d48d847248ec10e73bec9b3c6b906f4119aaa#r867492847) [[3]](https://github.com/kiagnose/kiagnose/pull/45/commits/923d48d847248ec10e73bec9b3c6b906f4119aaa#r862428394)

From what I understand, the current implementation tries to ensure the user `ConfigMap` state is kept in order to ensure that the checkup spec (aka "inputs", anything that is not prefix with "status.") is persisted and wont change or deleted from the user ConfigMap.
Is it correct?

If so, please make sure to mention it the commit message because its not an easy thing to understand for the diff.

Also, I think that the current implementation wont achieve that because the `ConfigMap` can still change at any point of time (which is fine and expected).
Practicality this can be achieved with a controller that will reconcile the `ConfigMap` state 
on change events.

Thus I think the reporter should be simplified and care only for updating the `ConfigMap` data with the new status, and not also ensure the spec is as it was initially (aka "inputs").
Suggestions to simplify the reporter:
- Change reporter to not keep the state of the user `ConfigMap`.
- Always fetch `ConfigMap` at stat of `reporter.Report()`
- At `reporter.Report()` If the user `ConfigMap` `spec.data` is nil do not return immediately.
   Instead do best effort to report what possible and then return meaningful error.
   Checkup execution might be expensive for the user thus the framework should do best effort
   to report the checkup results.

There are planes to use a controller and CRD as replacement for the `ConfigMap`,
persisting the checkup spec (aka "inputs")  can be addressed then.

2022-05-09 10:23 UTC, orelmisan commented on kiagnose/internal/reporter/reporter.go
> +			Data: nil,
Done.

2022-05-09 10:32 UTC, orelmisan commented on kiagnose/internal/reporter/reporter_test.go
> +	t.Run("on checkup start", func(t *testing.T) {
Changed "on checkup start" to "on initial report".

2022-05-09 10:40 UTC, EdDev commented
> There are 3 different threads discussing similar topic, from my perspective all related to each other : [[1]](https://github.com/kiagnose/kiagnose/pull/45/commits/923d48d847248ec10e73bec9b3c6b906f4119aaa#r867492551) [[2]](https://github.com/kiagnose/kiagnose/pull/45/commits/923d48d847248ec10e73bec9b3c6b906f4119aaa#r867492847) [[3]](https://github.com/kiagnose/kiagnose/pull/45/commits/923d48d847248ec10e73bec9b3c6b906f4119aaa#r862428394)

If there are 3 threads speaking on the same topic, opening a 4th one will surely not help and unfocus us.
What I feedback before is [here](https://github.com/kiagnose/kiagnose/pull/45#discussion_r867505854).

If you think it needs to be done differently than what was suggested there, we can discuss it in a PR that tries to improve it.

2022-05-09 10:43 UTC, EdDev approved these changes
Thank you @orelmisan.

I think most of the comments have been answered and the state of the PR seems good to me.
We can continue improving it and I expect to revisit most of the places again pretty soon.

@ormergi , if I missed some critical aspect which you think is totally wrong, please feel free to propose an alternative when time allows.

2022-05-09 10:43 UTC, merged

2022-05-09 14:37 UTC, ormergi commented
> If there are 3 threads speaking on the same topic, opening a 4th one will surely not help and unfocus us. What I feedback before is [here](https://github.com/kiagnose/kiagnose/pull/45#discussion_r867505854).
> 

On the contrary, its confusing to have 3 threads discussing the same thing from different angle.