launcher: Report actual checkup status
kiagnose/kiagnose pull request #46
Opened 2022-05-08 11:11 UTC by orelmisan

This PR replaces the hard-codded implementation with an actual reporting of "succeeded" and "failureReason" fields to the user-supplied ConfigMap object.

This PR also changes the launcher's tests to test the actual final report (in applicable test cases).

Depends on PR #45.

2022-05-08 12:26 UTC, EdDev requested changes
Commit:launcher: Report succeeded and failureReason

I find this commit hard to review.
It includes too many changes, some not related directly with the production code addition.

Can you please perform the refactor of test structure without changing their logic (and what they test) as a pre-step? Then, it should be easy to see what was changed and what was added more easily.

As an example, I am not sure I understand what does it mean "with report" and "without report" in the failure scenarios.

2022-05-08 12:26 UTC, EdDev commented on kiagnose/internal/launcher/launcher.go
> +			statusData.Succeeded = true
I think this needs to be set only after the `Run()` execution.
Here, I would expect to see it set to `false` with the reason in case of an error.

In practice, there is no need to set the success boolean at all. It should be the default in case the value was not raised before.

2022-05-08 12:26 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +		assert.Empty(t, checkupData[reporter.FailureReasonKey])
Can you compare the full data? That would be preferable over multi-asserts.

2022-05-08 12:31 UTC, EdDev reviewed
Passed through the "prefix" commits.

General note: You are using in the commit message a lot of `This` wording. I would recommend reducing its usage to the minimum. It does not add information and looks redundant.

2022-05-08 13:10 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/0a605bbaea9cfaa80f5de4cdfed48a0b81330360..6925c373534baef3367bd3412c54c9cba2efdb67): Added intermediate commits to slowly show the change to `launcher_test.go`.

2022-05-08 13:13 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +			statusData.Succeeded = true
This code is called after the calls to `Run()` and `Teardown()`.

The success boolean is only set to `true` in case of success, and remains as the default `false` otherwise.

2022-05-08 13:15 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +		assert.Empty(t, checkupData[reporter.FailureReasonKey])
It is a bit problematic because the timestamps are set inside a struct local to the `Launcher.Run()` method.
We can expose them, but I don't think the justification is very strong.

2022-05-08 13:18 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/6925c373534baef3367bd3412c54c9cba2efdb67..06480039d92c2e1a1a0758cc4c0a4d0064b78f64): Changed the commit messages to reduce the usage of the word "this".

2022-05-08 15:06 UTC, ormergi reviewed
Hi Orel, thanks for the PR.
Please see my inline comments.

2022-05-08 15:06 UTC, ormergi commented on kiagnose/internal/launcher/launcher_test.go
> +func TestLauncherRunShouldFailWithReport(t *testing.T) {
nit: Please consider renaming to something like `TestLauncherShouldFailWhen` (and remove "when" from tests description), having functioning reporter is the default state.

2022-05-08 15:06 UTC, ormergi commented on kiagnose/internal/launcher/launcher_test.go
> +			reporter.New(fakeClient, configMapNamespace, configMapName),
I think it worth to create another test function when the "production" reporter is being used, 
IMO its confusion to see one test using the "production" component and the rest uses the stub component.

2022-05-09 06:17 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +}
Please see @EdDev's [comment](https://github.com/kiagnose/kiagnose/pull/45#discussion_r863616213) in PR #45.

2022-05-09 06:48 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +}
@orelmisan , I suggested a function instead of a variable. In both cases the end result is hiding the details, and Or was talking about that.

2022-05-09 06:54 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +}
These details are representing the minimal checkup spec.
Why in your opinion are they important to the comprehension of the test?

2022-05-09 07:20 UTC, EdDev reviewed
Reviewed commit `launcher, tests: Move success scenario to a dedicated function`.

2022-05-09 07:20 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("when checkup runs successfully", func(t *testing.T) {
I think the intention is to check that the launcher runs successfully, stubbing (or not) the needed to make it so.

Anyway, lets not over-complicate things... keep it simple.
There is no real need for `t.Run`, there is only one test.

And the test can be called `TestLauncherRunsSuccessfully`.

2022-05-09 07:20 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +func TestLauncherShould(t *testing.T) {
You can place in the name all the common wording from each test below.
I think in this case it is: `TestLauncherShouldFailWhen`.

2022-05-09 07:32 UTC, EdDev reviewed
> launcher, tests: Split failure cases to two functions

launcher, tests: Split failure cases to two groups

> Split the failure cases into two categories:
> 1. Failures that are expected to be reported to the user.
> 2. Failures that are expected to be logged.

You need some overview so one can understand what is this all about.
Something like:
```
When the launcher execution fails, it can result in either the outcome is successfully reported to the user (through the API sever) or no (e.g. unable to access the API server).

To make this distinction clear and allow it to evolve with future scenarios, the two are grouped under different test hierarchies.
```

2022-05-09 10:05 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/06480039d92c2e1a1a0758cc4c0a4d0064b78f64..56f078e848176071e7856385c1de1d2f043ad5e1): Rebased on PR #45.
Changed the order of the commits, so refactor commits comes first.
Kept the old test names.
Retained the reporterStub's ability to fail on the initial report.

2022-05-09 11:03 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/56f078e848176071e7856385c1de1d2f043ad5e1..917f2b820f92b6e2e523000b259b16e0c204631f): Rebase

2022-05-09 11:16 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/917f2b820f92b6e2e523000b259b16e0c204631f..e5a5961c01da9c58c144f852223d3bce55dea342): Updated the 6th commit message and the PR description to explain the logic behind the "succeeded" field.

2022-05-09 11:17 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +			statusData.Succeeded = true
Updated the commit message and the PR description to explain the logic behind "succeeded" field.

2022-05-09 12:41 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/e5a5961c01da9c58c144f852223d3bce55dea342..5901de3f6d8ab95b87a24849d0febf6737a09bdc): Zero the actual reported timestamps before asserting equality with expected values.

2022-05-09 12:43 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +		assert.Empty(t, checkupData[reporter.FailureReasonKey])
The actual timestamps are now zeroed before asserting the actual report equality with the expected results.

2022-05-09 12:47 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +			statusData.Succeeded = true
@ormergi IMO the Status struct should stay a simple data struct.
The logic added to Launcher.Run() is a simple `if` statement.

2022-05-09 12:48 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	t.Run("when checkup runs successfully", func(t *testing.T) {
Removed the redundant `t.Run()`.

2022-05-09 12:49 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +func TestLauncherRunShouldFailWithoutReport(t *testing.T) {
Renamed this to `TestLauncherRunShouldFailWithoutReportWhen`.

2022-05-09 12:49 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +func TestLauncherRunShouldFailWithReport(t *testing.T) {
Renamed to `TestLauncherRunShouldFailWithReportWhen`.

2022-05-09 12:52 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +			reporter.New(fakeClient, configMapNamespace, configMapName),
The tests division is based on whether there will be a report to the user at the end or not.

2022-05-09 12:53 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +func TestLauncherShould(t *testing.T) {
Changed this to:
1. `TestLauncherRunShouldFailWithReportWhen`
2. `TestLauncherRunShouldFailWithoutReportWhen`

2022-05-09 13:20 UTC, EdDev commented on kiagnose/internal/launcher/launcher.go
> +			statusData.Succeeded = true
Ok, you convinced me it is enough for now.

2022-05-09 13:28 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +	zeroTimestamps(actualCheckupData)
It will be nicer if you call this on `expectedData` as well.

2022-05-09 13:57 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +	zeroTimestamps(actualCheckupData)
Done.

2022-05-09 13:58 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/5901de3f6d8ab95b87a24849d0febf6737a09bdc..6af425456486da401b1ce5c577bdd47f67be386e): Answered review comment.

2022-05-09 14:04 UTC, EdDev submitted a review, later dismissed
Thank you!

2022-05-10 06:54 UTC, ormergi reviewed
Regarding "launcher, tests: Check report on failure cases" commit:
What about successful tests are you going to change them to assert on the 
status that reported?

Regarding "launcher, tests: Change test when initial report fails" commit 
the commit message title is not clean, do you think you can add more info about what is going to change?

2022-05-10 06:54 UTC, ormergi commented on kiagnose/internal/launcher/launcher_test.go
> +func TestLauncherRunsSuccessfully(t *testing.T) {
nit: redundant 's' at Runs.

2022-05-10 06:54 UTC, ormergi commented on kiagnose/internal/launcher/launcher.go
> +			statusData.Succeeded = true
This defer function already bloated, it will be nicer if we can reuse some noise from it.
Note that what I suggested can also be static functions at launcher/launcher.go.

2022-05-10 06:54 UTC, ormergi commented on kiagnose/internal/launcher/launcher_test.go
> +}
It will improve visibility and make it easier to understand how the "expectedData" should look like,
The "expectedData" can be defined locally where needed.

This is nice to have..

2022-05-10 06:54 UTC, ormergi commented on kiagnose/internal/launcher/launcher.go
> +
regarding line [67 line](https://github.com/kiagnose/kiagnose/pull/46/commits/0516103cedea0e2314893be7b3733768688a650b#diff-57e7e8036316bd96561318e6d20d9487345e4ac53cb9c3867a324bffeb4d564eR67), it seems that that status "succeeded" is not affected by the reporter, please add a note about it in the commit message.

2022-05-10 06:54 UTC, ormergi commented on kiagnose/internal/launcher/launcher_test.go
> +			expectedData := checkupSpecData()
nit: It would be easier to understand what is the expected results if it was defined inline:
```
expectedData := map[string]string {
    reporter.SucceededKey: ..
    reporter.FailureReasonKey: ..
    config.StartTimestampKey: ..
    config.CompletionTimestampKey: ..
}
```

2022-05-10 07:00 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +func TestLauncherRunsSuccessfully(t *testing.T) {
This is grammatically correct.

2022-05-10 07:02 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +			statusData.Succeeded = true
This is only a temporary step in the way to PR #48.

2022-05-10 07:03 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +}
This could be done in a follow-up PR.

2022-05-10 07:08 UTC, orelmisan commented on kiagnose/internal/launcher/launcher.go
> +
The line you are referring to is the final report. 
If it fails - the user will not get a report.
There is no point in updating a value that will not be reported.

2022-05-10 07:11 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +			expectedData := checkupSpecData()
I agree that it would be nicer, but `expectedData` is comprised of two maps:
1. The minimal spec.
2. All the reported data.

2022-05-10 07:25 UTC, ormergi commented on kiagnose/internal/launcher/launcher_test.go
> +			expectedData := checkupSpecData()
It seems (2) is not reflected in tests, did I miss something?

2022-05-10 07:30 UTC, orelmisan commented on kiagnose/internal/launcher/launcher_test.go
> +			expectedData := checkupSpecData()
Let me rephrase, section 2 is all the expected reported data.
Please see [here](https://github.com/kiagnose/kiagnose/pull/46/files/0516103cedea0e2314893be7b3733768688a650b..4eafc85ed21521162dceae3e2861acfd6acf589c#diff-5bfeeac3b26c7f73c22a1fa3ef5b79ca2f0f2a69eb8d9c27ce1aaf04b40af719R108-R110).

2022-05-10 08:49 UTC, EdDev commented on kiagnose/internal/launcher/launcher_test.go
> +}
To be clear: Visibility makes sense if the data is relevant to the test. If the data is not relevant to the test, it is noise and we do not want to know about it.

2022-05-10 08:54 UTC, orelmisan commented
> Regarding "launcher, tests: Check report on failure cases" commit: What about successful tests are you going to change them to assert on the status that reported?

It was done in the [previous commit](https://github.com/kiagnose/kiagnose/pull/46/commits/0516103cedea0e2314893be7b3733768688a650b) (and stated in its commit message).

> Regarding "launcher, tests: Change test when initial report fails" commit the commit message title is not clean, do you think you can add more info about what is going to change?

The commit message says:
```
Replace the reporter stub with the production reporter code,
in case when the initial report fails.
```

What are you missing?

2022-05-10 09:04 UTC, EdDev commented
> > Regarding "launcher, tests: Change test when initial report fails" commit the commit message title is not clean, do you think you can add more info about what is going to change?
> 
> The commit message says:
> 
> ```
> Replace the reporter stub with the production reporter code,
> in case when the initial report fails.
> ```
> 
> What are you missing?

Maybe he is missing the reasoning behind it.
Also, I am not sure if `in case when the initial report fails` is a valid sentence (that `when` part does not fit).

2022-05-10 09:10 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/6af425456486da401b1ce5c577bdd47f67be386e..50872a90de1cc4f10dff18d41f3f40b85446b193): Updated last commit message.

2022-05-10 09:21 UTC, EdDev commented
> This is done in order to use the production reporter whenever possible.

I am not sure if this qualifies to reasoning.
How about this commit:
```
launcher, tests: Use production reporter instead of stub

The test that covers the scenario in which the report fails to
post the start timestamp is currently using a reporter stub.

In order to cover a more realistic scenario (and setup), the
stub is replaced with the production reporter.
```

2022-05-10 09:27 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/50872a90de1cc4f10dff18d41f3f40b85446b193..6f563a7ba21053ef518ffa931586f6f0001831c4): Changed last commit message.

2022-05-10 09:37 UTC, ormergi commented on kiagnose/internal/launcher/launcher_test.go
> +func TestLauncherRunsSuccessfully(t *testing.T) {
Now I realized it doesnt mention `launcher.Run()`.

2022-05-10 09:40 UTC, ormergi commented on kiagnose/internal/launcher/launcher.go
> +			statusData.Succeeded = true
Alright, fair enough.

2022-05-10 09:43 UTC, ormergi commented on kiagnose/internal/launcher/launcher_test.go
> +			expectedData := checkupSpecData()
It doenst seem to be a problem, the expectedData can include what necessary in any case.

We can address it later this is nice to have.

2022-05-10 09:45 UTC, ormergi commented on kiagnose/internal/launcher/launcher.go
> +
It will matter when we will log the status that is about to be written to the ConfigMap, but this is not the scope of this PR.

2022-05-10 09:46 UTC, ormergi approved these changes
Thanks

2022-05-10 09:47 UTC, merged