kubevirt-vm-latency: Spin up VM's
kiagnose/kiagnose pull request #55
Opened 2022-05-11 13:14 UTC by ormergi

With this PR changes the Kubevirt VM lantecy checkup will spin up two SR-IOV VM's.

Depends on #41 and #49, only last 4 commits should be reviewd.

2022-05-11 17:25 UTC, ormergi commented
Rebased

2022-05-11 18:51 UTC, orelmisan reviewed
Thank you @ormergi for the PR!
Please see the inline comments for the first commit.

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/go.mod
> +	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
Can you please describe in the commit message what is this package and why do we need it?

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/go.mod
> +	k8s.io/apimachinery v0.23.5
Several lines below you are replacing these to 0.23.1, is it necessary?

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/cloudinit.go
> +package vmgenerator
Can you please explain in the commit message what this file / package does?

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/cloudinit.go
> +package vmgenerator
Can you please add the licence comment?

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +package vmgenerator
Can you please add the licence comment?

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	nodeName string) *kvcorev1.VirtualMachineInstance {
Can you please pass a config struct(s) instead of seven arguments?

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	vmi.Spec.TerminationGracePeriodSeconds = &terminationGracePeriodSeconds
I've seen this trick in Learning Go:
```go
func int64ptr(n int) *int64 {
   return &n
}

vmi.Spec.TerminationGracePeriodSeconds = int64ptr(defaultTerminationGracePeriodSeconds)
```

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	addSriovNetwork(vmi, networkName, netAttachDefNamespace+"/"+netAttachDefName, macAddress, cidr)
Please consider extracting this part to a function:
```
netAttachDefNamespace+"/"+netAttachDefName
```

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	vmi.Spec.Domain.Devices.Interfaces = append(vmi.Spec.Domain.Devices.Interfaces, masqueradeInterface("pod"))
Why `masqueradeInterface` and not bridge for example?

2022-05-11 18:51 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +		))
nit: can the second `)` be in a line of its own?

2022-05-11 19:26 UTC, orelmisan reviewed
Second commit.

2022-05-11 19:26 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	return &checkup{client: c, namespace: workingNamespace, params: params}
```suggestion
return &checkup{
  client: c, 
  namespace: workingNamespace, 
  params: params
  }
```

2022-05-11 19:26 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	WorkingNamespace                     string
Why are there two copies of this? (one here and another in the checkup's state)

2022-05-11 19:26 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +	}
This looks like a leftover.

2022-05-11 19:41 UTC, orelmisan reviewed
Third commit.

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
>  }
Can you please move it above the `SetSetupTimeout` method so it can be the first function?

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		sourceVmiMac, sourceVmiCidr, c.params.SourceNodeName)
I've suggested in a previous commit to pass there parameters inside one or two structs (one for the NAD and another for the rest).

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	if err := c.client.WaitForVmisReady(ctx, sourceVmi, targetVmi); err != nil {
nit: can you please add a newline here?

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +	t.Run("failed to create VM", func(t *testing.T) {
```suggestion
t.Run("failed to create a VM", func(t *testing.T) {
```

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCheckup := checkup.New(&clientStub{failStartVmis: expectedError}, "", newTestsCheckupParameters())
```suggestion
testCheckup := checkup.New(
  &clientStub{failStartVmis: expectedError },
   "",
    newTestsCheckupParameters(),
 )
```

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +	t.Run("VMI was not ready on time", func(t *testing.T) {
```suggestion
t.Run("VMI was not ready before timeout expiration", func(t *testing.T) {
```

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCheckup := checkup.New(&clientStub{failWaitForVmisReady: expectedError}, "", newTestsCheckupParameters())
Same suggestion as above.

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +}
Can you please consider moving these methods to the vmi package as functions?

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +package checkup_test
Missing licence comment.

2022-05-11 19:41 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/vmi/vmi.go
> +package vmi
Missing the licence comment.

2022-05-11 19:47 UTC, orelmisan reviewed
Forth commit.

2022-05-11 19:47 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +func (c *checkup) SetTeardownTimeout(duration time.Duration) {
```suggestion
func (c *checkup) SetTeardownTimeout(timeout time.Duration) {
```

2022-05-11 19:47 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	defer cancel()
Is this a leftover from old usage of another context?

2022-05-11 19:47 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	var errs []string
```suggestion
var errs []error
```

2022-05-11 19:47 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	}
Please see PR #52, it has something similar.

2022-05-11 19:47 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +	testTimeout               = time.Millisecond
Why has this changed here?

2022-05-11 20:35 UTC, orelmisan commented
@ormergi, Can you please add manifest files to:
1. Deploy the relevant ClusterRole (with the required permissions so far).
2. Configure and run this checkup (similar to what we have for the echo checkup).

2022-05-12 05:29 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/cloudinit.go
> +package vmgenerator
It will be also polite to specify its source of origin.

2022-05-12 05:59 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/cloudinit.go
> +	"gopkg.in/yaml.v3"
The usage of this package requires `yaml` annotations when defining the structs.
You cloned the file but changed this part, very odd.

2022-05-12 05:59 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	addPodNetwork(vmi)
Why do we need the pod network in the VM? If I am not mistaken, we are suppose to test just a single network, i.e. a single vNIC that its connection was defined in the NAD.
We are talking only about the secondary networks.

2022-05-12 05:59 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +		containerDiskName        = "alpine"
I do not understand how this was composed.
- Alpine requires very small memory, in the range of 128M - 256M to work.
- By default, it does not support could-init, but this commit hints it is needed.

2022-05-12 05:59 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	vmi.Spec.TerminationGracePeriodSeconds = &terminationGracePeriodSeconds
For some reason this looks familiar. See [here](https://github.com/kiagnose/kiagnose/blob/f7184d332626ee159502b43488258d4306e9c0ae/kiagnose/internal/checkup/checkup.go#L217).

2022-05-12 06:29 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	vmi.Spec.TerminationGracePeriodSeconds = &terminationGracePeriodSeconds
> For some reason this looks familiar. See [here](https://github.com/kiagnose/kiagnose/blob/f7184d332626ee159502b43488258d4306e9c0ae/kiagnose/internal/checkup/checkup.go#L217).

I remember this code.
I find the usage of const + a function that returns a pointer to its parameter cleaner.

2022-05-12 11:27 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/ee0c76fca865b04dfc892ca051ae42349bdcd3bc..f2a806d72941fd69e3a8523fb6ce7c9c914cbe3d): Rebased to latest main in order to get #49 changes

2022-05-12 12:25 UTC, ormergi reviewed
[Changes](https://github.com/kiagnose/kiagnose/compare/f2a806d72941fd69e3a8523fb6ce7c9c914cbe3d..08dc03bf9844c690690f988d21c04b17f5fb9b2d): Addressed "kubevirt-vm-latency: Introduce vm-generator" review comments

2022-05-12 12:25 UTC, ormergi commented on checkups/kubevirt-vm-latency/go.mod
> +	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
Following [[1]](https://github.com/kiagnose/kiagnose/pull/55/commits/54012531f84b30928672199a4fbe396da6b0437e#r870963787), now `sigs.k8s.io/yaml` is being used by cloidinit.go, I updated the commit message.

2022-05-12 12:28 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	return &checkup{client: c, namespace: workingNamespace, params: params}
Done

2022-05-12 12:39 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/08dc03bf9844c690690f988d21c04b17f5fb9b2d..41025dfafe9396a6c287854ce10769c98d508fd3): Fixed commit message and reference link

2022-05-12 12:51 UTC, ormergi reviewed
[Changes](https://github.com/kiagnose/kiagnose/compare/41025dfafe9396a6c287854ce10769c98d508fd3..4051c0db1040cf735d06b54d88ce3523685d3c74): Addressed "kubevirt-vm-latency: Read namespace file and pass it to checkup
" commit review comments

2022-05-12 12:51 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	return &checkup{client: c, namespace: workingNamespace, params: params}
Done

2022-05-12 12:51 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
> +	WorkingNamespace                     string
Thanks for the heads up, this is a left over I removed it.

2022-05-12 12:51 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +	}
Sorry for the noise, it is a left over, I removed it.

2022-05-12 12:52 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	vmi.Spec.Domain.Devices.Interfaces = append(vmi.Spec.Domain.Devices.Interfaces, masqueradeInterface("pod"))
I was just looking for the reasoning.

This is a better [link](https://github.com/kiagnose/kiagnose/pull/55#discussion_r870968794) to the relevant thread.

2022-05-12 12:56 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	vmi.Spec.TerminationGracePeriodSeconds = &terminationGracePeriodSeconds
This should have been `func int64ptr(n int64) *int64 {`.
I wrote it late at night...

2022-05-12 13:07 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +		alpineContainerDiskImage = "quay.io/kubevirt/fedora-with-test-tooling-container-disk:v0.53.0"
@ormergi Please take a look at [this](https://groups.google.com/g/kubevirt-dev/c/siDqS8hgvFo) post in the kubevirt's mailing list. 
Furthermore, the container disk image is fedora but the const name is alpine.

2022-05-12 13:15 UTC, ormergi reviewed
[Changes](https://github.com/kiagnose/kiagnose/compare/4051c0db1040cf735d06b54d88ce3523685d3c74..1b84913391a86bfd8a91a8e03c4c59200139c4d5): Address "kubevirt-vm-latency: Create VMs on setup" commit review comments.

2022-05-12 13:15 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +	t.Run("failed to create VM", func(t *testing.T) {
Done

2022-05-12 13:15 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCheckup := checkup.New(&clientStub{failStartVmis: expectedError}, "", newTestsCheckupParameters())
Done

2022-05-12 13:15 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +	t.Run("VMI was not ready on time", func(t *testing.T) {
Done

2022-05-12 13:15 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCheckup := checkup.New(&clientStub{failWaitForVmisReady: expectedError}, "", newTestsCheckupParameters())
Done

2022-05-12 13:15 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	if err := c.client.WaitForVmisReady(ctx, sourceVmi, targetVmi); err != nil {
Done

2022-05-12 13:38 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/1b84913391a86bfd8a91a8e03c4c59200139c4d5..7cdc79cea926b11e4cd71bd83775582fdbeda482): Move functions from vmi.go to client.go.

2022-05-12 13:39 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/1b84913391a86bfd8a91a8e03c4c59200139c4d5..7cdc79cea926b11e4cd71bd83775582fdbeda482): Move functions from vmi.go to client.go, @orelmisan let me know if this what you meant.

2022-05-12 13:39 UTC, ormergi reviewed
[Changes](https://github.com/kiagnose/kiagnose/compare/7cdc79cea926b11e4cd71bd83775582fdbeda482..43f2849ab2265f1ad5794370457dd2bf70965926): Addressed "kubevirt-vm-latency: Delete VMs on teardown" commit review comments.

2022-05-12 13:39 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +func (c *checkup) SetTeardownTimeout(duration time.Duration) {
Done

2022-05-12 13:39 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	defer cancel()
It was added before we discussed about using context and timeouts,
I think this should remain at least for the `WaitVmisDispose` which is long blocking operation.
@orelmisan @EdDev WDYT?

2022-05-12 13:39 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	}
Note that in #52 at the end `[]string` was expected, here we need to return an error.

2022-05-12 13:39 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +	testTimeout               = time.Millisecond
This is a leftover, sorry for the noise, I removed it.

2022-05-12 13:47 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/43f2849ab2265f1ad5794370457dd2bf70965926..dd5ee51a7aa93206bd220514430a7a955d51af24): fix VM image variable name, @orelmisan note that this is different image and its maintained.

2022-05-12 13:51 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/dd5ee51a7aa93206bd220514430a7a955d51af24..f22a0493a1c0c6c71a46081d26ae7527f244ccb8): Move `checkup.New()` closer to the type definition

2022-05-12 13:52 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +		alpineContainerDiskImage = "quay.io/kubevirt/fedora-with-test-tooling-container-disk:v0.53.0"
Done, note that this is different image and its maintained.

2022-05-12 13:54 UTC, ormergi commented on checkups/kubevirt-vm-latency/go.mod
> +	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
I mean for this https://github.com/kiagnose/kiagnose/pull/55#discussion_r870963787

2022-05-12 13:57 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	defer cancel()
I think we should keep it.

2022-05-12 14:25 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCheckup := checkup.New(&clientStub{failStartVmis: expectedError}, "", newTestsCheckupParameters())
nit: I suggest to put the last `)` on a line of its own.

2022-05-12 14:27 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/vmi/vmi.go
> +package vmi
It is still missing.

2022-05-12 15:03 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	var errs []string
This is related to https://github.com/kiagnose/kiagnose/pull/55#discussion_r870687760

2022-05-12 15:32 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/f22a0493a1c0c6c71a46081d26ae7527f244ccb8..0663fd5cf88237fb26d76de2bba8b673f6e6d5f3): revert https://github.com/kiagnose/kiagnose/pull/55#issuecomment-1125008793

2022-05-13 08:43 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/vmi/vmi.go
> +package vmi
Done

2022-05-13 08:44 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/0663fd5cf88237fb26d76de2bba8b673f6e6d5f3..17d813f5ce237a9aee5183e69146c5a4819a7231): Fix license headers, rename variable names at `vmgenerator`

2022-05-13 08:56 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/17d813f5ce237a9aee5183e69146c5a4819a7231..a4e3dce6b3761273ca80cb6d0d57dd3fff81cb1f): Set the VM's system to boot first explicitly, it prevents from cloudinit disk to boot first.
it seems that if no boot order is set, the disk will boot the they order in the VM spec.

2022-05-13 09:37 UTC, ormergi commented
@EdDev @orelmisan I added manifests and readme.
I verified that the manifests are valid and the checkup is working on a local setup, please take another look.

2022-05-13 13:46 UTC, orelmisan commented
Thank you for the changes @ormergi!
Is it possible to please split the README file to a separate PR?
Unlike the manifests, it is not mandatory for the ability to run the checkup.

2022-05-15 06:56 UTC, EdDev requested changes
> In K8s each in container there is a file that containes its namespace
by default.

I do not understand this sentence.

2022-05-15 06:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/cloudinit.go
> + * source: https://github.com/kubevirt/kubevirt/blob/v0.53.0/tests/libnet/cloudinit.go
I am not familiar with such an annotation in the license itself. Do you have some ref for other projects doing the same with this license type?
You could document the package itself and then add such a contribution there.

2022-05-15 06:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> + * source: https://github.com/kubevirt/kubevirt/blob/v0.53.0/tools/vms-generator/utils/utils.go
Same

2022-05-15 06:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	kvcorev1 "kubevirt.io/api/core/v1"
nit: Please separate imports per domain (with newline).

We need to find a formatter that does this automatically.

2022-05-15 06:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	nodeName string) *kvcorev1.VirtualMachineInstance {
Or use the build pattern.
I am not really sure why two patterns have been used.

2022-05-15 06:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +		containerDiskName        = "alpine"
These are not in sync.
I would also suggest using the new Alpine with tooling, but it is not a must for this PR.

2022-05-15 06:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	addSriovNetwork(vmi, networkName, netAttachDefNamespace+"/"+netAttachDefName, macAddress, cidr)
I would be fine with just `strings.Join(...)`, but I do not mind also a function.

2022-05-15 06:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	addSriovNetwork(vmi, networkName, netAttachDefNamespace+"/"+netAttachDefName, macAddress, cidr)
Maybe I missed something, but this seems to support SR-IOV only interfaces. I thought we are suppose to support it per the NAD definition.

2022-05-15 06:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +func New(c *client.Client, workingNamespace string, params config.CheckupParameters) *checkup {
nit: In this context, the "working" prefix has no meaning (it has a meaning to the caller maybe). I suggest to drop it.

2022-05-15 06:56 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +func Run(env map[string]string, workingNamespace string) error {
Same, I suggest dropping `working` prefix.

2022-05-15 07:00 UTC, EdDev reviewed
Commit `kubevirt-vm-latency: Read namespace file and pass it to checkup`:

Could you please elaborate in the commit message about:
- The expectation of the executable to be run in a kubernetes pod, where the namespace file is mounted.
- The decision to create VM/s in the namespace from which the checkup is executed. After all, this was not the decision taken from the ConfigMap (it was passed from kiagnose as input).

2022-05-15 07:29 UTC, EdDev requested changes
Commit `kubevirt-vm-latency: Create VMs on setup`:

- The change includes some changes (/fix) to the containerdisk, which is a different topic to the spinning of VM/s. I think it merits its own commit with a proper explanation.
It may also be a reasonable simple amend to the commit that introduced it all in the first tplace.
- The mentioning of SR-IOV is mentioned here explicitly for the first time. Please help the reviewer understand why it is now supporting only that and not the general scenario (I would claim it needs to be mentioned a commit before this one).
- The existence of two packages, `vmigenerator` and `vmi`, seems a bit strange to me.
How is the split of the two helps here? Unless you have a specific reason not to do so, I would suggest to place both under a `vmi` package, with two files: `spec` and `operation`. And you could also consider placing the operations as methods.

2022-05-15 07:29 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +func addSystemContainerDiskVolume(vmi *kvcorev1.VirtualMachineInstance, volumeName, image string) {
I am not sure I really like this usage of the boot order.
The building blocks used in [libvmi](https://github.com/kubevirt/kubevirt/blob/main/tests/libvmi/storage.go) seems to work fine. Adding disks in the right order can also be done here, so placing this hard definition seems unneeded. Is there some hidden reason behind all this that I missed?

2022-05-15 07:29 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/vmi/vmi.go
> +func StartVmis(ctx context.Context, c kubecli.KubevirtClient, vmis ...*kvcorev1.VirtualMachineInstance) error {
I would prefer you call each from the caller explicitly, having such a wrapper does not give any special abstraction.
Even further, all the helpers that try to handle a collection of VMI/s, I think should not exist.

2022-05-15 07:29 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +func (c *Client) StartVmis(ctx context.Context, vmis ...*kvcorev1.VirtualMachineInstance) error {
I think this is limiting the client to a very specific use case and makes it harder to evolve it.
The `client` should be a simple proxy to the actual client and not attempt to wrap it with logic (even if it is a simple one). We do not know how will the callers evolve and by doing this logic wrapping it limits what can be done.

I have suggested a way to organize the spec and operation of VMI/s, please consider that one.

2022-05-15 08:01 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		teardownTimeout: defaultTeardownTimeout,
Why this needs to reside in the object state? It looks to me like it is an internal value taken from a const.
I guess I should have asked the same about `setupTimeout`.

2022-05-15 08:54 UTC, ormergi reviewed
@EdDev I answered to few comments I wasn't sure about.

2022-05-15 08:54 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	nodeName string) *kvcorev1.VirtualMachineInstance {
> Or use the build pattern.

I didn't picked the builder pattern here since the is only one VM variant and to keep the implementation simple,
you think its better fit in anycase?

> I am not really sure why two patterns have been used

What you mean?

2022-05-15 08:54 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +		containerDiskName        = "alpine"
It was changed at "kubevirt-vm-latency: Create VMs on setup" commit, I will move it to this commit.

> I would also suggest using the new Alpine with tooling, but it is not a must for this PR.

I wasn't aware there such image, does it support cloudinit?

2022-05-15 08:54 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +func addSystemContainerDiskVolume(vmi *kvcorev1.VirtualMachineInstance, volumeName, image string) {
While testing this PR on local setup, it seemed that if the boot order is not configured explicitly the disks boot order will be as it is in the VMI spec, the VM did not boot until I changed the order of the disks in the spec
in a way that the system disk is first.

Note that [libvmi](https://github.com/kubevirt/kubevirt/blob/main/tests/libvmi/factory.go#L39) exposes few factories that make sure that the system disk is added first by placing it at the first at options array.
But If the order is changed so that different disk will be added first, the VM wont boot.
In Kubevirt it is covered by e2e tests, as if the order is messed a PR wont pass CI.

In general I think that its wrong to not set boot order explicitly when there is more then one disk in the spec.

Here we have dont have e2e tests just yet, instead of changing the order of lines 63-64 I decided to set the boot order of the system disk explicitly.
So that if the caller "NewLatencyCheckVmi" is mistakenly changes in a way that cloudinit disk is added first, 
the OS disk wont boot first and this checkup breaks.

2022-05-15 08:54 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		teardownTimeout: defaultTeardownTimeout,
It was necessary to add `teardownTimeout` and expose `SetTeardownTimeout()` in order to control it in [tests](https://github.com/kiagnose/kiagnose/pull/55/commits/a4e3dce6b3761273ca80cb6d0d57dd3fff81cb1f#diff-9ab680d21e50243435b2107de32e969fa3a3ace87ac5b42d714af101bdbbc97cR77).
If `teardownTimeout` were locals at `Teardown() `the tests would hang until the timeout is reached.
Same goes for `setupTimeout` and `SetSetupTimeout()`.

2022-05-15 08:54 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/vmi/vmi.go
> +func StartVmis(ctx context.Context, c kubecli.KubevirtClient, vmis ...*kvcorev1.VirtualMachineInstance) error {
Note that having such helpers (that handle connection of VMI's) reduce noise from the caller (checkup.Run()),
this is why I added them in the first place.
You think its better to have their logic at the caller in anycase?

2022-05-15 08:54 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	addSriovNetwork(vmi, networkName, netAttachDefNamespace+"/"+netAttachDefName, macAddress, cidr)
I think I missed it, I thought it should be implemented at another phase of this checkup.

Do you prefer it to be part of this PR? 
if not I will do it on a followup PR.

2022-05-15 09:16 UTC, ormergi commented
@EdDev 
> Commit `kubevirt-vm-latency: Create VMs on setup`:
> 
> * The change includes some changes (/fix) to the containerdisk, which is a different topic to the spinning of VM/s. I think it merits its own commit with a proper explanation.
>   It may also be a reasonable simple amend to the commit that introduced it all in the first tplace.

Sorry for this mess I will move the changes to the first commit (that introduce this logic).

> * The mentioning of SR-IOV is mentioned here explicitly for the first time. Please help the reviewer understand why it is now supporting only that and not the general scenario (I would claim it needs to be mentioned a commit before this one).

I missed this one, it should have support the generic case.
Do you mind if I will implement the generic case in a followup PR?

> * The existence of two packages, `vmigenerator` and `vmi`, seems a bit strange to me.
>   How is the split of the two helps here? Unless you have a specific reason not to do so, I would suggest to place both under a `vmi` package, with two files: `spec` and `operation`. And you could also consider placing the operations as methods.

With the current implementation, `client/vmi` includes the "operations" and `checkup/vmigenerator` includes the "spec",
it is splitted that way to reduce noise from the callers at `checkup` (Setup(), Teardown()..).
Putting all your comments together regarding this topic:
- `internal/client` - will wrap the most basic operations of Kubevirt client (create, delete..)
- `internal/vmi/spec.go` - provide factory for the checkup VMs spec.
- `internal/vmi/operation.go` - provide helpers for managing the VMs (start, wait, console, ping..)
Is that what you suggest?

2022-05-15 09:24 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	nodeName string) *kvcorev1.VirtualMachineInstance {
> I didn't picked the builder pattern here since the is only one VM variant and to keep the implementation simple

The same reasoning conflicts with the implementation in coudinit, no?

> you think its better fit in anycase?

I think there is a need to keep consistency.
The build pattern has the advantage of reading a bit nicer and resolves the large amount of arguments passed in as a side effect.
Does it merits its usage? I cannot say for sure.

2022-05-15 09:27 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	nodeName string) *kvcorev1.VirtualMachineInstance {
> What you mean?

`cloudinit` implementation uses the build pattern, while here you use a more "classic" pattern of mutating an existing object on a procedural manner.

2022-05-15 09:30 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +		containerDiskName        = "alpine"
Yes, it originated [here](https://github.com/kubevirt/kubevirtci/pull/770). It is already used in [kubevirt e2e tests](https://github.com/kubevirt/kubevirt/blob/00b1544db6b7ef8ef19e10509544784e0475be7a/tests/libvmi/factory.go#L78).

2022-05-15 10:00 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/cloudinit.go
> + * source: https://github.com/kubevirt/kubevirt/blob/v0.53.0/tests/libnet/cloudinit.go
Either drop it from here or place it in a package doc, whatever you prefer.
Unless you find a ref about doing this as it is presented in the change here.

2022-05-15 10:00 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	addSriovNetwork(vmi, networkName, netAttachDefNamespace+"/"+netAttachDefName, macAddress, cidr)
It is fine to do it in a following PR, just please make it clear in this PR that this is the case.

2022-05-15 10:00 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +func addSystemContainerDiskVolume(vmi *kvcorev1.VirtualMachineInstance, volumeName, image string) {
I think I covered this by saying:
> Adding disks in the right order can also be done here

The caller that constructs the VMI spec controls its correct composition. AFAIK we are not developing a generic library such that someone can create the same in a different order.
Everything is under "our" control, and explicitly setting the boot order by using dedicated parameters in the spec has no better outcome than defining/building the spec in the right order. All parts are hard-coded in this application.

I can even reason that imposing the boot order as you did will not fit all options in the future. A future author may think the order is per the ordering in the spec, and be surprised that it is hard-coded in the helpers to a specific one.
But this is not the strongest reasoning for not doing this, the strongest reasoning is just that this is not the minimum needed to accomplish the objective. And I personally think the spec should be minimalistic, as each parameter used in it requires maintenance (e.g. knowing what it is and how it affects the VM).

2022-05-15 10:00 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/vmi/vmi.go
> +func StartVmis(ctx context.Context, c kubecli.KubevirtClient, vmis ...*kvcorev1.VirtualMachineInstance) error {
I think that showing that **two** VMI/s have been called is informative and does not create noise.

2022-05-15 10:00 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		teardownTimeout: defaultTeardownTimeout,
You could have passed the values as an argument to the respective method.
Or even pass in a context to these methods (which may fit nicer, as it expresses that the caller controls this timeout).

2022-05-15 10:55 UTC, EdDev commented
> Do you mind if I will implement the generic case in a followup PR?

Sounds good to me.

> With the current implementation, `client/vmi` includes the "operations" and `checkup/vmigenerator` includes the "spec", it is splitted that way to reduce noise from the callers at `checkup` (Setup(), Teardown()..). Putting all your comments together regarding this topic:
> 
>     * `internal/client` - will wrap the most basic operations of Kubevirt client (create, delete, console..)
> 
>     * `internal/vmi/spec.go` - provide factory for the checkup VMs spec.
> 
>     * `internal/vmi/operation.go` - provide helpers for managing the VMs (start, wait, console, ping..)
> 
> 
> Is that what you suggest?

Yes, exactly.

2022-05-15 20:00 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/5a7919f6035fd61a1734be717de834c3077b9f1b..adb6bdaa264d45793507cb4a0f5d66719740e424): Rename vmgenerator `internal/checkup/vmigenerator` with `internal/vmi, and change its implementation to builder pattern.

2022-05-15 20:06 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/adb6bdaa264d45793507cb4a0f5d66719740e424..1c673fc0ee7727def10d345f6ce14ee6c24fa396): update go.mod file, no new files.

2022-05-16 06:14 UTC, EdDev reviewed
First commit review

2022-05-16 06:14 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/cloudinit.go
> +		}
I do not think this is needed.

2022-05-16 06:15 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/1c673fc0ee7727def10d345f6ce14ee6c24fa396..464b935a34ea4a977bd44eceda0dca8c4c96e7f0): 
- Move `internal/client/vmi` code to `internal/vmi`
- Change `client` to wrap the most basic Kubevirt client commands.
- Change `checkup` and `launcher` test following the changes to `client` and `vmi`.

2022-05-16 07:07 UTC, ormergi commented
Changes:
- [[1]](https://github.com/kiagnose/kiagnose/compare/524cb33a09ecc91047a755bd77182cb5d0ccc5f2..464b935a34ea4a977bd44eceda0dca8c4c96e7f0) revert adding commits instead of editing.
- [[2]] https://github.com/kiagnose/kiagnose/compare/464b935a34ea4a977bd44eceda0dca8c4c96e7f0..764d89656eb4d9503243eace37c436d921762350 get rid of helpers that handle collection of VMs.

2022-05-16 07:13 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/764d89656eb4d9503243eace37c436d921762350..bfd97edbbbf8ffbb541e69f4065054dc68b33c84): Reorder  failing checkup teardown tests.

2022-05-16 07:19 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +// https://github.com/kubevirt/kubevirt/blob/v0.53.0/tools/vms-generator/utils/utils.go
Yes `libvim` is all that needed, this is a left over sorry for the noise, I will remove it.

2022-05-16 07:24 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/cloudinit.go
> +		}
It is being used in order to set static IP address to the secondary NIC using cloudinit [[1]](https://github.com/kiagnose/kiagnose/compare/5a7919f6035fd61a1734be717de834c3077b9f1b..adb6bdaa264d45793507cb4a0f5d66719740e424#diff-d60aa090110dbe4421acf2db6a61ce9c88ae82264bd0e66ddc999917378b3c22R135)

2022-05-16 09:34 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/bfd97edbbbf8ffbb541e69f4065054dc68b33c84..8702e13314285c22094335fb4a77b4696e2dc8a1): 
- Remove `cloudinit` `withNamespace()`, instead namespace will be passed on creation of VMs.
- Use Kubevirt API `DiskBusVirtio`
- Fix package `vmi` description
- Update commit messages of first two commits

2022-05-16 09:36 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +	const virtioBus = "virtio"
Thanks for the heads up, done.

2022-05-16 09:37 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +func withNamespace(namespace string) Option {
I removed this func and changed the code to pass the namespace on creation.

2022-05-16 10:21 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/8702e13314285c22094335fb4a77b4696e2dc8a1..d3c19c905aae6208179406c872500ef9b4f45c2c): Change checkup.Setup() and checkup.Teardown() to receive a context to control their time out instead of exposing methods.

2022-05-16 10:22 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		teardownTimeout: defaultTeardownTimeout,
Done.

2022-05-16 10:26 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +func (c *Client) StartVmis(ctx context.Context, vmis ...*kvcorev1.VirtualMachineInstance) error {
Thanks for explaining, I agree it less flexible the benefit is that it makes it much easier to test,
and for this checkup I think there will be no need for the client to be flexible.

Having said that I do agree we cant predict how it will evolve, and the the fact that
there is no single package that handles such things.
I changed `client` to  wrap the most basic operations of Kubevirt client.

2022-05-16 10:28 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/vmi/vmi.go
> +func StartVmis(ctx context.Context, c kubecli.KubevirtClient, vmis ...*kvcorev1.VirtualMachineInstance) error {
Thanks for explaining, I agree it will surly improve visibility.
I removed the helpers that handle VMs collections.

2022-05-16 10:38 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +		containerDiskName        = "alpine"
Thanks for the heads-up I changed it to use alpine-with-test-tooling image.

2022-05-16 10:40 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	kvcorev1 "kubevirt.io/api/core/v1"
Done, all over.

I suggest to not be strict about it until there will be such formatter, its very easy to miss it.

2022-05-16 10:41 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/cloudinit.go
> + * source: https://github.com/kubevirt/kubevirt/blob/v0.53.0/tests/libnet/cloudinit.go
Thanks for the heads up, I changed it to be the package doc.

2022-05-16 10:42 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	defer cancel()
I changed it so that context is used when waiting for VMs to be ready.

2022-05-16 10:42 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCheckup := checkup.New(&clientStub{failStartVmis: expectedError}, "", newTestsCheckupParameters())
Done

2022-05-16 10:45 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +	nodeName string) *kvcorev1.VirtualMachineInstance {
Thanks for explaining, I changed it  follow the builder pattern.
Looking at this again its more clear that its worth to follow the builder pattern in this case as it improve readability, it worth the cost of the overhead it brings.

2022-05-16 10:47 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/d3c19c905aae6208179406c872500ef9b4f45c2c..82ec80b0259b6173aefad02c0e6c5e36532fca84): rename `workingNamespace` to just `namespace` where there is no need for it.

2022-05-16 10:48 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +func Run(env map[string]string, workingNamespace string) error {
Done

2022-05-16 10:48 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +func New(c *client.Client, workingNamespace string, params config.CheckupParameters) *checkup {
Done

2022-05-16 10:48 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> + * source: https://github.com/kubevirt/kubevirt/blob/v0.53.0/tools/vms-generator/utils/utils.go
Done

2022-05-16 10:49 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +		alpineContainerDiskImage = "quay.io/kubevirt/fedora-with-test-tooling-container-disk:v0.53.0"
Note that now the image is change to alpine-with-test-tooling.

2022-05-16 10:56 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/vmgenerator/vmgenerator.go
> +func addSystemContainerDiskVolume(vmi *kvcorev1.VirtualMachineInstance, volumeName, image string) {
Thanks for explaining, I removed explicit boot order definition for now as part of changing the implementation to follow the builder pattern.

I still think its good practice to set the boot order explicitly as long Kubevirt will set the boot order by default (intentionally or not), it should be considered it as the system-disk that should be booted first.
In wonder if the a VM system disk should be expressed explicitly in the API,
this discussion would be obsolete if there was systemDisk attribute in the VM spec,
it seems that its not a thing.

2022-05-16 10:59 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/82ec80b0259b6173aefad02c0e6c5e36532fca84..7e080d983c68805760585799dc51931256cf194a) removed the commit that adds readme, I will add it in a follow up PR.

2022-05-16 11:33 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/cloudinit.go
> +		}
Again, these 3 lines are not needed.
See [here](https://github.com/kubevirt/kubevirt/pull/7748).

2022-05-16 11:58 UTC, EdDev reviewed
First two commits still have open issues.

2022-05-16 11:58 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +func Run(env map[string]string, workingNamespace string) error {
Sill here

2022-05-16 12:20 UTC, orelmisan reviewed
Suggestion for the first commit message:
```
kubevirt-vm-latency: Introduce vmi package
The 'vmi' package provides a factory for generating Kubevirt[1] VMs that will be used by the
checkup.
It is built form Kubevirt's 'libvmi' [2] and 'libnet' [3] packages, stripped down to meet the checkup's needs.

Also go.mod file is updated, no new files were added:
- 'kubevirt.io/api' and 'k8s.io/api' are no longer indirect import since they are
   being used directly.
- 'sigs.k8s.io/yaml' required by vmi/cloudinit.go.
[1] https://kubevirt.io
[2] https://github.com/kubevirt/kubevirt/blob/v0.53.0/tests/libvmi
[3] https://github.com/kubevirt/kubevirt/blob/v0.53.0/tests/libnet

Signed-off-by: Or Mergi <ormergi@redhat.com>
```

2022-05-16 12:27 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +func New(c *client.Client, workingNamespace string, params config.CheckupParameters) *checkup {
I moved the change to the right commit (second commit)

2022-05-16 12:27 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/mainflow.go
> +func Run(env map[string]string, workingNamespace string) error {
I moved the change to the right commit (second commit)

2022-05-16 12:32 UTC, orelmisan reviewed
Regarding the second comment message "kubevirt-vm-latency: Read namespace file and pass it to checkup":

> The framework also supports passing parameters to a checkup by specifying it in
the user ConfigMap.

This sentence is confusing.
The framework passes the configuration to the checkup's Job/Pod as environment variables.
The ConfigMap object is only used to report the results (I don't think the term ConfigMap should be in this commit message).

> Thus Kubevirt VM latency checkup VMs can be created only at the checkup namespace.
Unlike any other parameter the checkup namespace is not provided by the ConfigMap.
It is expected that a checkup be aware it executed in Kubernetes pod, and it
should realize the namespace name it belongs to from the mounted namespace file.

By design, the checkup should run in a K8s cluster and set up objects in its own namespace, allocated to it by the framework.
In order to discover this namespace, we read a file which is available in each K8s Pod.

2022-05-16 14:41 UTC, EdDev reviewed
> kubevirt-vm-latency: Read namespace file and pass it to checkup

The language used here is presenting kiagnose and not the checkup.
I think it should have come from the context of writing a checkup.
I do not understand how the ability to pass other values has anything to do with all this. It is not absurd to think that this could also been passed to the checkup by kiagnose.

Something like this should be enough:
```
Checkups are assigned a dedicated namespace in which they can operate and create objects in.

The existing implementation of kiagnose does not pass the working namespace as input explicitly (using environment variables). Therefore, we are left to learn the namespace in which we work in from the mounter namespace file (which k8s make available).
```

2022-05-16 15:10 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/073d534f200c850bfa41702a5c7e10e9d8dd6b13..85972943b033617733261f567217ed43562e791f): 
- Updated `kubevirt-vm-latency: Read namespace file and pass it to checkup` and `kubevirt-vm-latency: Introduce vmi package` according to suggestion.
- Removed redundant conditional slice initialization at `vmi` package, `cloudinit.go` `withAddresses()`.
- Removed redundant function description for `vmi` package  `spec.go` `withContainerDiskImage()`

2022-05-16 16:20 UTC, ormergi commented
@EdDev @orelmisan thanks for the reviews and feedback, I addressed your comments and pushed new changes.
Please take another look :slightly_smiling_face:

2022-05-16 18:18 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCtx, cancel := context.WithTimeout(context.Background(), testTimeout)
I do not understand why you need a context with timeout. Isn't he failure occurring before the waiting loop?

2022-05-16 18:18 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/operation.go
> +			return false, nil
I do not think it is correct.
Failure to fetch the VMI means there is a problem and there is nothing to retry.`

Once the object is created on the API server, the resource is suppose to be available. If it is not there, something bad happened. If there is a communications error or some intermediate other error, I am not interested to handle it at this level (a controller would probably retry at a higher layer).

But maybe I miss something. Please share the scenario where it makes sense to retry when this fails.

2022-05-16 19:11 UTC, EdDev reviewed
The last commit message needs some more wording, allowing the reader to understand which manifest is required for registration, which one is for running an example job and the purpose of the "dev" ones (and how to use them).

The message also has some typos and wrong folders (e.g. the `manifest` is not seen in the paths).

2022-05-17 05:11 UTC, orelmisan commented
@ormergi There is a typo in the first commit message:
> It is built form Kubevirt's

form => from

2022-05-17 05:59 UTC, orelmisan reviewed
@ormergi Thanks for the changes.
Please see the inline comments.

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +	"k8s.io/apimachinery/pkg/api/resource"
nit: Can you please put a new line here?

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +func NewAlpine(name string, opts ...Option) *kvcorev1.VirtualMachineInstance {
If this is the main function we are using to instantiate a VM, can it be on top?

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/cmd/environment.go
> +
nit: Please consider adding a check that the file's content is not empty.

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		defaultSetupTimeout = time.Minute * 10
Isn't this timeout very long for an Alpine machine?

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	return vmi.NewAlpine(name,
nit: Can you please add a new line here?

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +func (c *checkup) Teardown(_ context.Context) error {
Why was the context added in this commit?

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	networkName string, netAttachDef types.NamespacedName,
What is the difference between `netAttachDef` and `networkName`?

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	waitCtx, cancel := context.WithTimeout(ctx, defaultSetupTimeout)
From the tests, I understand that you want to control this context from the outside.
So why are there two contexts?

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCtx, cancel := context.WithTimeout(context.Background(), testTimeout)
Here you have a very short timeout and its confusing, because it is not part of the test's subject.

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	defer cancel()
@ormergi, `Teardown` is receiving a context from the outside, why should it have another one?

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCtx, cancel := context.WithTimeout(context.Background(), testTimeout)
Same comment about short timeout in a different scenario.

2022-05-17 05:59 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCtx, cancel := context.WithTimeout(context.Background(), testTimeout)
AFAIU, the short timeout here should fail the setup.

2022-05-17 09:12 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +	"k8s.io/apimachinery/pkg/api/resource"
Note that all of them are from the same domain (k8s).

2022-05-17 10:42 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/d7eeebb6a57de59e37e885a0ff0f0238d52ae81c..33698226cda8f360a15ea486a4aa7bf17565191d): Update commit messages

2022-05-17 10:45 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		defaultSetupTimeout = time.Minute * 10
I set the timeout that long to overcome connection issues or slowness.

2022-05-17 10:49 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	networkName string, netAttachDef types.NamespacedName,
`netAttachDef` - namespaced name of the network-attachment-definition object
`networkName` - the name of the interface and network in the VMI spec.

2022-05-17 10:55 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	waitCtx, cancel := context.WithTimeout(ctx, defaultSetupTimeout)
In order to set a default timeout.
The parent context is the one that passed to `Setup() `and  controlled by the caller (i, e: tests) 
which may set shorter timeout and cause the context to be canceled before the Setup() default timeout.

2022-05-17 11:43 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/33698226cda8f360a15ea486a4aa7bf17565191d..fd4f9c79bcf61e9a059011ba64b758d955124a1b): Fix commit messages.

2022-05-17 11:44 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
> +func newFakeClient() *fakeClient {
@EdDev is it ok  with you, if I will get read of using timeouts in a follow up PR?

2022-05-17 11:48 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/operation.go
> +			return false, nil
@EdDev  Thanks for explaining it make sense,  the current implantation dont breaks anything but I do want to fix it.
Since it will require changes tests, is it ok if I address it in a follow up PR?

2022-05-17 11:49 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCtx, cancel := context.WithTimeout(context.Background(), testTimeout)
@EdDev Thanks for the heads up, I removed it.

2022-05-17 11:50 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
> +func NewAlpine(name string, opts ...Option) *kvcorev1.VirtualMachineInstance {
I think this is a nit, can we address it later?

2022-05-17 11:52 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCtx, cancel := context.WithTimeout(context.Background(), testTimeout)
Thanks for the heads up, I removed it.

2022-05-17 11:54 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/fd4f9c79bcf61e9a059011ba64b758d955124a1b..1790aa56f52a9a84d35b198abb322d992568977d): Remove redandent passing context with timeout in tests.

2022-05-17 11:55 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/1790aa56f52a9a84d35b198abb322d992568977d..5517ee62ae6cdba38d89952b44855cae0e0369da): Fixed second commit message.

2022-05-17 12:03 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/5517ee62ae6cdba38d89952b44855cae0e0369da..c9e83eb6f930e0ab1cbd86908b3084c102a7eaad): Fix tests that hanged due to setting up expected VMI object with the wrong condition.

2022-05-17 12:09 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +		testCtx, cancel := context.WithTimeout(context.Background(), testTimeout)
Note that just before Setup() is called, we inject a VMI object in order that makes Setup() pass.

Now I realize there is no need to pass context with short timeout to Setup() in this test, I will remove it.

2022-05-17 12:10 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/c9e83eb6f930e0ab1cbd86908b3084c102a7eaad..447e57ac6696ac3d5841cc3dc0dbb4d7a66d33ba): Change checkup test "Ms were not disposed before timeout expiration" to not pass context with timeout to Setup(), it is redundant.

2022-05-17 12:21 UTC, orelmisan approved these changes
Thank you @ormergi!

2022-05-17 13:08 UTC, merged