latency, e2e: Add KUBEVIRT_USE_EMULATION flag
kiagnose/kiagnose pull request #79
Opened 2022-05-19 14:13 UTC by orelmisan

Add a flag to control the usage of kubevirt's emulation
feature.
Using this flag, makes the e2e tests to run slower, thus it is disabled
by default.

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-05-19 14:57 UTC, EdDev reviewed
Nice and simple.

For some reason the CI fails :/

2022-05-23 13:01 UTC, ormergi submitted a review, later dismissed
Thanks for addressing this, I added some suggestions to reduce some noise from the script.

2022-05-23 13:01 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    if [ -n "${KUBEVIRT_USE_EMULATION}" ]; then
I think you can get rid of the `if` clause and reduce some noise if `KUBEVIRT_USE_EMULATION` will be set as `useEmulation` value

```
kubectl patch kubevirt kubevirt --namespace kubevirt --type=merge --patch "{\"spec\":{\"configuration\":{\"developerConfiguration\":{\"useEmulation\":$KUBEVIRT_USE_EMULATION}}}}"
￼
```

2022-05-23 13:05 UTC, orelmisan commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +      echo "Use emulation"
Done.

2022-05-23 13:07 UTC, EdDev commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    if [ -n "${KUBEVIRT_USE_EMULATION}" ]; then
I think the user comfort is more important then the script being "cleaner".
As the caller/user of this helper script, I do not want to know these details.

2022-05-24 08:41 UTC, EdDev requested changes

2022-05-24 09:05 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/867195682890f5cbd25803a0f92ab2475a65a815..17de1bc0c965a61cd9fb177e899d2eba03ef99b7): Rebase
Answered @EdDev's [comment](https://github.com/kiagnose/kiagnose/pull/79#pullrequestreview-982824853).

2022-05-24 09:16 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/17de1bc0c965a61cd9fb177e899d2eba03ef99b7..baa7dde69ec609d7f5d71fbdf80508ecb3dab121): Set the default value of `KUBEVIRT_USE_EMULATION` to "false".

2022-05-24 09:45 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    if [ -n "${KUBEVIRT_USE_EMULATION}" ]; then
>I think the user comfort is more important then the script being "cleaner".
As the caller/user of this helper script, I do not want to know these details.

Changing the script to what I suggest doesn't change the "frontend" for the user of this script 
or makes is less convenient to use.
Keeping this script clean will make it easier for us maintain eventually.

Anyway this is not a must.

2022-05-24 09:46 UTC, ormergi approved these changes
Looks good to me.

2022-05-24 09:52 UTC, EdDev approved these changes
Thanks!

2022-05-24 09:52 UTC, merged