Introduce mainflow skeleton
kiagnose/kiagnose pull request #8
Opened 2022-03-20 19:30 UTC by ormergi

Introduce kiagnose mainflow skeleton for launching and managing
checkups lifecycle (e.g: setup, teardown, result reporting).

2022-03-21 14:56 UTC, orelmisan reviewed
Thank you for the PR!
Please see the inline comments.

2022-03-21 15:23 UTC, ormergi commented on kiagnose/mainflow.go
> +type Launcher interface {
Yes, Setup() should cover loading env vars up to creating all entities required for the checkup (w/o starting it).

2022-03-21 15:24 UTC, EdDev requested changes
I have tried to simplify the handling and take care of cases where we have panics occurring (the current code does not handle them at all).

2022-03-21 15:24 UTC, EdDev commented on kiagnose/mainflow.go
> +func Run(launcher Launcher) error {
I like less the usage of an error stack here, I would prefer to see the errors being wrapped in the regular manner: An error of one step be wrapped by the error of the next one.

In addition, per what I managed to figure out from the code, the `Report()` is expected to be call always, while the `Teardown` is to be called only if it passed the `Setup()`.
While I think it is fine, mimicking a constructor behavior, it is worth noting that it also means that `Setup` is responsible of cleaning up whatever he did already. If it has a large amount of side effects, it may become an issue later on.

But the problem I do see at this stage is that the code does not try to terminate in a control manner when panics are raised. This is true for both the `Teardown` and `Report` calls.

Consider this skeleton:
```
func Run(launcher Launcher) (runerr error) {
    defer func() {
        err := launcher.Report()
        if err != nil or runerr != nil:
            runerr = fmt.Errorf("mainflow failed: %v, %v", runerr, err)
        }
    }()
    if err = launcher.Setup(); err != nil {
        return err
    }
    defer func() { /*call Teardown() like Report() earlier*/ }()
    
    if err := launcher.Run(); err != nil {
        return err
    }
    return nil
}
```

2022-03-21 15:24 UTC, EdDev commented on kiagnose/mainflow_test.go
> +			failReport:   false,
This is the default, why specify it?

2022-03-21 15:24 UTC, EdDev commented on kiagnose/mainflow_test.go
> +			failTeardown: false,
same

2022-03-21 15:24 UTC, EdDev commented on kiagnose/mainflow_test.go
> +	failReport   bool
You can use the errors themselves, saving you an `if` each time...

```
launcherStub{
    failSetup:    errorSetup,
}
```

2022-03-21 15:25 UTC, EdDev commented on kiagnose/mainflow.go
> +	Report() error
What else can we report exactly if it is not the status?

2022-03-21 15:30 UTC, ormergi commented on kiagnose/mainflow.go
> +	Report() error
At this point of time I prefer to have the least of detailed interface, as other requirements may arise
with the implementation (e.g: add logic for the `mainflow`, expose variables, return other variables then `error`).

2022-03-21 17:01 UTC, ormergi reviewed
Resolve code-review comments: 
- gitignore typo
- mainflow unit tests formatting and simplifying stubs

2022-03-22 07:31 UTC, ormergi commented on kiagnose/mainflow.go
> +func Run(launcher Launcher) error {
Thanks for the heads up regarding cleaning up after Setup and handling panics, I will do the necessary changes.

Other than that, now that I am looking at it again, I realize that there is a problem with calling to Report() when Setup() is failing.
Setup() should include the logic for initializing the reporter (e.g: load k8s client, load configMap/CRD to update and verify it exist ).
I think its necessary to have another func for initializing the reporter:
```
func Run(launcher Launcher) (runerr error) {
    if err := launcher.Init(); err != nil {
        return err
    }
    defer func() {
        err := launcher.Report()
        if err != nil or runerr != nil:
            runerr = fmt.Errorf("mainflow failed: %v, %v", runerr, err)
        }
    }()
    ...
}
```
WDYT?

2022-03-22 08:13 UTC, EdDev commented on kiagnose/mainflow.go
> +func Run(launcher Launcher) error {
This will complicate things IMO.
You could just do a noop operation if the setup has failed to initialize the reporter.
This can be done internally or exposed:
- Internally means you do not see it at all, which may be problematic to test (you need to check this). The API remains as before.
- Externally means you have another object (e.g. `Reporter`) and you let the `Setup` set it up:
  `launcher.Setup(report.New())`
  Then `launcher.Report()` will delegate it to the inputted reporter, which may do something or not, depending of its population by the setup.

2022-03-22 08:15 UTC, EdDev commented on kiagnose/mainflow.go
> +func Run(launcher Launcher) error {
With the internal option, you do not call `Report` if the setup fails, you leave it to the `Setup()` implementation to handle it, together with cleaning up what it manage to do already (i.e. partial setup cleanup is under its responsibility, including reporting).

2022-03-22 09:02 UTC, ormergi commented
Changes: resolve code-review [comment](https://github.com/kiagnose/kiagnose/pull/8#discussion_r831219880)

2022-03-22 09:05 UTC, ormergi commented
Changes: reduce errors scope exposure

2022-03-22 09:50 UTC, EdDev requested changes

2022-03-22 09:50 UTC, EdDev commented on kiagnose/mainflow_test.go
> +		assert.Regexp(t, regexp.MustCompile(errorReport.Error()), err.Error())
I find this too odd.
It is playing with test to check if something happened, which does not seem to be "strong".

Also, using a regex for a substring inclusion seems an over kill, a reader may think there is something most sophisticated here than it really is.

Lets see out options:
- Use dedicated typed errors and wrap them using `%w`: This is nice for testing, but it also exposes the errors as API/s.
- Do a simple substring check (`strings.Contains`)
- Use the testify dedicated assert (https://pkg.go.dev/github.com/stretchr/testify/assert#ErrorContains).

Can you try the last one?

2022-03-22 09:50 UTC, EdDev commented on kiagnose/mainflow_test.go
> +	t.Run("should fail with wrapped run-error and reflect report error when both are failing", func(t *testing.T) {
Lets try to simplify it for the reader: `should fail when run & report is failing`.

2022-03-22 09:50 UTC, EdDev commented on kiagnose/mainflow_test.go
> +	t.Run("should fail with wrapped setup-error and reflect report error when both are failing", func(t *testing.T) {
Lets try to simplify it for the reader: `should fail when setup & report is failing`.

2022-03-22 09:50 UTC, EdDev commented on kiagnose/mainflow_test.go
> +	t.Run("should fail with wrapped teardown-error and reflect report error when both are failing", func(t *testing.T) {
Lets try to simplify it for the reader: `should fail when teardown & report is failing`.

2022-03-22 09:50 UTC, EdDev commented on kiagnose/mainflow_test.go
> +	t.Run("should fail with wrapped run-error and reflect teardown and report errors when each of them is failing", func(t *testing.T) {
Lets try to simplify it for the reader: `should fail when run, teardown & report is failing`.

2022-03-22 13:38 UTC, ormergi commented on kiagnose/mainflow_test.go
> +		assert.Regexp(t, regexp.MustCompile(errorReport.Error()), err.Error())
I also dont like assert on an error content, initially I did tried to wrap the errors 
but `ErrorIs` (which make use of `error.Is`) work in a way that it wont detect more then
one wrapped error, for example:
In case that Run(), Teardown() and Report() were failing:
```
assert.ErrorIs(t, err, runErr) 
assert.ErrorIs(t, err, teardownErr) <------- assertion fails
assert.ErrorIs(t, err, reportErr) <--------- assertion fails
```
Thus, I used other assertions to ensure the info of other errors is there.
Note that the errors content is also controlled by the tests, meaning the test 
does ensure that the flow works as we expect.

I will try to optimize the assertions and get rid of the regex

2022-03-22 13:40 UTC, ormergi commented on kiagnose/mainflow_test.go
> +		assert.Regexp(t, regexp.MustCompile(errorReport.Error()), err.Error())
https://go.dev/play/p/NmCcpqK2yaZ

2022-03-22 14:20 UTC, ormergi commented on .gitignore
> +# Golang
Done

2022-03-22 14:20 UTC, ormergi commented on kiagnose/mainflow.go
> +type Launcher interface {
No need to expose it, fixed

2022-03-22 14:21 UTC, ormergi commented on kiagnose/mainflow_test.go
> +	t.Run("should fail with wrapped run-error and reflect report error when both are failing", func(t *testing.T) {
Done

2022-03-22 14:21 UTC, ormergi commented on kiagnose/mainflow_test.go
> +	t.Run("should fail with wrapped setup-error and reflect report error when both are failing", func(t *testing.T) {
Done

2022-03-22 14:21 UTC, ormergi commented on kiagnose/mainflow_test.go
> +	t.Run("should fail with wrapped run-error and reflect teardown and report errors when each of them is failing", func(t *testing.T) {
Done

2022-03-22 16:46 UTC, ormergi commented
`[Change](https://github.com/kiagnose/kiagnose/compare/23eb323fa7d76522efacf7031a97914ce90b4d95..594f97a66f264d8832391625452d47cc3460ba36)`: Fix error messages formatting

2022-03-22 17:14 UTC, ormergi commented on go.mod
> +require github.com/stretchr/testify v1.7.1
I update it since `ErrorContians` assert is introduced only since 1.7.1

2022-03-22 18:48 UTC, EdDev commented on go.sum
>  github.com/stretchr/testify v1.7.0/go.mod h1:6Fq8oRcR53rry900zMqJjRRixrwX3KX962/h/Wwjteg=
Hmm.. if you run `tidy`, does this one go away?

2022-03-22 18:48 UTC, EdDev commented on kiagnose/mainflow.go
> +				runErr = fmt.Errorf("%w, %v", runErr, reportErr)
I missed the reason why you used `%w`.
I do not think we decided to expose the errors. If you do expose them, we will need to document them.

I suggest we avoid this for now, we can change it later per need. And you do have now means to check the errors in tests without it.

---

There is another problem I see now, the "mainflow failed: " prefix is repeating in the stacked errors.
I think we can follow this logic on each error handling we have:
- If there is no need to add an error to an existing error stack, then just do: `runErr = <new error>` (e.g. `runErr = reportErr`).
- If there is a need to add an error to an existing stack of errors, then do: `runErr = fmt.Errorf("%v, %v", runErr, <new error>)`.

To complete this, at the top add a defer that just adds the prefix if an error exists.

WDYT?

2022-03-23 08:09 UTC, ormergi commented on go.sum
>  github.com/stretchr/testify v1.7.0/go.mod h1:6Fq8oRcR53rry900zMqJjRRixrwX3KX962/h/Wwjteg=
Yep, thanks for the heads up.

2022-03-23 08:25 UTC, ormergi commented on kiagnose/mainflow.go
> +				runErr = fmt.Errorf("%w, %v", runErr, reportErr)
My intent was test the mainflow by asserting errors by their types and not content,
it turned out that `error.Is` wont work as I expected.
Now that the tests asserts on the error content anyway there is no value for wrapping them
no longer (`%w`). Sorry for the mess I will get rid of it.

Regarding the `mainflow failed` prefix, at first I handled it as part of defer as you suggest,
then it seemed like I am piggy backing that defer func with not related logic to its original
purpose (which is performing the report).

2022-03-23 09:19 UTC, EdDev commented on kiagnose/mainflow.go
> +				runErr = fmt.Errorf("%w, %v", runErr, reportErr)
> Regarding the mainflow failed prefix, at first I handled it as part of defer as you suggest,
then it seemed like I am piggy backing that defer func with not related logic to its original
purpose (which is performing the report).

I do not understand. There is now a problem that the prefix is added multiple times and the addition is repeated instead of being done once. Am I missing something?

2022-03-23 12:10 UTC, EdDev approved these changes
Looks great, thanks!

2022-03-23 12:28 UTC, phoracek commented on .gitignore
> +.idea/
These are not project-specific but you-specific. I recommend setting up https://stackoverflow.com/questions/7335420/global-git-ignore.

2022-03-23 13:31 UTC, orelmisan approved these changes
Thank you, looks great!

2022-03-23 15:04 UTC, EdDev submitted a review, later dismissed

2022-03-24 08:08 UTC, EdDev approved these changes

2022-03-24 08:09 UTC, merged