kiagnose, namespace: Use watcher to wait for deletion
kiagnose/kiagnose pull request #84
Opened 2022-05-23 16:34 UTC by EdDev

Waiting for the namespace to be deleted was done using polling.
This has now been improved by using a watcher.

To avoid a race where the deletion event arrives before a watcher is
created for the namespace, the watcher is created before the delete
action.

2022-05-23 18:16 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	if errAction := action(ctx); errAction != nil {
It allows splitting the "wait" and "operation", each doing its thing.
In order to re-use it, some more work is needed to generalize the `wait*` one.

If you'll insist, I can flatten it and collapses everything into `DeleteAndWait`.

2022-05-24 08:33 UTC, orelmisan commented on kiagnose/internal/checkup/namespace/namespace.go
> +	if errAction := action(ctx); errAction != nil {
Do you plan to make a `wait` function in a future PR?

2022-05-24 08:45 UTC, orelmisan commented on kiagnose/internal/checkup/namespace/namespace.go
> +	if errAction := action(ctx); errAction != nil {
Do you mind putting all the code in `DeleteAndWait()`?
If we don't have a near future plan for the separation of "action" and "wait" parts, I think the code will be more readable flat.
Another reasoning is that `waitForNamespaceDeletion()` actually requests the the Namespace deletion.

2022-05-24 10:00 UTC, orelmisan commented on kiagnose/internal/checkup/namespace/namespace.go
> +	log.Printf("deleted namespace %q request sent", nsName)
```suggestion
	log.Printf("delete namespace %q request sent", nsName)
```

2022-05-24 10:06 UTC, orelmisan submitted a review, later dismissed
Thank you for the changes.

2022-05-24 10:30 UTC, EdDev commented
change: Rebase

2022-05-24 10:36 UTC, ormergi reviewed
Thanks for addressing this it looks good, please see my inline comments.

2022-05-24 10:36 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +			expectedErrMatch  = "deadline exceeded"
You can use `context.DeadlineExceeded` typed error.

2022-05-24 10:36 UTC, ormergi commented on kiagnose/internal/checkup/namespace/namespace.go
> +	nsLabel := fmt.Sprintf("%s=%s", NamespaceNameLabel, nsName)
You can use `corev1.LabelMetadataName` instead.

2022-05-24 10:36 UTC, ormergi commented on kiagnose/internal/checkup/namespace/namespace.go
> +			}
I think this check should be moved before the event type check (before line 66).

2022-05-24 10:44 UTC, EdDev commented
change: Use a zero teardown timeout.

(we should try and get rid of this time dependent tests)

2022-05-24 10:49 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +			expectedErrMatch  = "deadline exceeded"
Done

2022-05-24 10:49 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	nsLabel := fmt.Sprintf("%s=%s", NamespaceNameLabel, nsName)
Done

2022-05-24 10:49 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +			}
Why?

2022-05-24 10:58 UTC, EdDev commented
change: Answered review comments about the contant strings and prioritized the `ctx` check over the event existence.

2022-05-24 11:03 UTC, EdDev commented
Unfortunately, I am not able to pass the unit test that checks what happens when the context expires.
```
    checkup_test.go:187: 
        	Error Trace:	checkup_test.go:187
        	Error:      	An error is expected but got nil.
        	Test:       	TestCheckupTeardownShould/fail_when_Namespace_wont_dispose_on_time
```

All the time-based tests should be replaced with something that we can control.

2022-05-24 12:48 UTC, EdDev commented
change: Add `watch` permission.

2022-05-24 15:35 UTC, ormergi commented on kiagnose/internal/checkup/namespace/namespace.go
> +			}
I got it wrong, sorry for the noise

2022-05-24 16:17 UTC, EdDev commented
change: Added an injection to the fake client to ignore an operation. It allows the `Delete` verb on the namespace to be ignored, therefore, not to create an event, giving opportunity for the context timeout to kick in.

2022-05-24 16:52 UTC, EdDev commented
change: Rebase

2022-05-25 09:17 UTC, qinqon requested changes

2022-05-25 09:17 UTC, qinqon commented on kiagnose/internal/checkup/namespace/namespace.go
> +	nsWatcher, err := client.CoreV1().Namespaces().Watch(ctx, metav1.ListOptions{LabelSelector: nsLabel})
There is a "labels" package at apimachinery with some helpers for this operation, what we can use here is "Set" We can use https://pkg.go.dev/k8s.io/apimachinery@v0.24.0/pkg/labels#Set so we don't have to create a expression.

```suggestion
	nsLabel := labels.Set(map[string]string{corev1.LabelMetadataName: nsName})
	nsWatcher, err := client.CoreV1().Namespaces().Watch(ctx, metav1.ListOptions{LabelSelector: nsLabel.String()})
```

2022-05-25 09:17 UTC, qinqon commented on kiagnose/internal/checkup/namespace/namespace.go
>  	}
Defer has to be done just after resource instantiation
```suggestion
	}
	defer nsWatcher.Close();
```

2022-05-25 09:17 UTC, qinqon commented on kiagnose/internal/checkup/namespace/namespace.go
> +	defer nsWatcher.Stop()
Added at previous comment
```suggestion
```

2022-05-25 09:17 UTC, qinqon commented on kiagnose/internal/checkup/namespace/namespace.go
> +	}
This can be implemented using the helper `watch.Until` here https://pkg.go.dev/k8s.io/client-go/tools/watch#Until so we don't have to handle the channel

It would be something like 

```golang
if _, err := watch.Until(timeout, nsWatcher, func(event watch.Event) (bool, error) {
		        if event.Type != k8swatch.Deleted {
				return false, nil
			}
			ns, ok := event.Object.(*corev1.Namespace)
			if !ok {
				false, nil
			}
			log.Printf("Namespace %q deleted", ns.Name)
			return true, nil
	}); err != nil {
		return err
	}
```

2022-05-25 11:44 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	nsWatcher, err := client.CoreV1().Namespaces().Watch(ctx, metav1.ListOptions{LabelSelector: nsLabel})
It seems an overkill to me in this case. We are not using any interesting helper method on the `Set`, I think the current simpler (less dependencies) is good enough.

2022-05-25 11:44 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
>  	}
You mean `Stop()`?

2022-05-25 11:44 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	}
Nice, I will try it out. Thanks!

2022-05-25 11:53 UTC, qinqon commented on kiagnose/internal/checkup/namespace/namespace.go
> +	nsWatcher, err := client.CoreV1().Namespaces().Watch(ctx, metav1.ListOptions{LabelSelector: nsLabel})
The project is already using apimachinery so the dependency is already there, also I think we can simplify this with 

```
labels.Set{corev1.LabelMetadataName: nsName}
```

2022-05-26 13:33 UTC, EdDev commented
[change](https://github.com/kiagnose/kiagnose/compare/fa05c76b90569cae4292763ba972ff82e5f7556c..9dbc9b251d59a5d4d0746783b062e55344791785): Implemented the watching mechanism using the client-go tooling (i.e. `Until`).

2022-05-26 13:42 UTC, EdDev commented
The unit tests are still not working... Investigating.

2022-05-29 12:40 UTC, EdDev commented
change: There was a need to inject a watch event for the ns deletion (in unit tests).

2022-05-29 12:52 UTC, EdDev commented
change: Make linter happy.

2022-05-29 13:12 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	}
Done

2022-05-29 13:17 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	nsWatcher, err := client.CoreV1().Namespaces().Watch(ctx, metav1.ListOptions{LabelSelector: nsLabel})
Done

2022-05-30 05:58 UTC, qinqon requested changes
Jus a nit to simplify a little ListWatch

2022-05-30 05:58 UTC, qinqon commented on kiagnose/internal/checkup/namespace/namespace.go
> +			}
You don't need this here, there is no extra options passed when you consume the ListWatch since it's a very controller context.

2022-05-30 06:13 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +			}
This is the only way to inject custom options, so I am not sure I follow your comment here.
The options are required in order to offload to the server side the events we are interested in listening to (we do not want to get events of the whole cluster).

2022-05-30 06:21 UTC, qinqon commented on kiagnose/internal/checkup/namespace/namespace.go
> +			}
I mean the comma part is not needed we are not calling eat with extra options

2022-05-30 06:32 UTC, EdDev commented
change: Simplify the resource-version update in tests (no need to use unstructured data).

2022-05-30 06:35 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +			}
Maybe you mean the condition if it is already populated with some data or not?
I think this is safer, as we do not know if this will change or not in the future. I also had the impression that `Until` adds labels, so by the time this is reached, it is already populated with the ones it adds.

2022-05-30 06:38 UTC, qinqon submitted a review, later dismissed

2022-05-30 07:11 UTC, ormergi reviewed
Hi Edy, thanks for the PR  it nice to see that client-go provide watchers helpers.

Could you please elaborate on the commit message about why its necessary to 
set the namespace ResourceVersion in tests?

2022-05-30 07:11 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +	c.injectResourceVersionUpdate("create", "namespaces")
Here we can use `namespaceResource`.

2022-05-30 07:11 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +func (c *testsClient) injectIgnoreOperation(verb, resourceName string) {
nit: I would omit `inject`.

2022-05-30 07:11 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +		testClient.injectIgnoreOperation("delete", "namespaces")
Here we can use `namespaceResource`.

2022-05-30 07:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +		testClient.injectIgnoreOperation("delete", "namespaces")
Sorry, I do not understand.

2022-05-30 07:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +		&corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: "o", ResourceVersion: "123"}},
It is not needed, it is a leftover. Thanks.

2022-05-30 07:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func (c *testsClient) injectIgnoreOperation(verb, resourceName string) {
It makes sense (to me) to keep the same language for consistency.

2022-05-30 07:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +	c.injectResourceVersionUpdate("create", "namespaces")
Same, I do not understand what you mean.

2022-05-30 07:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func (c *testsClient) injectResourceVersionUpdate(verb, resourceName string) {
I wanted to keep the `verb` and `resourceName` as input arguments, but the linter does not like it if all are using the same exact values. This is how to overcome it.

2022-05-30 07:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func (c *testsClient) injectWatchWithNamespaceDeleteEvent() {
I am having hard time decoding the suggested name. It has "watch", "delete" and "event" with no clear relation between each other. I find the existing option better.

2022-05-30 07:31 UTC, EdDev commented
[change](https://github.com/kiagnose/kiagnose/compare/593253fcaf75b7a14dc4a51b5c19a01033b40e27..8929baa5cf2cf1b4e410a8f2d84815795504583f): Removed a leftover from the tests and updated the commit message with a note about the need for the resource version.

2022-05-30 08:44 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +		testClient.injectIgnoreOperation("delete", "namespaces")
I meant to use this variable instead https://github.com/kiagnose/kiagnose/blob/main/kiagnose/internal/checkup/checkup_test.go#L46

2022-05-30 08:44 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +	c.injectResourceVersionUpdate("create", "namespaces")
I meant to use this variable instead https://github.com/kiagnose/kiagnose/blob/main/kiagnose/internal/checkup/checkup_test.go#L46

2022-05-30 08:47 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +func (c *testsClient) injectResourceVersionUpdate(verb, resourceName string) {
It seems that it wont be necessary to receive`verb` and `resourceName` parameters, if both functions are merged to one.

2022-05-30 09:21 UTC, orelmisan commented on kiagnose/internal/checkup/namespace/namespace.go
> +	w := &cache.ListWatch{
What is the difference between `ListWatch` and something like:
```go
client.CoreV1().Namespaces().Watch(ctx, metav1.ListOptions{
  LabelSelector: ...,
})
```

2022-05-30 09:38 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func (c *testsClient) injectResourceVersionUpdate(verb, resourceName string) {
And still, I want to keep the arguments. I think it is the right thing to do, serving other resources (e.g. jobs) in the very near future. It also allows me to reuse it on other projects.

2022-05-30 09:47 UTC, EdDev commented
change: Use the existing const instead of `"namespaces"` resource.

2022-05-30 10:56 UTC, orelmisan commented on kiagnose/internal/checkup/namespace/namespace.go
> +	w := &cache.ListWatch{
What is the difference in functionality?

2022-05-30 12:45 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	w := &cache.ListWatch{
Sorry, I do not understand you.
Maybe you can try reducing the confusion by providing a code snippet you propose here.

What I answered before is that you cannot replace the `w` with the thing the `Watch` returns, they are not the same.
I can add information like: The `Until()` is creating a watcher internally, it does not accept one that is already instantiated.
But I am not sure it helps, it may open more questions on how this thing works.

2022-05-30 12:51 UTC, ormergi approved these changes
Thanks for the changes, LGTM.

2022-05-30 13:08 UTC, qinqon approved these changes

2022-05-30 13:37 UTC, merged