checkup: Randomize Namespace's name
kiagnose/kiagnose pull request #89
Opened 2022-05-25 07:00 UTC by orelmisan

In order to run multiple checkups simultaneously, it is required to run them in Namespaces with a unique name.
Create checkup namespaces with names in the following format:
`kiagnose-checkup-<random string>`

This PR does not handle name randomization of ClusterRoleBindings, which is also required to run multiple checkups simultaneously. It will be done in a follow-up PR.

2022-05-25 08:29 UTC, RamLavi requested changes
like!, adding an import nit

2022-05-25 08:29 UTC, RamLavi commented on kiagnose/internal/checkup/checkup.go
> +
why are the `k8s.io` imports grouped apart?

2022-05-25 08:34 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +
This was done in order to emphasize the difference between the `k8s.io/api` repo and `k8s.io/apimachinery` repo.

2022-05-25 10:39 UTC, RamLavi commented on kiagnose/internal/checkup/checkup.go
> +
ah, the reason I'm asking is that I am used to the convention used on kubevirt where there should be 5 import groups:
1. standard go libraries
2. test libraries
3. third part libraries (like k8s.io...)
4. org libraries (for kubevirt, it's all kubevirt related repos)
5. own repo's libraries.

But TBH it is not so meticulously enforced, so I leave it as a suggestion.

2022-05-25 10:40 UTC, RamLavi approved these changes
/lgtm

2022-05-25 10:45 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +
Thank you for the explanation.

2022-05-26 14:23 UTC, ormergi reviewed
Hi Orel, thanks for addressing this

IMO: commits 1-7 can be merged to single atomic commit that actually bring meaningful change, each commit does stands by its own but its all variables substitutions (until commit 7).
Same goes for commits 8-9.

2022-05-29 07:13 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	return fmt.Sprintf("%s-%s", name, rand.String(randomStringLen))
What is the reasoning behind your proposal?

The randomization code used in this PR is also used by [kubevirt's libvmi](https://github.com/kubevirt/kubevirt/blob/5bf9394089f6790279aad9ac2001a7a230d34ec3/tests/libvmi/vmi.go#L49).

2022-05-29 07:15 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	NamespaceName                  = "kiagnose-checkup"
It is still being used by `newTestRoles()` in `checkup_test.go`.
I'll fix it in a follow-up PR.

2022-05-29 07:20 UTC, orelmisan commented
> IMO: commits 1-7 can be merged to single atomic commit that actually bring meaningful change, each commit does stands by its own but its all variables substitutions (until commit 7). Same goes for commits 8-9.

I agree that commits 1-7 could be squashed, but I've found it more comprehensible to depict the change gradually.
Same for commits 8-9.

2022-05-29 09:21 UTC, EdDev commented
> > IMO: commits 1-7 can be merged to single atomic commit that actually bring meaningful change, each commit does stands by its own but its all variables substitutions (until commit 7). Same goes for commits 8-9.
> 
> I agree that commits 1-7 could be squashed, but I've found it more comprehensible to depict the change gradually. Same for commits 8-9.

I tend to agree that this is the same subject, under the same area, so having so many commits may be an overkill.

2022-05-29 09:23 UTC, EdDev reviewed
| This change was done in preparation for the Namespace's name randomization.

This is repeating on each commit, which is too much IMO.

2022-05-29 09:23 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +	"k8s.io/apimachinery/pkg/util/rand"
Please alias it with  `k8s` or `util`.

2022-05-29 09:23 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +	NamespaceName                  = "kiagnose-checkup"
Won't this change the documentation/manifests?

2022-05-29 09:25 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	NamespaceName                  = "kiagnose-checkup"
This is not reflected in the manifests, because they are deployed to the `kiagnose` Namespace.

The documentation is an open PR (#93).

2022-05-29 09:38 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/024c5f7fb15d352d2b86cc4fb78baa6e89dff96f..31f73839dcfb046cfed7cd6f54288fa8250fe6fc): Squased commits 1-7, and 8-9.

2022-05-29 09:41 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/31f73839dcfb046cfed7cd6f54288fa8250fe6fc..2f7b95d4f33e96852e6fa4df6ba8697a32cf9149): Answered review [comment](https://github.com/kiagnose/kiagnose/pull/89#discussion_r884238686).

2022-05-29 09:42 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	"k8s.io/apimachinery/pkg/util/rand"
Aliased it `k8srand`

2022-05-29 10:23 UTC, EdDev approved these changes
Thank you!

2022-05-29 16:03 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	return fmt.Sprintf("%s-%s", name, rand.String(randomStringLen))
The fact that one project solves a problem in one way doesn't mean other projects should follow the same solution :slightly_smiling_face: 
In this case its easy to come up with our own implementation instead of bringing another dependency with code we dont use (one liner vs. 120).

2022-05-29 16:04 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	NamespaceName                  = "kiagnose-checkup"
I think #91 is the right place.

2022-05-29 16:23 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	NamespaceName                  = "kiagnose-checkup"
PR #91 deals with ClusterRoleBinding names.
The problem is with a function that creates Role objects.

2022-05-29 16:33 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	return fmt.Sprintf("%s-%s", name, rand.String(randomStringLen))
> The fact that one project solves a problem in one way doesn't mean other projects should follow the same solution slightly_smiling_face 

It is the same behavior like Pod names in a `ReplicaSet` or a random VMI Pod name.
I think that there is value in the same "look and feel".

> In this case its easy to come up with our own implementation instead of bringing another dependency with code we dont use (one liner vs. 120).

Our `vendor` directory has ~1,000,000 lines ;)

2022-05-29 16:34 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +	return fmt.Sprintf("%s-%s", name, rand.String(randomStringLen))
> The simplest thing to do would be appending Unix time to the namespace name

If apimachinery maintainers accept it, we will adopt it as well.
There is a good chance that your proposal is not safe for the long run or even today. The existing library can prove by usage that it is safe, yours requires proof.

This is not a syntax sugar thing that is imported, but a complex logic thing that can cause a lot of problems if you are wrong. I suggest to keep using the apimachinery version.

2022-05-29 16:37 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +	return fmt.Sprintf("%s-%s", name, rand.String(randomStringLen))
> The fact that one project solves a problem in one way doesn't mean other projects should follow the same solution

One project? Maybe it is the other way around.
We have k8s and its satellite projects, then we have kiagnose who will invent a new randomization. You will need to be a bit more convincing on this.

2022-05-29 16:49 UTC, EdDev reviewed
Ok, after looking at both naming randomization for the namespace and cluster role bindings, I find the approach from the test perspective problematic. What I mean but this is, that it is hard to test and complicates the API.

My suggestion is to use a `NameGenerator` object, with a `Name` method that generates a name. A `Namer` interface can be used so in tests a stub with a fixed name can be set.

The only unit tests that this new NG requires is that calling `Name()` twice, does not generate the same name.

WDYT?

2022-05-30 09:26 UTC, ormergi commented
> 

@EdDev I think its possible thing to do, from what I understand it requires passing `NameGenerator` object to checkup.New()
that later on can be switched with a stub in tests.
What was the blocker you tackled?

2022-05-30 09:42 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	return fmt.Sprintf("%s-%s", name, rand.String(randomStringLen))
@orelmisan 
> Our vendor directory has ~1,000,000 lines ;)

Yep, not optimal, but if we can make avoid adding more to it easily why not? :slightly_smiling_face: 

@EdDev 
> If apimachinery maintainers accept it, we will adopt it as well.
There is a good chance that your proposal is not safe for the long run or even today. The existing library can prove by usage that it is safe, yours requires proof.

I do understand `apimachinery` is proofed by it usage, but I am not sure what kind of proof do you expect.
Also this code is 5 year old, I dont think anyone would bother to touch also my suggestion doesnt seem 
to add value for `apimachinery` implementation, but I can give it a try..

Note that in `apimachinery` implementation uses the standard go `rand` packaged and the randomization seed
that being used is `time.Now().UnixNano()`.
Eventually the results will be derivative of the randomization seed, what I suggest is basically using the string directly.

> One project? Maybe it is the other way around.
We have k8s and its satellite projects, then we have kiagnose who will invent a new randomization. You will need to be a bit more convincing on this.

What I meant is that we should not `always` stick with the exact same solutions we see on other projects
when we can simplify them to our needs.

2022-05-30 10:45 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/2f7b95d4f33e96852e6fa4df6ba8697a32cf9149..ac8d6f2a389232263ec00054819005870d597037): Rebase
Introduced the `namer` interface and the `NameGenerator` struct that implements it.

2022-05-30 10:53 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/ac8d6f2a389232263ec00054819005870d597037..4811fbc3bfc938d8109a08138dd4f8372080ed80): Changed `checkup.NamespaceName` value to `kiagnose-checkup`.

2022-05-30 11:09 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/4811fbc3bfc938d8109a08138dd4f8372080ed80..7a97625a3e3ef0b5406415c3a3813c23b3d28e2c): Generate name using `NameGenerator.Name()` in `nameGeneratorStub.Name()`.

2022-05-30 11:19 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/7a97625a3e3ef0b5406415c3a3813c23b3d28e2c..ac0c4572609e80d2ea238f2983accbcc69bbf0f6): Changed `nameGeneratorStub` receiver to an object instead of a pointer.

2022-05-30 11:20 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func (ngs nameGeneratorStub) Name(prefix string) string {
Why do we need this complicated logic? Isn't it enough to return a specific pre-defined string? We do not need it to be random in these tests.

2022-05-30 12:34 UTC, EdDev commented on kiagnose/internal/checkup/namegenerator/namegenerator.go
> +	return fmt.Sprintf("%s-%s", prefix, k8srand.String(randomStringLen))
I won't insist. IMO it is a matter of minimalism.
No need to invest in it further.

2022-05-30 13:12 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/ac0c4572609e80d2ea238f2983accbcc69bbf0f6..0f9d2691b4fe540ff7d57e5ca7df852d91d5658c): Removed random name generation from unit tests.

2022-05-30 13:13 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +func (ngs nameGeneratorStub) Name(prefix string) string {
This function now returns: `<input>-12345`

2022-05-30 13:27 UTC, EdDev approved these changes

2022-05-30 13:50 UTC, ormergi reviewed
Thanks for the changes, other then the random string generator implementation 
https://github.com/kiagnose/kiagnose/pull/89#discussion_r884635351
LGTM.

2022-05-30 14:12 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/0f9d2691b4fe540ff7d57e5ca7df852d91d5658c..45af7ff838339fb340d1a6681db9c62036954c0e): Rebase

2022-05-30 14:18 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/45af7ff838339fb340d1a6681db9c62036954c0e..0fd76854918716d4f4c0314f718a91588dd9f02f): Removed two redundant newlines.

2022-05-30 18:57 UTC, EdDev reviewed
Some newlines have been removed which I prefer untouched.

2022-05-30 18:57 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Please preserve the newline.

2022-05-30 18:57 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Please preserve the newline.

2022-05-30 18:57 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Please preserve the newline.

2022-05-30 18:57 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Please preserve the newline.

2022-05-30 18:57 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Please preserve the newline.

2022-05-30 18:57 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Please preserve the newline.

2022-05-30 18:57 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Please preserve the newline.

2022-05-30 18:57 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Please preserve the newline.

2022-05-30 18:57 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Please preserve the newline.

2022-05-30 19:14 UTC, orelmisan commented
@EdDev The linter complains about `TestCheckupTeardownShould()` being longer than 100 lines.

2022-05-30 19:50 UTC, RamLavi submitted a review, later dismissed
/lgtm

2022-05-31 10:20 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> -
Done.

2022-05-31 10:20 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> -
Done.

2022-05-31 10:20 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> -
Done.

2022-05-31 10:20 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> -
Done.

2022-05-31 10:21 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> -
Done.

2022-05-31 10:22 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/0fd76854918716d4f4c0314f718a91588dd9f02f..48d926b000209a17f46961360097052aad73be47): Rebased on PR #101.

2022-05-31 11:18 UTC, EdDev approved these changes
Thanks

2022-05-31 12:12 UTC, merged