Run checkups on its own namespace
kiagnose/kiagnose pull request #9
Opened 2022-03-28 10:13 UTC by ormergi

A checkup is treated as an untrusted application, and as such
it should be executed in an isolated way so it won't interfere
with other entities on the cluster.
When finished all related objects should be deleted, leaving
the cluster as it was before.

Checkup workspace includes a new namespace where the checkup will
run with and where all related objects will be created, such as:
- ServiceAccount
    That is granted with permissions from Roles and ClusterRoles
    that were specified at the checkup spec.
- ConfigMap
    Where the checkup results will be stored.
- Roles RoleBindings and ClusterRoleBindings
    In order to grant the permissions to the workspace SA.
- Batch Job
   That will be used to run the checkup container one time
   with the needed permissions.

This PR introduce the logic for checkup workspace creation and treardown.
In also includes an initial implementation for the checkup spec for tests.

2022-04-06 07:01 UTC, ormergi commented
Lint github action failed https://github.com/kiagnose/kiagnose/runs/5837175951?check_suite_focus=true#step:4:25
It pass on my local env.

2022-04-06 12:01 UTC, EdDev reviewed
I liked the isolation of the client, nice!

There are some comments inline.
You also used some `utils` folder/package, which you probably know I cannot accept. :)

2022-04-06 18:20 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +func New(spec *Spec) *Checkup {
Done

2022-04-06 18:20 UTC, ormergi commented on kiagnose/internal/client/client.go
> +}
Done

2022-04-06 18:21 UTC, ormergi commented on kiagnose/internal/client/client.go
> +func Create() (Client, error) {
I changed it to return concrete object

2022-04-06 18:23 UTC, ormergi commented on kiagnose/internal/utils/configmap/configmap.go
> +		Create(context.Background(), cm, metav1.CreateOptions{})
Changed it to one liner

2022-04-07 07:29 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +		},
I would suggest to minimize it to:
```
{"should create checkup", checkup.New("framework:v1", nil, nil, nil)}
```

2022-04-07 07:29 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +		},
and here to:
```
{"create checkup with Roles", checkup.New("framework:v1", nil, nil, roles())}
```

2022-04-07 07:29 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func TestNewCheckup(t *testing.T) {
I am a bit confused here.
It seems that you have exposed many of the inner structure of `checkup`. But I am not clear why.
All tests below are mechanic, they check that things got constructed.

But if we go back to the actual need from `checkup`, we wanted to just expose `Setup`, `Run` and `Teardown`.
So why all these intermediate details matter, or asking differently, why there is a need to expose everything?

2022-04-07 07:29 UTC, EdDev commented on kiagnose/internal/client/client.go
> +}
After going this again, this client is doing basically two things:
- Minimizing the `kubernetes.Interface` to only the things needed at the moment.
- Abstracting away `rest.InClusterConfig()`.

I think the second point is good, especially if there is no other place we can do it so it will be shared with multiple packages.

I do not see the usefulness of the first point. Could you please show where it helped in the production or test code?

2022-04-07 11:20 UTC, orelmisan reviewed
Thank you for the PR @ormergi.
I've reviewed the second commit's production code, please see the inline comments.

2022-04-07 11:20 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +func newCheckupJob(name, namespace, serviceAccountName, image string, envs []corev1.EnvVar) *batchv1.Job {
`activeDeadlineSeconds` field is missing from the Job's spec (the Job's timeout).

2022-04-10 12:56 UTC, EdDev requested changes

2022-04-10 12:56 UTC, EdDev commented on kiagnose/internal/checkup/namespaces/namespaces.go
> +	_, err := client.RESTClient().Delete().Resource("*").Namespace(nsName).Do(context.Background()).Get()
We are not suppose to use the `RESTClient`, right?

2022-04-10 12:56 UTC, EdDev commented on kiagnose/internal/checkup/namespaces/namespaces.go
> +		return false, nil
I'm not sure I understand this.
If there is no error or if there is an error that is not about the missing namespace, you retry.

But if the error is `!errors.IsNotFound(err)` something is wrong (e.g. communication error). Even if we should keep on trying, I would expect a log of this to be posted.

2022-04-10 12:56 UTC, EdDev commented on kiagnose/internal/checkup/namespaces/namespaces.go
> +	return wait.PollImmediate(time.Second, timeout, func() (bool, error) {
You want to retry every second for 5 min (default)? This is a bit extreme, don't you think?

We probably need to use a watcher for this, but this can be an improvement for later on. Consider opening an issue to track it (if you agree with this).

2022-04-10 12:56 UTC, EdDev commented on kiagnose/internal/checkup/namespaces/namespaces.go
> +// DeleteAndWait deletes a namespace and waits until delete
This is not in sync with the function name.
It is also unclear why it is under `namespaces` package. Perhaps elaborate in the text.

2022-04-10 13:14 UTC, EdDev commented
Also, please make most packages singular (and not plural, like `namespace`).

2022-04-10 16:20 UTC, ormergi commented on kiagnose/internal/checkup/namespaces/namespaces.go
> +// DeleteAndWait deletes a namespace and waits until delete
This is a leftover I will remove it, sorry about the noise.

2022-04-10 16:20 UTC, ormergi commented on kiagnose/internal/checkup/namespaces/namespaces.go
> +	return wait.PollImmediate(time.Second, timeout, func() (bool, error) {
I am open to other suggestions for the retry time, what you have in mind?

As for using  a watcher, I am not sure whats going to happen when the namespace is disposed
and the watcher still being used, I will give it a try and see how it goes.

2022-04-10 16:20 UTC, ormergi commented on kiagnose/internal/checkup/namespaces/namespaces.go
> +		return false, nil
Yep this is pretty much it, any other error then not-exist one is silent.
I will log the error messages.

2022-04-10 16:41 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name: name,
So we can have multiple checkups running simultaneously.

2022-04-10 16:49 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name: name,
Each checkup could run in its own random Namespace (all Namespaces will share a common prefix and a unique suffix).

2022-04-10 17:19 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +			Name: name,
Yes, sounds right to me.
Only the framework ns is constant, the checkup jobs are unique.
It is also the only way to assure this will work safely.

2022-04-11 06:26 UTC, EdDev requested changes
Great work Or.

Although I have a lot of comments, this PR looks really nice and the unit tests are very thorough.

Please also try and go over the commit messages, they need some more work.

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +}
Couldn't you just extended it? (I did not try it)
`type testClient struct { fake.Clientset }`

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	log.Printf("namespace '%s' successfully deleted", nsName)
Deleting has been successfully requested at this point, nothing more.
Actual deletion occurred after the wait period.

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	return wait.PollImmediate(time.Second, timeout, func() (bool, error) {
Polling each second is too fast IMO, consider increasing to 3 or 5.
If there is a version of polling with exponential backoff it may work best.

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/rbac/rbac.go
> +}
I think this is not used.

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/rbac/rbac.go
> +	return nil
Unlike the namespace, here you do not wait for it to be gone.
Is this intentional?

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +
You should place it somewhere after the factory or near the `Teardown` method.

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +		return concentrateErrors(errs)
It would be beneficial to mention it is a teardown failure.

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
Unrelated change

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> -
unrelated change

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func assertClusterRoleBindingNotExists(t *testing.T, testClient *testsClient) {
I suggest you keep the previous naming pattern: ``assertNoClusterRoleBindingExists`.

2022-04-11 06:26 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +func assertNamespaceNotExists(t *testing.T, testClient *testsClient) {
Same, better keep the previous name pattern.

2022-04-11 10:04 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	envVars = append(envVars, inputEnvVars...)
It is not possible to pass both single object and a slice (using ...) to append https://go.dev/play/p/Rk2sMg_Zhym
I will change envVars to be initialized with each envVar and append the slice with the rest.

2022-04-11 10:08 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/fd225ba37a6fb0dc8655775559c2b52912fee1b7..72a0be582ccab1954434a2050d3a45b368399f39) following "Introduce checkup components" review:
- Rename checkup.New() argument and local's names to be more consistent
- Initialize slices with elements instead of calling append twice.
- newCheckupJob() timeout argument is changed to int64 instead of time.Duration

2022-04-11 15:19 UTC, ormergi reviewed
[Changes](https://github.com/kiagnose/kiagnose/compare/bf689de988236a27af67e878f978912c57f31e55..b077fb93f916c260948f03919eaff9e57701ec6f) following "Delete checkup components on teardown" review

2022-04-11 15:19 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> -
I moved to previous commit.

2022-04-11 15:19 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +func assertClusterRoleBindingNotExists(t *testing.T, testClient *testsClient) {
Done

2022-04-11 15:30 UTC, ormergi commented
Commits messages were updated

2022-04-12 06:41 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +			Name: name,
This should have been added to the design to ease this discussion, we just missed it.

This is not only related to concurrency, but to proper execution. Failure for any reason to remove a namespace should not block other executions, can we agree on that?
In my view, this is no different from randomizing namespaces when running e2e tests (see k8s e2e framework).
There should be no dependencies between one run and another, be it serial or in parallel.

2022-04-12 06:43 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> -
Moved to previous commit.

2022-04-12 09:06 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name: name,
This will probably cause a change to checkup.New(), because the namespace name will be known only after its creation.

2022-04-12 09:32 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +}
Is there a problem to expose it? We are in a test, what do you see problematic by doing so?

2022-04-12 09:44 UTC, orelmisan reviewed
Hi @ormergi, I've reviewed your second and third commits, its a very nice work.
Please see the inline comments.

2022-04-12 09:44 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	backoffLimit := int32(0)
Please consider treating `defaultTerminationGracePeriod` and `backoffLimit` in the same manner (as consts).

2022-04-12 09:44 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +	}()
Why is this differed function is declared before `CreateClusterRoleBindings()`?

2022-04-13 08:47 UTC, ormergi reviewed
Changes following "Introduce checkup components" review

2022-04-13 08:47 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	backoffLimit := int32(0)
In the `defaultTerminationGracePeriod` case the linter considered it as magic number so I added a const for it,
for the `backoffLimit` it doesnt consider `0` as magic number (probably because its the default value).
If the liner would pass it I would define single variable with `:=`.

2022-04-13 08:47 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	const defaultTerminationGracePeriod = 5
In general I prefer to avoid shortening physical unit names, it is more consistent with other API's (e.g time.Duration func's use full names, k8s API's use full names for physical units), the code would look like this:
```
const defaultTerminationGracePeriodSeconds = 5
terminationGracePeriodSeconds := int64(defaultTerminationGracePeriodSeconds)
checkupPodSpec := corev1.PodTemplateSpec{
	ObjectMeta: metav1.ObjectMeta{},
	Spec: corev1.PodSpec{
	TerminationGracePeriodSeconds: &terminationGracePeriodSeconds,
        ...
```
I think its long and a bit too bulky,  note that the unit name can be understood from the code
as it is now, the usage is right next to the definition and used only one time, WDYT?

2022-04-13 11:09 UTC, ormergi commented on kiagnose/internal/checkup/rbac/rbac.go
> +	return nil
> What can happen if one job finishes and immediately another is triggered?

If by  job finishes and immediately another is triggered you mean a checkup is executed and as soon as it finish
it is being executed again, it should work fine no collisions whatsoever since the clean up is performed.

In case a checkup is executed before another is finished and both use the same `ClusterRole`, the second
checkup will fail on creating the `ClusterRoleBinding` since its already executed.
Following the discussion on https://github.com/kiagnose/kiagnose/pull/9/commits/cc7301b0c031525f1ce077d9246d90c1dd721c86#r844968232
it means that ClusterRoleBinding names should also be generated.

> Lets assume the deletion of the cluster roles is in progress and not yet finished.
Will this cause a problem? Collision? Are these objects unique?

In case the ClusterRole is being deleted the checkup will probably failed at some point
since it wont have the permissions it expects to have.

2022-04-13 11:09 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +}
In order to test `Checkup` an interface of the client is necessary.
I would also work with `kubernetes.Interface` (which default K8s clientset implements)
but you would need to figure out which of the interfaces `kubernetes.Interface` brings
a component use.
Defining our own interface for the client makes it visible and it is clear what are the dependencies.

2022-04-13 12:08 UTC, EdDev commented on kiagnose/internal/checkup/rbac/rbac.go
> +			return nil, fmt.Errorf("failed to clean up ClusterRoleBindings: %v", err)
It first failed to create, then alslo failed to clean up. I think you should add both to avoid confusion.

2022-04-14 09:36 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +func New(image string, timeout time.Duration, envVars []corev1.EnvVar, clusterRoles []rbacv1.ClusterRole, roles []rbacv1.Role) *Checkup {
@ormergi can you please receive (and save) the following types?
```
clusterRoles []*rbacv1.ClusterRole
roles []*rbacv1.Role
```
When working with the K8s API, later on, we use them as pointers.

2022-04-14 12:50 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +func New(image string, timeout time.Duration, envVars []corev1.EnvVar, clusterRoles []rbacv1.ClusterRole, roles []rbacv1.Role) *Checkup {
Done

2022-04-14 12:53 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/2e87b48e3bed4309a819c5d3199b14a95e771013..c66f8f67d2ffad85e8ef68ae225b06a2e46d8e7e) use pointers when referring to  reference types (e.g Role, ClusterRoles, etc..)

2022-04-14 13:00 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +func New(image string, timeout time.Duration, envVars []corev1.EnvVar, clusterRoles []rbacv1.ClusterRole, roles []rbacv1.Role) *Checkup {
Thank you.

2022-04-14 14:53 UTC, ormergi commented on kiagnose/internal/checkup/rbac/rbac.go
> +			return nil, fmt.Errorf("failed to clean up ClusterRoleBindings: %v", err)
Done

2022-04-14 16:09 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +func TestCheckupTeardown(t *testing.T) {
Done

2022-04-17 05:32 UTC, EdDev reviewed
Second commit.

> Introduce checkup components

checkup: Construct a checkup instance

> A checkup is treated as an untrusted application, it should
> be executed in an isolated way without interfering with other
> workloads / components in the cluster or change anything.
> When finished all related objects should be deleted, leaving
> the cluster as it was before.

Nice introduction, however, it seems not related to the actual commit.
Probably more related to the teardown one.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

> Checkup componentes includes a new namespace where all related
> objects will be created, such as:

The checkup object includes the following components:
...

> This commit introduce the logic for generating each object that is
> required for the checkup according to the user spec.

This change implements the constructions of the checkup object and its members.

2022-04-17 05:32 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +	const defaultTerminationGracePeriod = 5
I would just do this to reduce the number of names: `var terminationGracePeriod int64 = 5`.

Generally speaking, adding `Sec` to the tail will not harm anything.
At the same time, using any other name will be suffice as well (probably even `t`), just because it is just a mean to pass an address in a very localized area.

Being a nit, it does not deserve too much attention IMO.

2022-04-17 06:38 UTC, EdDev reviewed
Commit 3:

> Create checkup componentes on setup

checkup: Create components

> This commit introduce the logic for creating each of checkup
> componentes (e.g: Namespace, Job, etc..) in the cluster.

- This change ...
- typo: components

> Note about the 'launcher', since Setup() is the initialize the checkup
> it won't trigger Teardown().
> In case of failure checkup.Setup(), attempts to cleanup the object that
> already been created.
> The clean up is done by deleting the Namespace and eventually all the objects
> inside it [1].

The creation of the components is performed in the `Setup` method.
In case of failure, it will attempt to cleanup any intermediate objects.

(the part about teardown not being called when setup fails is not implemented in this change, so I would not mention it at all)

> In tests Kubernetes fake client is being used, and should be normalized
> to prevent inconsistent results when listing objects that been created
> and deleted, for example:
> With a "clean" client, where no objects were create, listing Namespaces
> will return 'nil'.
> But if a Namespace already been created and deleted, listing Namespaces
> result would be an empty Namespaces slice.

This is very confusing and hard to read.
How about something like:

```
The kubernetes fake client used in tests records objects that are created and deleted. In order to assert the results correctly, a normalization is required to some of the empty containers (slices, maps) the fake tracks. Any `nil` value is converted to an initialized empty container, allowing a semantic equality to pass.
```

2022-04-17 06:47 UTC, EdDev reviewed
Commit 4

> Delete checkup components on teardown

checkup: Delete components at teardown

2022-04-17 06:47 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +	}
This shows that we should not mix between the delete and wait parts.
It is more efficient to delete all objects first and then wait for them afterwards.

This can be optimized in a following PR.

2022-04-17 06:47 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +}
There is some duplication (and difference in assertion) with `assertNoObjectExists`.
Can you use these new assertions in the previous one?

2022-04-17 07:18 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	clusterRoleBindings []*rbacv1.ClusterRoleBinding
On the other hand, one could ask why these functions should be exported when reviewing the original commit :slightly_smiling_face:

2022-04-17 09:07 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	const defaultTerminationGracePeriod = 5
I added seconds to the const, and changed the intermediate var to compact name,
hope it will make everyone happy :slightly_smiling_face:

2022-04-17 09:29 UTC, ormergi reviewed
Also updated the commit messages title's and body according to code-review comments.

2022-04-17 09:29 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	const defaultTerminationGracePeriod = 5
I added seconds to the const, and changed the intermediate var to compact name,
hope it will make everyone happy :slightly_smiling_face:

2022-04-17 09:29 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +			Name: name,
I have oppend an issue to track this https://github.com/kiagnose/kiagnose/issues/17

2022-04-17 09:29 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	clusterRoleBindings []*rbacv1.ClusterRoleBinding
Moved to the previous commit.

2022-04-17 09:29 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +	testTimeout = time.Minute * 10
Note that in general this is how you set 10 minutes time.Duration, 
for those tests 1 minute is good enough so I removed the `* 10` part.

2022-04-17 09:29 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	}
I have opened an issue for tracking https://github.com/kiagnose/kiagnose/issues/18

2022-04-17 09:29 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +}
Done

2022-04-17 09:31 UTC, ormergi commented
@EdDev @orelmisan please take another look

2022-04-17 09:31 UTC, orelmisan reviewed
Hi @ormergi, Please see the inline comments regarding the second commit.

2022-04-17 09:31 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name: name,
@ormergi can you please open an issue about randomizing the Namespace's name?

2022-04-17 09:31 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +func newConfigMapWriterPolicyRule(cmName string) rbacv1.PolicyRule {
This function is called only once. Please consider placing its content inline.
IMO it will improve the Role definition's readability.

2022-04-17 09:31 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name:      roleName,
Shouldn't this name represent the relationship between the Role and the ServiceAccount?

2022-04-17 09:31 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name: clusterRoleName},
Shouldn't this name represent the relationship between the ClusterRole and the ServiceAccount?

2022-04-17 09:31 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +		ImagePullPolicy: corev1.PullAlways,
Why was this image pull policy selected? (and not for example `IfNotPresent`)
https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy

2022-04-17 10:24 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +			Name:      roleName,
I do not understand this comment. Please be explicit on what you think is wrong and/or provide a suggestion.

2022-04-17 10:24 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +			Name: clusterRoleName},
I do not understand this comment. Please be explicit on what you think is wrong and/or provide a suggestion.

2022-04-17 10:34 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +)
I placed the const part just before New() for visibility because its the place where it is being used.
Note that the checkup struct also use an interface that is defined just before it, meaning the const block
will be at the top of the file and might make it hard to follow.

I just realized that there are const that are being used only at New(), I moved them inside (job and env var names consts).

2022-04-17 10:34 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +func New(image string, timeout time.Duration, envVars []corev1.EnvVar, clusterRoles []*rbacv1.ClusterRole, _ []*rbacv1.Role) *Checkup {
We discussed it offline and realized that it will require forwarder changes to the code and tests and it is not 
a must for the MVP to work, if no one objects I prefer to do it on a follow up PR so we can get done
with this one.
I have opened an issue to tack this https://github.com/kiagnose/kiagnose/issues/20

2022-04-17 10:34 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +func newConfigMapWriterPolicyRule(cmName string) rbacv1.PolicyRule {
I am planning to handle Roles on a follow up PR this will probably changed as well, I have opened an issue to tack this #20.

2022-04-17 10:34 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +			Name:      roleName,
I am planning to handle Roles on a follow up PR this will probably changed as well, I have opened an issue to tack this https://github.com/kiagnose/kiagnose/issues/20.

2022-04-17 10:34 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +			Name: clusterRoleName},
Not sure what is the convention, since its going to be ephemeral object I left the name as is.
Please let me know if you have suggestion how it should be named.

2022-04-17 10:34 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +		ImagePullPolicy: corev1.PullAlways,
Currently the framework user cannot control this, if the image pull policy it will be set to `IfNotPresent` by default,
there might be a case where new revisions of a checkup image exists but wont be fetched, ending up with 
the framework keep executing the old revision of a checkup image.

2022-04-17 10:42 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name:      roleName,
We could use something like <RoleName>-<ServiceAccount_name> or vice versa.
I'll look for a convention.

2022-04-17 10:43 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name: clusterRoleName},
We could use something like `<ClusterRoleName>-<ServiceAccount_name>` or vice versa.
I'll look for a convention.

2022-04-17 10:49 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	}
Done

2022-04-17 10:49 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +	}
Done

2022-04-17 10:51 UTC, ormergi commented
I pushed new [changes](https://github.com/kiagnose/kiagnose/compare/09f3644aa6220d0a7a63a24d4bc5b8f8e168dfa2..19c1fbc807dade6c48d256548abe01b53738fa99) following 
https://github.com/kiagnose/kiagnose/pull/9#discussion_r851725702
https://github.com/kiagnose/kiagnose/pull/9#discussion_r851725752
And also https://github.com/kiagnose/kiagnose/pull/9#discussion_r851726591
to somthing nicer.

2022-04-17 10:52 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +		ImagePullPolicy: corev1.PullAlways,
We are not suppose to set it to a tag like `latest` but to a digest. In such a case, it has no meaning IMO and saves you from problems like connectivity to the registry.
What is the setting in other large projects? E.g. kubevirt.

2022-04-17 10:55 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +	testTimeout = time.Minute
nit: You changed it in the wrong commit.

2022-04-17 11:02 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +			Name: clusterRoleName},
You are talking about adding a posix to the binding name?
If it is to use some addition it is from the subject passes in, otherwise the caller should construct the name.

But this is only relevant if you expect more than one binding to be associated to the same ClusterRole. Is this the case?

2022-04-17 11:20 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +		ImagePullPolicy: corev1.PullAlways,
Yes it is the best practice but it doesn't mean that every one follows it, I set this pull policy so that the framework will do best effort to get the right image.
On Kubevirt the image pull policy is controllable via `Kubevirts` custom resource 
https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/api/core/v1/types.go#L1629

2022-04-17 11:28 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +		ImagePullPolicy: corev1.PullAlways,
And what is kubevirt default value set there?

2022-04-17 12:13 UTC, orelmisan reviewed
Hi @ormergi, I've reviewed most of the third commit.
Please see the inline comments.

2022-04-17 12:13 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +	actualNs, err := testClient.Tracker().Get(gvr, "", checkup.NamespaceName)
Can this be performed using the "Regular" `corev1().Namespaces().Get()`?
Why is it necessary to use `testClient.Tracker().Get()`

2022-04-17 12:22 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name: clusterRoleName},
Consider a scenario:
You have a ClusterRole named `kubvirt-reader`.
You have checkup A and checkup B who needs to run simultaneously and use kubvirt-reader .
With the current implementation, the second checkup to run will fail to create the ClusterRoleBinding because it already exists.

2022-04-17 12:25 UTC, orelmisan commented on kiagnose/internal/checkup/checkup.go
> +			Name: clusterRoleName},
Furthermore, a cluster admin who will run:
```
kubectl get clusterrolebindings
``` 

Will see a ClusterRoleBinding with the same name as the Role.

2022-04-17 12:34 UTC, EdDev commented on kiagnose/internal/checkup/checkup.go
> +			Name: clusterRoleName},
Ok, so it is a name randomization issue and we can defer it with all the other ones.
Ref: #17

2022-04-17 12:40 UTC, ormergi commented on kiagnose/internal/checkup/checkup.go
> +		ImagePullPolicy: corev1.PullAlways,
@EdDev  
> And what is kubevirt default value set there?
It is not clear from the docs what Kubevirt does by default, I think its `IfNotPresent`.

We can use the default policy meaning to no specify anything, it looks good enough
https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting

2022-04-17 13:42 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +	assert.Equal(t, checkup.NewNamespace(checkup.NamespaceName), actualNs)
It checks that the client has the expected data, and that data is created from the production code.
If you claim that we need to duplicate this creation of the data in the test, it means we couple it strongly to the implementation (i.e. if the content of the namespace creation in this case changes, we need to change the test).

Coupling the tests in this manner requires a very good reasoning.
Do you have one?

Perhaps this can help look at this from a different angle: We are not interested to check if the structure contains the correct data, we are interested to check if the logic of adding it, deleting it and so on works as expected.
One could claim that we also need to assert the exact correct data we want to reach the API, but that sounds like a useless test to me. We do not change the data, if we did, we should have checked it explicitly and then such a test would have made sense.

2022-04-17 13:47 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	namespace, err = client.Namespaces().Create(context.Background(), namespace, metav1.CreateOptions{})
You will have to elaborate and provide a suggestion. I do not really understand what you mean by this.

2022-04-17 13:50 UTC, orelmisan commented on kiagnose/internal/checkup/namespace/namespace.go
> +	namespace, err = client.Namespaces().Create(context.Background(), namespace, metav1.CreateOptions{})
I have provided a suggestion.
I suggested to remove the `var err error` and replace it with the short variable declaration stated above.

2022-04-17 13:52 UTC, orelmisan commented on kiagnose/internal/checkup/namespace/namespace.go
> +	namespace, err = client.Namespaces().Create(context.Background(), namespace, metav1.CreateOptions{})
BTW, all other calls to K8s client in the code are using the short variable declaration:
```go
someObject, err := someAPICall()
```

2022-04-17 13:55 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +	assert.Equal(t, checkup.NewNamespace(checkup.NamespaceName), actualNs)
> We are not interested to check if the structure contains the correct data, we are interested to check if the logic of adding it, deleting it and so on works as expected.

Fine by me.
Thanks for the clarification.

2022-04-17 13:59 UTC, EdDev commented on kiagnose/internal/checkup/namespace/namespace.go
> +	namespace, err = client.Namespaces().Create(context.Background(), namespace, metav1.CreateOptions{})
Ohh so you mean to ask:
> Why do we need `var err error` here?

Well, I guess the confusion is on which line you commented and the indirect ref to this `err` thing.

I guess the intention was to use the same variable that came as an argument.
That is not really needed, and it can also renamed to something short like `ns`.
Whatever works for you guys, I am fine with all options, seems like a nit to me.

2022-04-17 14:21 UTC, orelmisan commented on kiagnose/internal/checkup/namespace/namespace.go
> +	namespace, err = client.Namespaces().Create(context.Background(), namespace, metav1.CreateOptions{})
> I guess the intention was to use the same variable that came as an argument.

I haven't noticed it in the first read.
This is a nit, sorry for not marking it correctly.

2022-04-17 14:55 UTC, ormergi commented on kiagnose/internal/checkup/namespace/namespace.go
> +	log.Printf("deleted namespace '%s' request sent", nsName)
Done (all over)

2022-04-17 14:55 UTC, ormergi commented on kiagnose/internal/checkup/rbac/rbac.go
> +}
What does it matter if its from another API group?
Note that `rbac` package provides helpers for working with k8s RBAC objects, 
ServiceAccount is part of it eventough its not from the same API group as other 
objects.

2022-04-17 14:55 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +	actualNs, err := testClient.Tracker().Get(gvr, "", checkup.NamespaceName)
Yes it can work, the problem is that if you inject some mocking logic (e.g: return error when an object is created)
and the test triggers it as part of its assertion it will never pass and wont make sense.

For example: 
A test that checks, that checkup Setup() fails when it fails  to create a Namespace.
First we inject an error to the client when Namespace is created, then verify that no such object exists.
If we use `corev1().Namespaces().Get()` it will fail due to the injected error,
but if we use `testClient.Tracker().Get()` it will work as expected.

2022-04-17 14:55 UTC, ormergi commented on kiagnose/internal/checkup/namespace/namespace.go
> +	namespace, err = client.Namespaces().Create(context.Background(), namespace, metav1.CreateOptions{})
Done

2022-04-17 14:55 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +	testTimeout = time.Minute
Done

2022-04-17 15:07 UTC, orelmisan commented on kiagnose/internal/checkup/checkup_test.go
> +	actualNs, err := testClient.Tracker().Get(gvr, "", checkup.NamespaceName)
Thank you for the explanation.

2022-04-17 15:42 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/534b2bc3b8922a311cca7ba917ff1f5268fb2c20..52f25853b751a9e622f1e1ce93ebc4d58b78f1e8): added unit test for creating correspond ClusterRoleBinding to additional ClusterRoles

2022-04-17 15:48 UTC, ormergi commented
Changes [[1]](https://github.com/kiagnose/kiagnose/compare/534b2bc3b8922a311cca7ba917ff1f5268fb2c20..52f25853b751a9e622f1e1ce93ebc4d58b78f1e8) [[2]](https://github.com/kiagnose/kiagnose/compare/534b2bc3b8922a311cca7ba917ff1f5268fb2c20..52f25853b751a9e622f1e1ce93ebc4d58b78f1e8): added unit test for creating correspond ClusterRoleBinding to additional ClusterRoles

2022-04-17 15:52 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +	ns, err := testClient.listClusterRoleBindings()
This `ns` is a copy/paste leftover probably.

2022-04-17 16:01 UTC, EdDev commented on kiagnose/internal/checkup/checkup_test.go
> +	object, err := testClient.Tracker().List(gvr, gvk, "")
I think you can use `testClient.listClusterRoleBindings()`

2022-04-17 16:12 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +	ns, err := testClient.listClusterRoleBindings()
Done

2022-04-17 16:12 UTC, ormergi commented on kiagnose/internal/checkup/checkup_test.go
> +	object, err := testClient.Tracker().List(gvr, gvk, "")
Done

2022-04-17 16:23 UTC, orelmisan approved these changes
Thank you!

2022-04-17 16:38 UTC, EdDev approved these changes
Great, thanks!

2022-04-18 05:52 UTC, merged