latency, e2e: Add cleanup target
kiagnose/kiagnose pull request #90
Opened 2022-05-25 10:15 UTC by orelmisan

Add a `--cleanup` target to vm latency checkup `e2e.sh` script.
The target removes the user-supplied Job and ConfigMap objects.

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-05-25 10:32 UTC, RamLavi commented
Not a must, but do we want to add this as an extra step to `--run-tests` as well (around [here](https://github.com/kiagnose/kiagnose/blob/main/checkups/kubevirt-vm-latency/automation/e2e.sh#L166))?

imo it kinda makes sense that before a tests starts then the remnants of the former one are removed.

2022-05-25 10:44 UTC, orelmisan commented
> Not a must, but do we want to add this as an extra step to `--run-tests` as well (around [here](https://github.com/kiagnose/kiagnose/blob/main/checkups/kubevirt-vm-latency/automation/e2e.sh#L166))?
> 
> imo it kinda makes sense that before a tests starts then the remnants of the former one are removed. (AFAIU it's not a must because with #89 merged then we won't get cross-test issues.)

PR #89 will not solve this problem.
The user-supplied ConfigMap and Job objects are deployed to the `kiagnose` namespace which exists as long as the kiagnose framework is installed.

For this we can use other measures:
1. Add `ttlSecondsAfterFinished` field to the user-supplied Job - the Job will be automatically deleted after this amount of seconds.
2. Add a cron job to periodically delete ConfigMap objects of completed checkups @EdDev had suggested it in the past.

IMO the cleanup should be manual, so people will not unintentionally delete data (checkup results, logs, etc).

2022-05-25 10:52 UTC, RamLavi approved these changes
/lgtm

2022-05-26 06:57 UTC, EdDev commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +  ${KUBECTL} delete configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE}
What about the namespace? I thought that deleting it, will also cause the other stuff to get removed.
I am also missing ClusterRoles, NAD, etc...

2022-05-26 08:02 UTC, orelmisan commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +  ${KUBECTL} delete configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE}
The `cleanup` target (as I see it) is supposed to help you quickly re-run tests during local development (without deleting the whole cluster).

Example usage:
```bash
./checkups/kubevirt-vm-latency/automation/make.sh --e2e -- --run-tests
./checkups/kubevirt-vm-latency/automation/make.sh --e2e -- --cleanup
# Optional rebuild and re-deploy checkup / framework image
./checkups/kubevirt-vm-latency/automation/make.sh --e2e -- --run-tests
```

We can clean all the objects created in the cluster, but it will take more time, and require more work to re-run a test.

2022-05-26 09:24 UTC, EdDev commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +  ${KUBECTL} delete configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE}
The target name hints it is a cleanup for what other targets in this script do. So if it is not the kiagnose ns, then all the rest.

If the objective is just to run the tests quickly, then there is no need for a target. It is just a step in the test target. But IMO this is not the common case needed. Changing the code of the checkup requires rebuild, reload and the rest.

2022-05-29 16:11 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +  ${KUBECTL} delete configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE}
Note that at the current state, the checkup namespace (checkup-workspace) may exist from previous execution (in case e2e.sh is terminated), I think it should also be deleted.

Its seems that it is not the scope of this PR, but it worth to do similar target for the framework.

2022-05-30 19:18 UTC, RamLavi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +  ${KUBECTL} delete configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE}
my 2 cents: the goal IMO of this PR is to be able to run `--run-tests` repeatedly without it getting stuck on leftovers. 
however it seems that removing the `kiagnose` namespace entirely fails when we reran `--run-tests` cause the test expected the `kiagnose` namespace to be there (for the cm for example).

So I would vote that the framework namespace (aka `kiagnose`) stays when cleaning up. It also makes sense, cause the framework doesn't necessarily have to be removed every test run.

2022-05-30 19:21 UTC, RamLavi requested changes

2022-05-30 19:21 UTC, RamLavi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +  ${KUBECTL} delete job ${KIAGNOSE_JOB} -n ${KIAGNOSE_NAMESPACE}
```suggestion
  ${KUBECTL} delete job ${KIAGNOSE_JOB} -n ${KIAGNOSE_NAMESPACE} --ignore-not-found
```

2022-05-30 19:21 UTC, RamLavi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +  ${KUBECTL} delete configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE}
```suggestion
  ${KUBECTL} delete configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} --ignore-not-found
```

2022-05-30 19:39 UTC, orelmisan commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +  ${KUBECTL} delete job ${KIAGNOSE_JOB} -n ${KIAGNOSE_NAMESPACE}
Done.
Thanks for the suggestion!

2022-05-30 19:40 UTC, orelmisan commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +  ${KUBECTL} delete configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE}
Done.

2022-05-30 19:40 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/4cc2187e1da43c08bdcd782e0e1dee259f551194..794b805cefbef883d65bb1daf3a903ca4902ecb4): Added `--ignore-not-found` option to `kubectl delete` commands.

2022-05-31 11:50 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/794b805cefbef883d65bb1daf3a903ca4902ecb4..dbafcc258eca51ecf308852528005f36136caf8c): Rebase
Changed target name to `clean-run`.

2022-05-31 12:15 UTC, EdDev approved these changes
Thanks!

@ormergi, @RamLavi  please take a look.

2022-05-31 12:32 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/dbafcc258eca51ecf308852528005f36136caf8c..104d9201921b8311c598471a2fda28f8afbd6c05): Rebase
Removed redundant new line.

2022-05-31 12:32 UTC, orelmisan commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +
Done.

2022-05-31 13:15 UTC, RamLavi approved these changes
/lgtm

2022-05-31 13:16 UTC, EdDev approved these changes
Thanks!

2022-05-31 13:16 UTC, merged