README: Add initial usage instructions
kiagnose/kiagnose pull request #93
Opened 2022-05-25 18:39 UTC by orelmisan

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-05-26 07:06 UTC, phoracek commented on README.md
> +$ git clone https://github.com/kiagnose/kiagnose.git
Would you please drop the leading $? So I can triple-click the line to select all and then just paste it as-is into my terminal

2022-05-26 07:29 UTC, orelmisan commented on README.md
> +$ git clone https://github.com/kiagnose/kiagnose.git
Sure.

2022-05-26 07:54 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/c1bf15c17b045c44ac421219cf8d11600dfa04f3..9b297612994077fd6b794163c8fea28a06d67cb4): Removed `$` sign from shell input examples.

2022-05-26 08:13 UTC, RamLavi requested changes
Very helpful and good README. add a few comments and questions.

2022-05-26 08:13 UTC, RamLavi commented on README.md
> +
I think we need to add here an explanation of what this `framework Job` does. something like:
```
The framework job will initiate the checkup job inside a dedicated checkup namespace.
```

2022-05-26 08:13 UTC, RamLavi commented on README.md
> +After the framework Job had been completed, the results should be concatenated
```suggestion
After the framework Job had been completed running the checkup job, the results should be concatenated
```

2022-05-26 08:13 UTC, RamLavi commented on README.md
> +3. Apply the following manifest (as a cluster administrator user):
Today, we only apply this manifest, but tomorrow we many want to do more complicated stuff, why not put the proper make.sh command?

2022-05-26 09:31 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/9b297612994077fd6b794163c8fea28a06d67cb4..87a9035e5f44dc34006fa0c190e8d437fe6ae82b): Answered code-review comments.

2022-05-26 09:32 UTC, orelmisan commented on README.md
> +## Installation
Done.

2022-05-26 09:33 UTC, orelmisan commented on README.md
> +The checkup vendor should provide:
It was added to the preface at the beginning of the document.

2022-05-26 09:33 UTC, orelmisan commented on README.md
> +1. Make sure the checkup's image is accessible to your cluster.
I've added a sub-title above the instructions.

2022-05-26 09:34 UTC, orelmisan commented on README.md
> +The ConfigMap object is created in the `kiagnose` Namespace (created during the installation).
Done.

2022-05-26 09:37 UTC, orelmisan commented on README.md
> +## Checkup Removal
One of the constraints we've had at the beginning of the project was that the only utility needed for controlling the framework is `kubectl`.

2022-05-26 09:38 UTC, orelmisan commented on README.md
> +
Added a short description of the framework's main process.

2022-05-26 09:40 UTC, orelmisan commented on README.md
> +After the framework Job had been completed, the results should be concatenated
I'm having a hard time deciding on how to get this sentence right and not cumbersome.

2022-05-26 09:41 UTC, orelmisan commented on README.md
> +3. Apply the following manifest (as a cluster administrator user):
As I've written in a previous comment, the usage of `kubectl` as the only utility needed to control the framework is a project constraint.

2022-05-26 11:56 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/87a9035e5f44dc34006fa0c190e8d437fe6ae82b..2ee4ff04f55590292eb7f2d440707ab983761b83): Added cleanup instruction after the checkup execution had finished.

2022-05-26 11:57 UTC, RamLavi requested changes

2022-05-26 11:57 UTC, RamLavi commented on README.md
> +The checkup vendor should provide:
```suggestion
A vendor creating a checkup should provide:
```

2022-05-26 11:57 UTC, RamLavi commented on README.md
> +3. A manifest file with the checkup's required permissions (ClusterRole objects).
```suggestion
3. A ClusterRole manifest yaml file with the checkup's required permissions.
```

2022-05-26 11:57 UTC, RamLavi commented on README.md
> +After the framework Job had been completed, the results should be concatenated
perhaps cut to 2 sentences, suggestion:
```
The framework Job waits until the checkup job is completed. Then the results are added to the user-supplied ConfigMap object:
```

2022-05-26 12:12 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/2ee4ff04f55590292eb7f2d440707ab983761b83..8e353a2b4ddfd3acccf68efd0afc89c0937aabb9): Answered code review comments.
Added input / output fields sub-titles.

2022-05-26 12:12 UTC, orelmisan commented on README.md
> +The checkup vendor should provide:
Done.

2022-05-26 12:14 UTC, orelmisan commented on README.md
> +After the framework Job had been completed, the results should be concatenated
@RamLavi Thank you for the suggestion.
I've changed it to something similar.

2022-05-26 12:15 UTC, orelmisan commented on README.md
> +3. A manifest file with the checkup's required permissions (ClusterRole objects).
@RamLavi Thank you for the suggestion.
I've changed it to something similar.
BTW, the original design had included the ability to use both `ClusterRole` and `Role` objects so I've tried to keep the sentence open for this future addition.

2022-05-29 14:12 UTC, RamLavi submitted a review, later dismissed
Thanks! 
/lgtm

2022-05-30 14:45 UTC, phoracek reviewed
One minor note. The rest is really awesome, great job

2022-05-30 14:45 UTC, phoracek commented on README.md
> +## Removal
```suggestion
## Removal
```
```suggestion
## Framework Removal
```

So it is consistent with other headlines

2022-05-30 18:44 UTC, orelmisan commented on README.md
> +## Removal
Done.
Thanks for catching this!

2022-05-30 18:45 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/8e353a2b4ddfd3acccf68efd0afc89c0937aabb9..f19a235bfb8e7d11f978bd6cf036d0796d84a5a8): Answered code review [comment](https://github.com/kiagnose/kiagnose/pull/93#discussion_r884899840).

2022-05-31 08:03 UTC, phoracek submitted a review, later dismissed

2022-05-31 13:16 UTC, RamLavi approved these changes
/lgtm

2022-05-31 13:26 UTC, RamLavi submitted a review, later dismissed
/lgtm

2022-05-31 19:42 UTC, EdDev requested changes
Very nice, thank you.

I have some small comments, but the general content and structure is very good.
I would try and move out details to other README.* files (not too many), keeping the main README simple and easy to read.

Please also add a section about the reference (with a link to its file).
You could do that in a following PR or a separate commit.

2022-05-31 19:42 UTC, EdDev commented on README.md
> +# Usage
Can you place an `Example` section above this one?
Either as a small play or just a snippet that can be copy/pasted, showing the expected result.

It is usually more beneficial to show the thing at work than explain in details all the rest.

2022-05-31 19:42 UTC, EdDev commented on README.md
> +## Framework Removal
Please use the name Kiagnose instead of "Framework".

2022-05-31 19:42 UTC, EdDev commented on README.md
> +```
Assuming we do not know from where the user started, I think this needs to be dropped and just mention at the next point from where the command is expected to be executed (e.g. `from the project root`).

2022-05-31 19:42 UTC, EdDev commented on README.md
> +> **_WARNING:_** It is your responsibility as a cluster admin to **ALWAYS** check the checkup's **image** and **permissions**
I it like less when the sentences talk directly to the reader. I would prefer a non direct approach, e.g. "It is up to the cluster administrator to ...".
I would also add: "One should make sure a trustful checkup is used.".

2022-06-01 05:34 UTC, orelmisan commented on README.md
> +The framework runs each checkup in a dedicated ephemeral Namespace, which is disposed when the checkup ends.
Done.

2022-06-01 05:34 UTC, orelmisan commented on README.md
> +[kiagnose](https://github.com/kiagnose/kiagnose) is a [Kubernetes](https://kubernetes.io) diagnostic framework which enables validation of cluster functionality.
Done.

2022-06-01 05:35 UTC, orelmisan commented on README.md
> +## Framework Installation
Done.

2022-06-01 05:35 UTC, orelmisan commented on README.md
> +## Framework Removal
Done.

2022-06-01 05:35 UTC, orelmisan commented on README.md
> +```
Done.

2022-06-01 05:35 UTC, orelmisan commented on README.md
> +> **_WARNING:_** It is your responsibility as a cluster admin to **ALWAYS** check the checkup's **image** and **permissions**
Done.

2022-06-01 05:35 UTC, orelmisan commented on README.md
> +| spec.param.*      | Arbitrary strings that will be passed to the checkup                          | No        | [0..N]                                |
Done.

2022-06-01 05:35 UTC, orelmisan commented on README.md
> +In order to execute a checkup, we need to run a framework Job.
Done.

2022-06-01 05:35 UTC, orelmisan commented on README.md
> +After the framework Job had completed, the results could be retrieved from the user-supplied ConfigMap object:
Done.

2022-06-01 05:36 UTC, orelmisan commented
Change: Rebase
Answered review comments.

2022-06-01 05:46 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/02681a529d48d5b7709e20624d95793a4b7650aa..911f4ea783fa76f6b37607ee1c096c50194dbbf6): Squashed the two commits into one.

2022-06-01 06:34 UTC, EdDev approved these changes
Thank you!

Except the initial example, all seems in place and good.
I do not want to delay it on that example, I think it can be added in a following PR if you have the time.

2022-06-01 06:40 UTC, merged

2022-06-01 06:40 UTC, orelmisan commented on README.md
> +# Usage
@EdDev as you've suggested, we'll add this in a follow-up PR.