kubevirt-vm-latency: Support bridge networks
kiagnose/kiagnose pull request #94
Opened 2022-05-26 08:07 UTC by ormergi

Currently the checkup supports SR-IOV networks only, it defines the VMs interface with SR-IOV binding method 
regardless of the `NetworkAttachmentDefinition` (NAD) spec.

With this PR changes the checkup will detect which CNI plugin is being used by the given NAD and define the 
VMs interfaces accordingly.
If the bridge CNI is being used the VMs interfaces will be defined with bridge binding method.

2022-05-26 10:56 UTC, orelmisan reviewed
Thank you for the PR @ormergi!
Can you please separate the pre-flight part to another PR?

2022-05-26 13:45 UTC, ormergi commented
> Thank you for the PR @ormergi! Can you please separate the pre-flight part to another PR?

Done, first commit is moved to https://github.com/kiagnose/kiagnose/pull/97

2022-05-26 15:26 UTC, ormergi commented
/cc @EdDev

2022-05-29 15:36 UTC, ormergi commented
@orelmisan @EdDev please take another look.

2022-05-31 09:56 UTC, ormergi commented
Rebased

2022-05-31 12:57 UTC, RamLavi commented
> By supporting bridge network it will enable running the checkup on environment with SR-IOV hardware
> such as CI and dev environments.

you mean `without SR-IOV hardware` right?

2022-05-31 13:31 UTC, ormergi commented
> > By supporting bridge network it will enable running the checkup on environment with SR-IOV hardware
> > such as CI and dev environments.
> 
> you mean `without SR-IOV hardware` right?

Right, thanks for the heads up I will fix it.

2022-06-01 06:14 UTC, orelmisan reviewed
Thank you for the PR @ormergi!

First commit - Please see the inline comment.

2022-06-01 06:14 UTC, orelmisan commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
> +	testClient.returnNetAttachDef = &netattdefv1.NetworkAttachmentDefinition{}
Please consider moving this line:  
```go
testClient := newFakeClient()
testClient.returnNetAttachDef = &netattdefv1.NetworkAttachmentDefinition{}
testCheckup := checkup.New(
		testClient,
		k8scorev1.NamespaceDefault,
		config.CheckupParameters{},
		&checkerStub{},
	)
```

Or if it makes more sense - you can even receive it as a parameter of the factory function:
```go
testClient := newFakeClient(&netattdefv1.NetworkAttachmentDefinition{})
```

2022-06-01 06:20 UTC, orelmisan reviewed
@ormergi in the second commit, can you please explain how `clientStub{}` records the created interfaces on each create?

2022-06-01 06:56 UTC, ormergi commented
> @ormergi in the third commit, can you please explain how `clientStub{}` records the created interfaces on each create?

`clientStub{}` saves each VM that was created at `clientStub.createdVmis, tests will assert on each VM interfaces and check equality to expected interface.
Does it answer your question?

2022-06-01 12:12 UTC, EdDev requested changes
First commit review.

2022-06-01 12:12 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	var err error
I do not understand why this error declaration move was needed. I think it was better before.

2022-06-01 12:12 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +		vmi.WithMultusNetwork(networkName, fmt.Sprintf("%s/%s", netAttachDef.Namespace, netAttachDef.Name)),
nit: This could have been simpler: `a + "/" + b`

2022-06-01 12:12 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	if c.netAttachDef, err = c.client.GetNetworkAttachmentDefinition(
It looks like you just coupled together the preflight check with populating the NAD.
Doesn't it seem odd to you? To me it shows we do not need the preflight at all.

2022-06-01 12:47 UTC, EdDev requested changes
Reviewed `vmlatency: Introduce NetworkAttachmentDefinition config parser`.

2022-06-01 12:47 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +package netattachdef
Missing header

2022-06-01 12:47 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +func ParseCniPlugins(config string) []string {
> Since the NAD Spec.Config does not have well formed API its not easy to unmarshal and requires multiple conversions and type checking.

I do not understand where this is coming from. What exactly is not well defined?
You are suppose to fetch the `config` value and then parse its content as json. Why is that problematic?

2022-06-01 12:47 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser_test.go
> +package netattachdef_test
missing header

2022-06-01 13:36 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +func ParseCniPlugins(config string) []string {
`NetworkAttachmentDefinition` spec may use more then one plugin, in this case `config` will have `plugins` array instead of just `"type": <plugin name>`.
That the parser should realize it and parse `config` accordingly (`map[string]interface{}` vs `[]map[string][]interface{}`),
it means much more conversions logic instead of "grepping" the expected string (`"type": "sriov"`).

2022-06-01 15:06 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	if c.netAttachDef, err = c.client.GetNetworkAttachmentDefinition(
Do you expect the NAD to be fetched again at setup()?

If there were more preflight checks will you think differently (i.e: that there is value in preflight())?

2022-06-01 15:08 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	var err error
It was a leftover, sorry for the noise I reverted it to how to was.

2022-06-01 15:08 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
> +	testClient.returnNetAttachDef = &netattdefv1.NetworkAttachmentDefinition{}
You mean as an argument of `newFakeClient()`?

2022-06-01 15:32 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
> +	testClient.returnNetAttachDef = &netattdefv1.NetworkAttachmentDefinition{}
I see it is just initialized, why there is a need to pass it in as an argument?

2022-06-01 15:34 UTC, ormergi commented
@EdDev following https://github.com/kiagnose/kiagnose/pull/94#issuecomment-1143743706,
Now I realized that the tests pass with or w/o converting `clientStub{}` methods to have pointer receiver, 
because there is no assertion on `clientStub.createdVmis` slice:
https://github.com/kiagnose/kiagnose/blob/6e649f2677d7badc9252c46b4bddcbbad6bfe7e2/checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go#L159-L179
Adding this assertion makes the test fail (as expected) when `clientStub{}`methods to have pointer receiver.

Now answering the question why having pointer reciver in the first place, 
looking at [CreateVirtualMachineInstance()](https://github.com/kiagnose/kiagnose/blob/6e649f2677d7badc9252c46b4bddcbbad6bfe7e2/checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go#L227-L230) we can see that if the receiver is not configured as a pointer, `clientStub{}` will be discarded when it returns.
Here is a nice explanation with [another example](https://github.com/dominikh/go-staticcheck/issues/27)

2022-06-01 18:10 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	if c.netAttachDef, err = c.client.GetNetworkAttachmentDefinition(
> Do you expect the NAD to be fetched again at setup()?

Not really, this is why I am saying we do not need preflight at the moment.

> If there were more preflight checks will you think differently (i.e: that there is value in preflight())?

Sure, but then I would not check here things that we already need later on. I would check in the preflight only the parts I do not need to directly grab later. Do we have stuff like that?

2022-06-01 18:54 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +func ParseCniPlugins(config string) []string {
Parsing the CNI sounds the right thing to do IMO, anything else is really a hack.
Have you tried to use https://github.com/containernetworking/cni/tree/main/libcni ?

I am willing to take the existing solution if you are willing to invest in the libcni soon after.

2022-06-02 08:50 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
> +	testClient.returnNetAttachDef = &netattdefv1.NetworkAttachmentDefinition{}
At first I tough that it will eventually hide more details from the reviewer (the the client act like NetAttachDef exists),
passing the  NetAttachDef as argument my improve visibility, maybe I am over thinking it.. 

I changed `newFakeClient` to have this, we plan to change those tests anyway or at least the client
if we see its not readable enough we will improve it later.

2022-06-02 08:52 UTC, ormergi commented
[Change](https://github.com/kiagnose/kiagnose/compare/4fb8c2860f3184d1cd406f3aed22c9e78239e9e3..0effb2faee57bda23172f72787e23874418c77ca): address https://github.com/kiagnose/kiagnose/pull/94/commits/6491c3b3250bef8b3cd124a1c8dfdd258e3a43d3#r886726148, change `launcher_test.go` `fakeClient` to act like a NetworkAttachmentDefinition exists.

2022-06-02 14:02 UTC, RamLavi requested changes
Added some comments

2022-06-02 17:18 UTC, ormergi reviewed
[Changes](https://github.com/kiagnose/kiagnose/pull/94/commits/5485da7047a42031d898fa2dec6c3d08ae0cdb63#r886728686): Updated commit message with supported CNI plugins, and tests description.

2022-06-02 17:18 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +			"create VMs with bridge interface",
Done

2022-06-02 17:18 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +			"when NetAttachDef uses SR-IOV CNI, create VMs with SR-IOV interface",
Done

2022-06-06 06:30 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	var err error
I know. if we decide to keep it, then please make sire we keep things neat and documented

2022-06-06 06:38 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +		for groupNameIdx, groupName := range names {
yeah, but [looks](https://go.dev/play/p/EoAj5dEg7Yz) like `names` is holding 2 items, where it should only hold 1. Perhaps  `SubexpNames` is not be the regex method we want?

2022-06-06 09:08 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +		for groupNameIdx, groupName := range names {
It is expected, from `SubexpNames` doc "..Since the Regexp as a whole cannot be named, names[0] is always the empty string.." 
https://pkg.go.dev/regexp#Regexp.SubexpNames

2022-06-06 09:37 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	if c.netAttachDef, err = c.client.GetNetworkAttachmentDefinition(
Here are the checks we had in mind: https://github.com/kiagnose/kiagnose/blob/8afde099232eb886c12220576f5d76a6b1959dd0/docs/vm_latency_checkup_design.md#prerequisites-validation
(1), (2)  and I think also (3) should be performed only at `preflight()`.

2022-06-06 10:09 UTC, RamLavi commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +		for groupNameIdx, groupName := range names {
Sounds to me like a issue waiting to happen. I would suggest explicitly ignoring the empty string, so that the programmer who did not run it locally - can acknowledge it is there.

2022-06-06 10:21 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +		for groupNameIdx, groupName := range names {
Why? it seems that this is the design, it is also documented.
I am not sure what you mean by ignoring the empty string explicitly, could you provide an example?

Note that by using group names and `SubexpNames()` there is no need to hard code the index and avoid magic numbers.

2022-06-07 10:15 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	if containsString(netattachdef.ParseCniPlugins(netAttachDef.Spec.Config), netattachdef.SriovCniPluginName) {
At this level, I would expect to see here an abstraction of all this.
Something like: `if netattachdef.IsSRIOV(netAttachDef) {...}`

2022-06-07 10:15 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +			}
Please assert the full state.
If this fails, we are left with partial data.

2022-06-07 10:15 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +	c.createdVmis = append(c.createdVmis, v)
The change of the clientStub pointer receiver has been done in the previous commit, but only used here.
For the reviewing sake, it was useful. However, I must admit I did not understand in the previous commit message that you do that because a following commit mutated the stub. Perhaps you should mention that.

2022-06-07 14:11 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/4f458e803ce7c8e092ab57dbadcc443d07f96d32..6493ac8a77410fbcdd9ad7ceaeb45b71c325abaa): Prase NetworkAttachmentDefinition using `libcni`

2022-06-07 15:21 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	if containsString(netattachdef.ParseCniPlugins(netAttachDef.Spec.Config), netattachdef.SriovCniPluginName) {
Done

2022-06-07 15:22 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +type testCase struct {
I renamed this struct name.

2022-06-08 05:28 UTC, EdDev reviewed
> Checkup{}'should hold an instance of the NetworkAttachmentDefinition
> because it should be used by Setup(), in order to detect the CNI plugin that
> being used and define the VMs interface accordingly.

There are too much implementation details here.
How about this:
`Save the NetworkAttachmentDefinition in the checkup object state in order to detect the CNI plugin used in a later step.`

But I think we negotiated to remove the preflight for now, which may change this thing altogether.

2022-06-08 05:44 UTC, EdDev reviewed
>  vmlatency, checkup, tests: Change clientStub{} receivers to pointer
> 
> In order to test that each VM is created with the correct interface,
> 'clientStub{}' should record them on each create, meaning `clientStub{}`
> is mutated.
> 'clientStub{}' method's should have pointer receivers to avoid its
> new state for being discarded when a method returns.

Please say the same in a way that you do not need to use names from the code. We can read the code diff of this change, what we need in the commit is the "why" and a summary of what is done. (e.g. "... , the client stub in tests needs to save the .... In order to support that, the client stub methods need to be update to work with pointer receivers.".

2022-06-08 05:44 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +)
None of these constants are seem to be used in this parser. I do not think they belong here.

2022-06-08 05:44 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +func ParseCniPlugins(config string) []string {
I think that now you can call the function something like `ListCNIPuginTypes` as that is what it does really.

Also, it may be more accurate to call this file just `config`, so you can add to it other functionalities/helpers (e.g. the check if it is SR-IOV or not).

2022-06-08 05:44 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser_test.go
> +	}
What about the case when it fails to parse (returns that `nil` at the end)?

2022-06-08 05:46 UTC, EdDev requested changes
> Currently SR-IOV and bridge CNI are supported.

This is still incorrect.

2022-06-08 06:11 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/8d4e661948ac5614629e90ba267e915f9e5e2a7c..0b1793adafb2d5a0a4116ba8e645093011f294be): Move NetworkAttachmentDefinition existence check from preflight to setup, following https://github.com/kiagnose/kiagnose/pull/94#discussion_r886728686

2022-06-08 06:43 UTC, ormergi reviewed
[Changes](https://github.com/kiagnose/kiagnose/compare/0b1793adafb2d5a0a4116ba8e645093011f294be..29d3d8ce454ac3fe3a22189308aefe2bc6de6b0d): Updated commit messages and  addressed the following comments.
@EdDev could you please take another look?

2022-06-08 06:43 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +)
Thanks for the heads up I moved them to tests.

2022-06-08 06:43 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser.go
> +func ParseCniPlugins(config string) []string {
Done.

2022-06-08 06:43 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/netattachdef/configparser_test.go
> +	}
Thanks for the heads up, I added a test cover it.

2022-06-08 06:46 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/29d3d8ce454ac3fe3a22189308aefe2bc6de6b0d..d81eb459b5b2f3281ceb9381f06a627278bbde78): Unexport SR-IOV CNI plugin name.

2022-06-08 06:49 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/d81eb459b5b2f3281ceb9381f06a627278bbde78..d985014d47799ff19f5bee2d0cff313391061d25): Add missing CNI plugin names in checkup tests.

2022-06-08 12:16 UTC, EdDev reviewed
Thank you!
All looks good, but please note there are at least two commits with too long subject lines.

2022-06-08 13:07 UTC, ormergi commented
[Changes](https://github.com/kiagnose/kiagnose/compare/d985014d47799ff19f5bee2d0cff313391061d25..52120b2d593c534c09059b07b40cac910e8dbe46): Fix test description and shorten commit message titles.

2022-06-08 13:36 UTC, EdDev approved these changes
Thank you!

2022-06-08 15:06 UTC, merged