documentation: Add checkup API document
kiagnose/kiagnose pull request #95
Opened 2022-05-26 10:05 UTC by orelmisan

Add a document to describe the API between the kiagnose framework
and the checkup.

Signed-off-by: Orel Misan <omisan@redhat.com>

2022-05-31 14:04 UTC, RamLavi commented
Correct me if I am wrong, but isn't this a rewriting of the [Checkup Installation] (https://github.com/kiagnose/kiagnose/pull/93/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R63) in #93?
If so, perhaps it would be better to join the 2 PRs so that the README could link to the checkup-API doc?

2022-05-31 14:15 UTC, orelmisan commented
This document is intended for checkup authors.
It should depict the API between the framework and a checkup.

2022-06-01 07:24 UTC, ormergi commented on docs/checkup_api.md
> +3. Documentation of the checkup results and their meaning.
Please combine those to one.

2022-06-01 08:32 UTC, ormergi requested changes
Hi Orel, thanks for the PR.

Please try to avoid numbering when its not a must, it will make the it more "accessible"
and not feel like reading a contract hehe :slightly_smiling_face: 
Also I would expect some context regarding the framework behavior, it will make it much
easier to understand why things are as they are.
Adding some references to the echo checkup will be nice.

2022-06-01 08:49 UTC, EdDev reviewed
Very nice, thanks.

One general note: Please replace all mentioning of "framework" with "Kiagnose", unless there is some exception which it does not fit.

2022-06-01 08:49 UTC, EdDev commented on docs/checkup_api.md
> +| `status.failureReason` | Checkup failure reason    | `<empty string/input/setup/check>: <free text>` |
I think it is fine. We want to recommend a structure.

2022-06-01 08:49 UTC, EdDev commented on docs/checkup_api.md
> +| `status.succeeded`     | Is the checkup successful | "true"/"false"  As a string                     |
Except for the redundant capital `A`, it looks fine to me.
I am not familiar with a "boolean string".

2022-06-01 08:51 UTC, EdDev commented
> Please try to avoid numbering when its not a must, it will make the it more "accessible"
> and not feel like reading a contract

Isn't this document describing an API? And API **is** a contract.

2022-06-01 09:22 UTC, RamLavi reviewed
Added some comments and questions.

2022-06-01 09:22 UTC, RamLavi commented on docs/checkup_api.md
> +| `RESULT_CONFIGMAP_NAMESPACE` | Output ConfigMap Namespace | True         | Used by the underlying Pod need to write the checkup result |
I'm afraid I don't understand, where is this configured?

2022-06-01 09:22 UTC, RamLavi commented on docs/checkup_api.md
> +3. The checkup shall concatenate its results under the ‘data’ field of the result ConfigMap object, with ‘status.result.’ prefix.
is this status copied to the kiagnose configmap?

2022-06-01 09:34 UTC, orelmisan commented
> another question, might be a stupid one: how does the checkup job have access to kubectl? do we pass the kubeconfig?

@ram Please see https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#directly-accessing-the-rest-api

2022-06-01 10:16 UTC, ormergi commented on docs/checkup_api.md
> +| `status.failureReason` | Checkup failure reason    | `<empty string/input/setup/check>: <free text>` |
Then there should be a note about it, its not obvious from `input/setup/check`

2022-06-06 10:13 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/7b8c95121a9697ff6dc9637175471c79001406f8..f922ffb31cfd3668f087665a29c5a7f74ca6d03c): Answered review comments.

2022-06-06 10:14 UTC, orelmisan commented on docs/checkup_api.md
> +3. Documentation of the checkup results and their meaning.
Done.

2022-06-06 10:15 UTC, orelmisan commented on docs/checkup_api.md
> +3. The framework shall strip the ‘spec.param.’ prefix, and pass the rest of the key as environment variables in upper case.
I've added more context and an example.

2022-06-06 10:15 UTC, orelmisan commented on docs/checkup_api.md
> +| `status.succeeded`     | Is the checkup successful | "true"/"false"  As a string                     |
Changed the "A" to "a".

2022-06-06 10:16 UTC, orelmisan commented on docs/checkup_api.md
> +| `status.failureReason` | Checkup failure reason    | `<empty string/input/setup/check>: <free text>` |
@ormergi Please note that there is free text at the end.
And as @EdDev said, these optional prefixes are helping the user to understand where the checkup had problems.

2022-06-06 10:16 UTC, orelmisan commented on docs/checkup_api.md
> +| `RESULT_CONFIGMAP_NAME`      | Output ConfigMap name      | True         | Used by the underlying Pod need to write the checkup result |
Done.

2022-06-06 10:18 UTC, orelmisan commented on docs/checkup_api.md
> +> it is advisable to read the contents of the `/var/run/secrets/kubernetes.io/serviceaccount/namespace` file.
I've added several other references to the K8s documentation.
I think they cover what this link covers as well.

2022-06-06 10:18 UTC, orelmisan commented on docs/checkup_api.md
> +2. The checkup is required to fill in the following fields:
More context was added.

2022-06-06 10:19 UTC, orelmisan commented on docs/checkup_api.md
> +1. A container image, which could run in a [Kubernetes](https://kubernetes.io/) cluster.
Done, except for:
> what is the process fail/success criteria? (=>the image must update the output in the cm under status.succeeded)

IMO this should be left for the checkup author to decide.

2022-06-06 10:20 UTC, orelmisan commented on docs/checkup_api.md
> +3. The framework shall strip the ‘spec.param.’ prefix, and pass the rest of the key as environment variables in upper case.
The section was rephrased to give more context regarding the work kiagnose does.

2022-06-06 10:21 UTC, orelmisan commented on docs/checkup_api.md
> +| `RESULT_CONFIGMAP_NAMESPACE` | Output ConfigMap Namespace | True         | Used by the underlying Pod need to write the checkup result |
I've moved this section above the custom parameters section.
Is it clearer now?

2022-06-06 10:22 UTC, orelmisan commented on docs/checkup_api.md
> +3. The checkup shall concatenate its results under the ‘data’ field of the result ConfigMap object, with ‘status.result.’ prefix.
Yes, all the data reported by the checkup is reflected to the user-supplied `ConfigMap` object.

2022-06-06 10:25 UTC, orelmisan commented
Rebase.

2022-06-08 07:27 UTC, RamLavi requested changes
Added comments

2022-06-08 07:27 UTC, RamLavi commented on docs/checkup_api.md
> +4. Kiagnose expects the checkup's results to be written to a specified `ConfigMap` object.
we need to have apecific names to our 2 configmaps, in order to avoid confusion (user-supplied cm and result cm?). Then we should stick to these names throughout the README. 
Also, I would recommend to link to the `Output` section below.

2022-06-08 07:27 UTC, RamLavi commented on docs/checkup_api.md
> +A checkup is free to create arbitrary objects in its Namespace.
```suggestion
A checkup is free to create arbitrary objects in the ephemeral Namespace.
```

2022-06-08 07:27 UTC, RamLavi commented on docs/checkup_api.md
> +1. The checkup should expect the following environment variables:
if we are not enumerating the input (which we are not exactly), then the enumeration needs a pretext.

suggestion:
```
## Input

### Pre-set inputs

The checkup should expect the following pre-set environment variables:
| Environment Variable Name    | Description                 | Remarks                                                      |
|------------------------------|-----------------------------|--------------------------------------------------------------|
| `RESULT_CONFIGMAP_NAMESPACE` | Results ConfigMap Namespace | Used by the underlying Pod need to write the checkup results |
| `RESULT_CONFIGMAP_NAME`      | Results ConfigMap name      | Used by the underlying Pod need to write the checkup results |

### custom inputs
Excluding the names of the pre-set environment variables, the checkup author is free to define additional environment variables.
* The variables will be specified by the user on the user-supplied `ConfigMap`, under `data` field.
* The variables should be with following format: `spec.param.<parameter key>: <key value>`.

Kiagnose strips the `spec.param.` prefix, and passes the rest of the key as an environment variable in upper case.

For example:
...
```

2022-06-08 07:27 UTC, RamLavi commented on docs/checkup_api.md
> +1. Kiagnose expects the checkup results to be reported under the `data` field of the result `ConfigMap` object.
I don't think that enumeration is needed at all in this section. we are not counting anything, I think a regular paragraph is better suited

2022-06-08 14:27 UTC, orelmisan commented
[Change](https://github.com/kiagnose/kiagnose/compare/b9a4451f4be811b41d9e6a5ce332666344ad17fa..0595608d840f878299247e394fadb881401469f4): Answered review comments.

2022-06-08 14:27 UTC, orelmisan commented on docs/checkup_api.md
> +1. Kiagnose expects the checkup results to be reported under the `data` field of the result `ConfigMap` object.
The numbering was removed.

2022-06-08 14:28 UTC, orelmisan commented on docs/checkup_api.md
> +1. The checkup should expect the following environment variables:
Thank you for the suggestion.
I've implemented most of it.

2022-06-08 14:28 UTC, orelmisan commented on docs/checkup_api.md
> +A checkup is free to create arbitrary objects in its Namespace.
Done.

2022-06-08 14:28 UTC, orelmisan commented on docs/checkup_api.md
> +1. Kiagnose creates the following objects for a checkup instance:
Done.

2022-06-08 14:36 UTC, orelmisan commented on docs/checkup_api.md
> +4. Kiagnose expects the checkup's results to be written to a specified `ConfigMap` object.
Done.

2022-06-08 15:00 UTC, RamLavi commented on docs/checkup_api.md
> +   - An ephemeral `Namespace`
I was thinking to do it instead but its not a must :)

2022-06-09 15:05 UTC, EdDev approved these changes
Thank you!

2022-06-09 15:05 UTC, merged