vmlatency, automation, e2e: Allow traffic between bridge ports on CI
kiagnose/kiagnose pull request #96
Opened 2022-05-26 13:16 UTC by ormergi

Following https://github.com/kiagnose/kiagnose/pull/96
Currently kubevirt-vm-latency checkup e2e test fails consistently due to connectivity issues between the VMs.
It seems that on CI environment traffic between bridge ports is blocked causing e2e test to fail 
due to no communication between VMs over the bridge network.

It seems that setting `sysctl -w net.bridge.bridge-nf-call-iptables=0` or adding iptables rule [[1]](https://github.com/kubevirt/cluster-network-addons-operator#configure-bridge-on-node) 
in order to enable traffic between bridge ports doesn't work on Github Workflow environment.

While troubleshooting, it seems that unloading `br_netfilter` removed the restrictions on traffic between bridge 
ports and made the test pass.
Unloading `br_netfilter` kernel module, ensures that the bridge traffic is not inspected (e.g: by iptables)
and thus no packet is dropped.

Thanks to @EdDev for suggesting this.

2022-05-26 15:58 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +      grep -Po "(?<=\"status.succeeded\":\")(false|true)+")
Done

2022-05-29 07:43 UTC, orelmisan commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +        run:  sudo rmmod br_netfilter
Can you please describe in the commit message what this command does?

2022-05-29 07:43 UTC, orelmisan commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +      grep -Po "(?<=\"status.succeeded\":\")(false|true)+")
The change was made in the third commit instead of the second.

2022-05-29 07:43 UTC, orelmisan commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    if [ "${succeded}" == "false" ]; then
Please consider changing this condition to `if [ "${succeded}" != "true" ]; then`.
It could catch more problems this way (different spelling, missing field, etc).

2022-05-29 07:43 UTC, orelmisan commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +      echo "Kubevirt VM latency checkup failed" && exit 1
Why is `&&` needed here?

2022-05-29 15:33 UTC, ormergi commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +        run:  sudo rmmod br_netfilter
I didn't add it to the commit message because its pretty standard linux command https://linux.die.net/man/8/rmmod.

2022-05-29 15:33 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +      grep -Po "(?<=\"status.succeeded\":\")(false|true)+")
Done

2022-05-29 15:33 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    if [ "${succeded}" == "false" ]; then
Done

2022-05-29 15:33 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +      echo "Kubevirt VM latency checkup failed" && exit 1
Just a habit of compact way of writing, I used an `if` clause which isnt compact no I realize its odd.
I moved `exit 1` to new line instead of using `&&`.

2022-05-29 15:33 UTC, ormergi commented
@orelmisan @EdDev please take another look.

2022-05-29 15:36 UTC, orelmisan commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +        run:  sudo rmmod br_netfilter
My intention was to describe that this command causes bridge-related traffic no to go through netfilter.

2022-05-30 05:51 UTC, orelmisan commented
@ormergi the e2e test fails because of the max allowed latency tolerance.

2022-05-30 08:20 UTC, ormergi commented
> @ormergi the e2e test fails because of the max allowed latency tolerance.

Its a proof that this PR works :grin: 

I changed max desired latency to 100ms

2022-05-30 08:39 UTC, ormergi commented
/cc @EdDev

2022-05-30 08:39 UTC, ormergi commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +        run:  sudo rmmod br_netfilter
Done, I also updated PR description.

2022-05-30 08:47 UTC, orelmisan commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +        run:  sudo rmmod br_netfilter
Please consider changing `iptables` to `netfilter` (it is part of the kernel module's name).

2022-05-30 09:14 UTC, ormergi commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +        run:  sudo rmmod br_netfilter
I guess you meant for the commit message and description, note that `iptables` is mentioned as an example.

2022-05-30 10:36 UTC, EdDev requested changes
Thanks.

2022-05-30 11:32 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    results=$(${KUBECTL} get configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} -o jsonpath='{.data}')
Not sure what you mean by multi level script, you mean that there should be another target for it?

This PR initially used `grep`, I was asked to use `jq` instead https://github.com/kiagnose/kiagnose/pull/96#discussion_r882674991.

2022-05-30 11:34 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    results=$(${KUBECTL} get configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} -o jsonpath='{.data}')
Also calling get once more is not too expensive at this case, I can change it to reuse first one if you prefer.

2022-05-30 12:49 UTC, ormergi commented on .github/workflows/checkup-kubevirt-vm-latency.check.yaml
> +      - name: Configure system to allow traffic between bridge ports
Sound good, done.

2022-05-30 12:50 UTC, EdDev commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    results=$(${KUBECTL} get configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} -o jsonpath='{.data}')
I meant that you parse the reason out of the output, but this is not needed.
If it fails, we see the full configmap anyway, so there is no need to make it nicer.

2022-05-30 12:53 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    results=$(${KUBECTL} get configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} -o jsonpath='{.data}')
Github Action wont report it as failing job, this is the reason for parsing and exit with retcode 1.

2022-05-30 12:54 UTC, EdDev commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    results=$(${KUBECTL} get configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} -o jsonpath='{.data}')
> This PR initially used grep, I was asked to use jq instead https://github.com/kiagnose/kiagnose/pull/96#discussion_r882674991.

If we are not using it already in some other place, I think we should not add it as a dependency.
We actually have the `kubectl` that can do this partially if you really must.
I would be fine with a grep, but even simpler than what you had before (just grep for the success, anything else is a failure).

2022-05-30 15:07 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    results=$(${KUBECTL} get configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} -o jsonpath='{.data}')
Looking for "succeeded" string only w/o the key is a bit risky, nothing promise that this string will appear only once.

2022-05-30 20:20 UTC, RamLavi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    results=$(${KUBECTL} get configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} -o yaml)
hmm, why is this line removed? don't we want to wait until the KIAGNOSE_JOB finishes the job (pun intended)?

2022-05-30 20:26 UTC, RamLavi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
>                value: ${VM_LATENCY_CONFIGMAP}
commit message is not accurate, cause the checkup can fail if it takes more than the timeout time. I would change it to something like this
```
Currently there is no assertion on the checkup results
and the e2e check job is not checked for actual test outcome.
```

2022-05-30 20:29 UTC, RamLavi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    results=$(${KUBECTL} get configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} -o yaml)
Also, I would prefer printing in json format, just so I could use jq to get the results outcome

2022-05-31 04:58 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    results=$(${KUBECTL} get configmap ${VM_LATENCY_CONFIGMAP} -n ${KIAGNOSE_NAMESPACE} -o yaml)
It was a mistake, sorry for the noise.
Previous iteration was with `jq` I was asked to use `grep` https://github.com/kiagnose/kiagnose/pull/96#discussion_r884683719.

2022-05-31 05:02 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
>                value: ${VM_LATENCY_CONFIGMAP}
> commit message is not accurate, cause the checkup can fail if it takes more than the timeout time. I would change it to something like this

Right, but even then the e2e job would report it succeeded.

2022-05-31 11:10 UTC, EdDev approved these changes
Thanks!

2022-05-31 11:10 UTC, merged