vmlatency, checkup, preflight: Verify NetworkAttachmentDefinition exists
kiagnose/kiagnose pull request #97
Opened 2022-05-26 13:33 UTC by ormergi

Currently the `NetworkAttachmentDefinition` (NAD) namespace and name are passed
to the checkup, w/o verifying it is exists.
In case the NAD does not exists, the checkup will hang until the timeout, because Kubevirt does
not validate that the NAD exists ending up with VMs that wont schedule.

With this PR changes the checkup will verify that before starting the checkup setup,
if the NAD does not exist it will fail early and wont hang until the timeout.
The checkup ClusterRoles manifest is updated with the required permissions to fetch the NAD.

Note that `go.mod` file is updated, but no new dependencies were added.

Signed-off-by: Or Mergi <ormergi@redhat.com>

2022-05-26 15:29 UTC, ormergi commented
/cc @orelmisan

2022-05-29 07:32 UTC, orelmisan reviewed
Thank you for the PR @ormergi.

As I see it, there are multiple changes made in a single commit:
1. Changing the ClusterRole name to `kubevirt-vm-latency-checker`.
2. Addition of a permission to get NetworkAttachmentDefinition objects.
3. Implementation of a Pre-flight check.

Can you please make these changes gradually over several commits?

2022-05-29 07:34 UTC, orelmisan commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    kubevirt-vm-latency-checker
This change should also occur at `checkups/kubevirt-vm-latency/manifests/kubevirt-vm-latency-checkup.yaml`.

2022-05-29 07:35 UTC, orelmisan commented on checkups/kubevirt-vm-latency/go.mod
> +	github.com/k8snetworkplumbingwg/network-attachment-definition-client v0.0.0-20191119172530-79f836b90111
Is there a change required to the `vendor` directory following these changes?

2022-05-29 15:04 UTC, ormergi commented on checkups/kubevirt-vm-latency/go.mod
> +	github.com/k8snetworkplumbingwg/network-attachment-definition-client v0.0.0-20191119172530-79f836b90111
No change were required, note that those dependencies were specified under `require` with "indirect" comment, meaning there is a dependency that uses it.
For example: github.com/k8snetworkplumbingwg/network-attachment-definition-client` is a dependency of Kubevirt client-go uses it.

2022-05-29 15:04 UTC, ormergi commented on checkups/kubevirt-vm-latency/automation/e2e.sh
> +    kubevirt-vm-latency-checker
Done

2022-05-29 15:09 UTC, ormergi commented
> Thank you for the PR @ormergi.
> 
> As I see it, there are multiple changes made in a single commit:
> 
> 1. Changing the ClusterRole name to `kubevirt-vm-latency-checker`.
> 2. Addition of a permission to get NetworkAttachmentDefinition objects.
> 3. Implementation of a Pre-flight check.
> 
> Can you please make these changes gradually over several commits?

Note that 1-3 are all part of the same commit because each change dependent on the other (i,e:  (3) requires (2), (1) wont make sense w/o (3)).

2022-05-29 15:18 UTC, orelmisan commented
> > Thank you for the PR @ormergi.
> > As I see it, there are multiple changes made in a single commit:
> > 
> > 1. Changing the ClusterRole name to `kubevirt-vm-latency-checker`.
> > 2. Addition of a permission to get NetworkAttachmentDefinition objects.
> > 3. Implementation of a Pre-flight check.
> > 
> > Can you please make these changes gradually over several commits?
> 
> Note that 1-3 are all part of the same commit because each change dependent on the other (i,e: (3) requires (2), (1) wont make sense w/o (3)).

I argue that the ClusterRole rename to `kubevirt-vm-latency-checker` does stand on its own.

2022-05-29 15:35 UTC, ormergi commented
> I argue that the ClusterRole rename to `kubevirt-vm-latency-checker` does stand on its own.

Do you insist of extracting the rename changes to new commit?

2022-05-29 15:39 UTC, orelmisan commented
> > I argue that the ClusterRole rename to `kubevirt-vm-latency-checker` does stand on its own.
> 
> Do you insist of moving the rename changes to new commit?

At least write the reason for this change it in the commit message if you don't want to split it.

2022-05-29 19:31 UTC, EdDev requested changes
Thanks.

2022-05-29 19:31 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +	return c.KubevirtClient.NetworkClient().K8sCniCncfIoV1().NetworkAttachmentDefinitions(namespace).
Ohh my, you are telling me that kubevirt client is exposing the NAD client?
I prefer not to depend on this, can we have a direct access to the client?

2022-05-30 07:14 UTC, orelmisan commented on checkups/kubevirt-vm-latency/go.mod
> +	github.com/k8snetworkplumbingwg/network-attachment-definition-client v0.0.0-20191119172530-79f836b90111
Thank you for the explanation.

2022-05-30 08:16 UTC, ormergi reviewed
@EdDev thanks for the review, I resolved your comments.
Please take another look.

2022-05-30 08:16 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +	cncfcniv1 "github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1"
Done

2022-05-30 08:16 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +func TestCheckupPreflightShouldFailWhenFailToGetNetAttachDef(t *testing.T) {
Looking at this again, I understand why it is confusing :sweat_smile:.
What I wanted to express is "checkup preflight should fail when it fails to get the net-attach-def".
I will change it to what you suggest it sounds good.

2022-05-30 08:16 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
> +	failGetNetAttachDef error
Done

2022-05-30 08:16 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +	cncfcniv1 "github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1"
Looks good, done (all over).

2022-05-30 08:16 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +func (c *Client) GetNetAttachDef(namespace, name string) (*cncfcniv1.NetworkAttachmentDefinition, error) {
Done.

2022-05-30 10:24 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	var err error
Why do you need this?
Can't you do `if _, err := c.client.GetNetworkAttachmentDefinition(` below?

2022-05-30 10:24 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	); err != nil {
I think the preflight check should be specific about the missing entity, not if there are communication or access problems.
I think you should fail only in one condition, anything else should be ignored.

2022-05-30 10:24 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +	netattdefclient "kubevirt.io/client-go/generated/network-attachment-definition-client/clientset/versioned/typed/k8s.cni.cncf.io/v1"
I see you still use the kubevirt client.

2022-05-30 10:40 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	); err != nil {
If there are communication / access issues at such early stage why continue the flow?
It is likely that there will be more issues later on that will cause the checkup to fail.
Failing faster will improve the UX, its one of the reasons for having preflight in the first place.

2022-05-30 11:09 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +	netattdefclient "kubevirt.io/client-go/generated/network-attachment-definition-client/clientset/versioned/typed/k8s.cni.cncf.io/v1"
Right, `kubevirt.io/client-go` includes generated version of  `NetAttachDef` client [[1]] (https://github.com/kubevirt/kubevirt/tree/main/staging/src/kubevirt.io/client-go/generated/network-attachment-definition-client/clientset/versioned) [[2]](https://github.com/kubevirt/kubevirt/blob/main/hack/generate.sh#L65).
Its different from using `github.com/k8snetworkplumbingwg/network-attachment-definition-client` as it will bring simmilar files to what Kubevirt client-go includes.

Note that once we switch to controller-runtime client we will not need neither of Kubevirt client-go or the `NetAttachDef` client.

2022-05-30 12:59 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	); err != nil {
The short answer is: This is not the k8s way.
The long answer is: Accessing the NAD directly is not a must to pass the checkup at this moment. Furthermore, it is not the preflight interest about intermediate disconnection or unavailability of the API server.
When the parsing of the NAD is introduced, it makes sense to fail there if the data is not collected, not in a different place.

2022-05-30 13:01 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +	netattdefclient "kubevirt.io/client-go/generated/network-attachment-definition-client/clientset/versioned/typed/k8s.cni.cncf.io/v1"
> Its different from using github.com/k8snetworkplumbingwg/network-attachment-definition-client as it will bring simmilar files to what Kubevirt client-go includes.

I do not understand if this means it is not possible or something else.
If you attempt to do so, will something break?

2022-05-30 15:02 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	); err != nil {
Initially this commit was part of #94, I was asked to move it to another PR, now it lake context and we have this discussion that could be obsolete.
With #94 PR changes fetching the NAD is a must.

Think about this scenario, the NAD is not exist and there was an issue with accessing the cluster API server,
the preflight will pass (false positive) and the checkup setup will later on fail due to missing data / NAD not found error.
Its wrong, isnt it?

2022-05-30 15:05 UTC, ormergi commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +	netattdefclient "kubevirt.io/client-go/generated/network-attachment-definition-client/clientset/versioned/typed/k8s.cni.cncf.io/v1"
> I do not understand if this means it is not possible or something else.
If you attempt to do so, will something break?

It doesn't work,` kubevirt.io/client-go` includes its own generated version of network-attachment-definition client, 
meaning we cannot use `import "github.com/k8snetworkplumbingwg/network-attachment-definition-client/..."`  because there are missing files (of the clientset itself).

2022-05-30 19:14 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
> +	netattdefclient "kubevirt.io/client-go/generated/network-attachment-definition-client/clientset/versioned/typed/k8s.cni.cncf.io/v1"
It sounds wrong to me, but I cannot dig into this further at this time.
I do not like the fact that we use the client provided by kubevirt, as accessing the NAD should be independent.

2022-05-30 19:22 UTC, EdDev commented on checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
> +	); err != nil {
And at the same time, it is not that accurate to fail due to a glitch on the API server.
There are a wide range of options to choose from, including retry, fail only on things you care about (I guess that is my suggestion) or just fail on first attempt as you suggested.

I do not know how a different action in a different PR will influence this decision.
But it does influence what fails and when.

I guess there is no one best path here, all have costs.
I am fine keeping it as is, thanks.

2022-05-30 19:23 UTC, EdDev approved these changes
Thank you!

2022-05-30 19:23 UTC, EdDev commented
@orelmisan , please check if all your concerns have been responded.

2022-05-30 19:33 UTC, orelmisan approved these changes
Thank you @ormergi!

2022-05-31 08:05 UTC, merged